<!-- SPDX-License-Identifier: AGPL-3.0-only -->
<script setup lang="ts">
import { computed } from 'vue'
import AppIcon from '../../AppIcon.vue'
import HarnessMark from '../../agents/HarnessMark.vue'
import { lineName, type BoardCard } from '../../../lib/modelsBoard'
const props = defineProps<{ card: BoardCard; number?: number; movable: boolean; forbidden?: boolean; placeholder?: boolean; subtitle?: string; thinking?: string; german: boolean }>()
defineEmits<{ open: [event: MouseEvent]; keys: [event: KeyboardEvent]; press: [event: PointerEvent] }>()
const thinkingWord = computed(() => ({ lean: props.german ? 'Knapp' : 'Lean', standard: 'Standard', deep: props.german ? 'Gründlich' : 'Deep', max: props.german ? 'Maximal' : 'Max', review: props.german ? 'Prüfung' : 'Review' })[props.thinking ?? ''] ?? props.card.harness)
const detail = computed(() => props.card.lock ? [{ top: props.german ? 'Oben angepinnt' : 'Pinned to top', bottom: props.german ? 'Unten angepinnt' : 'Pinned to bottom', not: props.german ? 'Nicht erlaubt' : 'Not allowed' }[props.card.lock.value], props.card.lock.why, props.card.lock.who, props.card.lock.at ? new Date(props.card.lock.at).toLocaleString(props.german ? 'de-AT' : 'en-GB') : '', props.card.lock.scope].filter(Boolean).join(' · ') : `${props.card.harness} · ${props.card.effort}`)
</script>
<template>
  <button class="mc" type="button" :class="{ locked: !!card.lock, forbidden, placeholder }" :data-line="card.line" :aria-label="`${number ? `${number}. ` : ''}${lineName(card)} · ${detail}`" :data-tip="`${lineName(card)} · ${detail}`" aria-haspopup="menu" :aria-disabled="!movable || undefined" @click="$emit('open', $event)" @keydown="$emit('keys', $event)" @pointerdown="$emit('press', $event)">
    <span class="mc-n" aria-hidden="true"><span v-if="number" class="number">{{ number }}</span><AppIcon v-else-if="card.lock" name="lock" :size="12" /><AppIcon v-else name="grip" :size="12" /><AppIcon v-if="number && movable" class="grip" name="grip" :size="12" /></span>
    <span class="mc-name">{{ lineName(card) }}</span><span class="mc-flag"><AppIcon v-if="card.lock" :name="card.lock.kind === 'rule' && movable ? 'pin' : 'lock'" :size="12" /></span>
    <span class="mc-sub"><HarnessMark :harness="card.harness" :size="14" /><span v-if="subtitle">{{ subtitle }}</span><span v-else>{{ thinkingWord }} · <strong>{{ card.effort }}</strong></span></span>
  </button>
</template>
<style scoped>
.mc { display: grid; grid-template-columns: 20px minmax(0, 1fr) 14px; grid-template-rows: 20px 16px; align-items: baseline; column-gap: 6px; width: 100%; height: 48px; padding: 6px 8px 6px 6px; border: 0; border-radius: 10px; background: var(--surface-raised); box-shadow: var(--shadow-btn); color: var(--ink); text-align: left; font: inherit; cursor: grab; touch-action: pan-x; user-select: none; }.mc:hover { box-shadow: var(--shadow-btn-hover); }.mc:focus-visible { outline: 2px solid var(--teal); outline-offset: 2px; }.mc-n { grid-column: 1; display: flex; justify-content: flex-end; align-items: center; font: 600 11px/20px var(--mono); color: var(--ink-2); }.grip { display: none; }.mc:hover .number:has(+ .grip), .mc:focus-visible .number:has(+ .grip) { display: none; }.mc:hover .grip, .mc:focus-visible .grip { display: block; }.mc-name { grid-row: 1; grid-column: 2; min-width: 0; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; font-size: 13px; font-weight: 650; line-height: 20px; }.mc-flag { grid-row: 1; grid-column: 3; align-self: center; display: grid; place-items: center; color: var(--ink-3); }.mc-sub { grid-row: 2; grid-column: 2 / 4; display: flex; align-items: center; gap: 4px; min-width: 0; overflow: hidden; white-space: nowrap; font-size: 11px; line-height: 16px; color: var(--ink-3); }.mc-sub strong { font-weight: 600; color: var(--ink-2); }.mc-sub > span:last-child { overflow: hidden; text-overflow: ellipsis; }.mc.locked { cursor: default; background: var(--surface-sunken); }.mc.forbidden { background: transparent; box-shadow: inset 0 0 0 1px var(--line); }.forbidden .mc-name, .forbidden .mc-sub { opacity: .6; }.mc[aria-disabled="true"] { cursor: default; }.mc.placeholder { background: var(--row-selected); box-shadow: inset 0 0 0 1.5px var(--chip-teal-line); }.placeholder > * { visibility: hidden; }
</style>
