<!-- SPDX-License-Identifier: AGPL-3.0-only -->
<script setup lang="ts">
import { computed } from 'vue'
import AppIcon from '../../AppIcon.vue'
import HoverText from './HoverText.vue'
import { resolutionLabel, type ModelResolution } from '../../../lib/modelsSettings'
const props = defineProps<{ kind: string; kindDefinition: string; kindLabels: string[]; project: string; projectLabels: string[]; person: string; resolution: ModelResolution | null; reviewer: ModelResolution | null; loading: boolean; error: string; german: boolean }>()
const emit = defineEmits<{ kind: [event: MouseEvent]; project: [event: MouseEvent]; why: [event: MouseEvent] }>()
const text = (en: string, de: string) => props.german ? de : en
const result = computed(() => props.error || (props.loading ? text('Checking which models can run…', 'Verfügbare Modelle werden geprüft…') : !props.resolution?.profile ? text(`waits: ${props.resolution?.trace.blocked || 'no model is available.'}`, `wartet: ${props.resolution?.trace.blocked || 'Kein Modell ist verfügbar.'}`) : `${resolutionLabel(props.resolution, props.german)}, ${text('reviewed by', 'geprüft von')} ${resolutionLabel(props.reviewer, props.german)}.`))
</script>
<template>
  <div class="sentence" data-next-sentence>
    <AppIcon name="arrow" :size="14" />
    <div class="context-row" data-next-context><span>{{ text('The next', 'Die nächste Arbeit in') }}</span><button type="button" class="pick" :aria-label="`${text('Kind of work', 'Art der Arbeit')}: ${kind}`" data-next-kind :data-tip="kindDefinition" @click="emit('kind', $event)"><span class="reserved"><HoverText :text="kind" /><span v-for="label in kindLabels" :key="label" class="reserve" aria-hidden="true">{{ label }}</span></span><AppIcon name="chevron" :size="12" /></button><span>{{ text('in', 'in') }}</span><button type="button" class="pick" :aria-label="`${text('Project', 'Projekt')}: ${project}`" data-next-project @click="emit('project', $event)"><span class="reserved"><HoverText :text="project" /><span v-for="label in projectLabels" :key="label" class="reserve" aria-hidden="true">{{ label }}</span></span><AppIcon name="chevron" :size="12" /></button><span>{{ text('for', 'für') }} {{ person }}:</span></div>
    <div class="result-row"><HoverText :text="result" aria-live="polite" /><button type="button" class="link-btn" data-next-why :aria-label="text('Why this model?', 'Warum dieses Modell?')" @click="emit('why', $event)">{{ text('Why?', 'Warum?') }}</button></div>
  </div>
</template>
<style scoped>.sentence { display: grid; grid-template-columns: 14px minmax(0, 1fr); grid-template-rows: 40px 40px; align-items: center; gap: 0 10px; margin-top: 16px; padding: 8px 16px; border-radius: 12px; background: var(--surface-sunken); font-size: 14px; color: var(--ink); }.sentence > svg { grid-row: 1 / 3; color: var(--ink-3); }.context-row { display: flex; align-items: center; gap: 4px; white-space: nowrap; min-width: 0; overflow-x: auto; scrollbar-width: thin; }.context-row > span { flex: none; }.pick { display: inline-flex; align-items: center; gap: 4px; min-width: 0; min-height: 36px; flex: none; border: 0; border-radius: 5px; padding: 4px; color: var(--ink); background: transparent; font: inherit; font-weight: 650; }.reserved { display: grid; min-width: 0; }.reserved > * { grid-area: 1 / 1; }.reserved > .reserve { visibility: hidden; pointer-events: none; }.result-row { display: flex; align-items: center; gap: 8px; min-width: 0; grid-column: 2; }.result-row > span { flex: 1; font-weight: 600; }.link-btn { flex: none; min-height: 36px; padding: 4px; border: 0; border-radius: 5px; background: transparent; color: var(--teal-ink); font: inherit; font-size: 13px; }.link-btn:focus-visible { outline: none; box-shadow: var(--focus-ring); }.pick:focus-visible { outline: none; box-shadow: var(--focus-ring); }@media (max-width: 860px), (pointer: coarse) { .sentence { grid-template-rows: 48px 48px; padding: 8px 10px; }.pick, .link-btn { min-height: 44px; } }</style>
