// SPDX-License-Identifier: AGPL-3.0-only

//go:build ignore

// generate turns the vendored gitleaks default configuration into the Go
// rule table the credential detector applies (../gitleaks_rules.go).
//
// To update: take the latest release tag
//
//	gh release view -R gitleaks/gitleaks --json tagName
//	gh api 'repos/gitleaks/gitleaks/contents/config/gitleaks.toml?ref=<tag>' -H 'Accept: application/vnd.github.raw' > gitleaks.toml
//	gh api 'repos/gitleaks/gitleaks/contents/LICENSE?ref=<tag>' -H 'Accept: application/vnd.github.raw' > LICENSE
//
// then set the tag in the go:generate line in ../detect.go and run
// `go generate ./internal/credentialguard`. Rules that cannot apply to free text
// (path-scoped) or do not compile under Go's RE2 are skipped and listed here,
// at generation time, never at run time.
//
// The file is parsed by a small reader for the subset of TOML gitleaks
// writes; an unknown key fails the run so a new rule feature is not dropped
// silently.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"regexp"
	"strconv"
	"strings"
	"unicode"
)

type allowlist struct {
	condition string
	target    string
	regexes   []string
	stopwords []string
	paths     bool
	commits   bool
}

type rule struct {
	id          string
	regex       string
	path        string
	entropy     float64
	secretGroup int
	keywords    []string
	allow       []allowlist
}

func main() {
	in := flag.String("in", "gitleaks/gitleaks.toml", "vendored gitleaks configuration")
	out := flag.String("out", "gitleaks_rules.go", "generated Go file")
	tag := flag.String("tag", "", "gitleaks release tag the configuration was taken from")
	flag.Parse()
	if *tag == "" {
		log.Fatal("-tag is required")
	}
	raw, err := os.ReadFile(*in)
	if err != nil {
		log.Fatal(err)
	}
	sum := sha256.Sum256(raw)
	global, rules, err := parse(string(raw))
	if err != nil {
		log.Fatalf("%s: %v", *in, err)
	}

	var body bytes.Buffer
	var skipped []string
	skip := func(id, reason string) {
		skipped = append(skipped, id+": "+reason)
		fmt.Printf("skip %s: %s\n", id, reason)
	}
	for _, r := range rules {
		switch {
		case r.path != "":
			skip(r.id, "scoped to file paths")
			continue
		case r.regex == "":
			skip(r.id, "no content pattern")
			continue
		}
		re, err := regexp.Compile(r.regex)
		if err != nil {
			skip(r.id, "does not compile under RE2: "+err.Error())
			continue
		}
		if r.secretGroup > re.NumSubexp() {
			skip(r.id, fmt.Sprintf("secretGroup %d beyond %d groups", r.secretGroup, re.NumSubexp()))
			continue
		}
		// A pattern that is mostly literal matches its own text; mark the
		// line so a gitleaks scan of this repository does not report it.
		note := ""
		if re.MatchString(r.regex) {
			note = " // gitleaks:allow"
		}
		fmt.Fprintf(&body, "{id: %s, regex: %s, keywords: %s, entropy: %s, secretGroup: %d, allow: %s},%s\n",
			strconv.Quote(r.id), goString(r.regex), goStrings(lower(r.keywords)),
			strconv.FormatFloat(r.entropy, 'g', -1, 64), r.secretGroup, allowSpecs(r.id, r.allow), note)
	}
	globalAllow := allowSpecs("global allowlist", []allowlist{global})

	var src bytes.Buffer
	fmt.Fprintf(&src, `// SPDX-License-Identifier: MIT

// Code generated by gitleaks/generate.go; DO NOT EDIT.

// Credential rules from the gitleaks default configuration.
//
//	Source:  https://github.com/gitleaks/gitleaks/blob/%s/config/gitleaks.toml
//	Tag:     %s
//	SHA-256: %s
//
// Copyright (c) 2019 Zachary Rice. Licensed under the MIT License; the full
// text is in gitleaks/LICENSE.
`, *tag, *tag, hex.EncodeToString(sum[:]))
	if len(skipped) > 0 {
		src.WriteString("//\n// Skipped at generation:\n")
		for _, s := range skipped {
			fmt.Fprintf(&src, "//   - %s\n", s)
		}
	}
	fmt.Fprintf(&src, "\npackage credentialguard\n\nconst gitleaksTag = %q\n\nvar gitleaksGlobalAllow = %s\n\nvar gitleaksRules = []leakRuleSpec{\n%s}\n",
		*tag, globalAllow, body.String())
	formatted, err := format.Source(src.Bytes())
	if err != nil {
		log.Fatalf("format: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s: %d rules, %d skipped\n", *out, len(rules)-len(skipped), len(skipped))
}

// allowSpecs keeps the allowlist checks that can apply to free text: regexes
// and stop words. A list that also needs a path or commit (AND) can never
// hold without one, so it is dropped; path- or commit-only lists likewise.
func allowSpecs(id string, lists []allowlist) string {
	var parts []string
	for _, a := range lists {
		if a.condition == "AND" && (a.paths || a.commits) {
			fmt.Printf("drop %s allowlist: needs a path or commit\n", id)
			continue
		}
		var regexes []string
		for _, r := range a.regexes {
			if _, err := regexp.Compile(r); err != nil {
				fmt.Printf("drop %s allowlist regex: does not compile under RE2: %v\n", id, err)
				continue
			}
			regexes = append(regexes, r)
		}
		if len(regexes) == 0 && len(a.stopwords) == 0 {
			continue
		}
		parts = append(parts, fmt.Sprintf("{target: %q, regexes: %s, stopwords: %s}", a.target, goStrings(regexes), goStrings(lower(a.stopwords))))
	}
	if id == "global allowlist" {
		if len(parts) == 0 {
			return "leakAllowSpec{}"
		}
		return "leakAllowSpec" + parts[0]
	}
	if len(parts) == 0 {
		return "nil"
	}
	return "[]leakAllowSpec{" + strings.Join(parts, ", ") + "}"
}

func lower(values []string) []string {
	out := make([]string, len(values))
	for i, v := range values {
		out[i] = strings.ToLower(v)
	}
	return out
}

func goString(s string) string {
	if strings.ContainsAny(s, "`\r") {
		return strconv.Quote(s)
	}
	return "`" + s + "`"
}

func goStrings(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = goString(v)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

// parse reads the global allowlist and the rules.
func parse(src string) (allowlist, []rule, error) {
	p := &parser{src: src}
	var global allowlist
	var rules []rule
	section := ""
	for {
		p.skipSpace(true)
		if p.eof() {
			return global, rules, nil
		}
		if p.peek() == '[' {
			header := p.until('\n')
			switch strings.TrimSpace(header) {
			case "[allowlist]":
				section = "global"
			case "[[rules]]":
				section = "rule"
				rules = append(rules, rule{})
			case "[[rules.allowlists]]":
				if len(rules) == 0 {
					return global, nil, p.errorf("allowlist before any rule")
				}
				section = "allow"
				r := &rules[len(rules)-1]
				r.allow = append(r.allow, allowlist{})
			default:
				return global, nil, p.errorf("unknown table %s", header)
			}
			continue
		}
		key := p.key()
		p.skipSpace(false)
		if !p.consume('=') {
			return global, nil, p.errorf("expected = after %s", key)
		}
		value, err := p.value()
		if err != nil {
			return global, nil, err
		}
		switch section {
		case "":
			if key != "title" && key != "minVersion" {
				return global, nil, p.errorf("unknown top-level key %s", key)
			}
		case "global":
			if err := setAllow(&global, key, value); err != nil {
				return global, nil, p.errorf("%v", err)
			}
		case "allow":
			r := &rules[len(rules)-1]
			if err := setAllow(&r.allow[len(r.allow)-1], key, value); err != nil {
				return global, nil, p.errorf("%v", err)
			}
		case "rule":
			if err := setRule(&rules[len(rules)-1], key, value); err != nil {
				return global, nil, p.errorf("%v", err)
			}
		}
	}
}

func setRule(r *rule, key string, v any) error {
	var err error
	switch key {
	case "id":
		r.id, err = asString(v)
	case "description":
	case "regex":
		r.regex, err = asString(v)
	case "path":
		r.path, err = asString(v)
	case "keywords":
		r.keywords, err = asStrings(v)
	case "entropy":
		r.entropy, err = asNumber(v)
	case "secretGroup":
		var n float64
		n, err = asNumber(v)
		r.secretGroup = int(n)
	default:
		return fmt.Errorf("unknown rule key %s", key)
	}
	return err
}

func setAllow(a *allowlist, key string, v any) error {
	var err error
	switch key {
	case "description":
	case "condition":
		a.condition, err = asString(v)
	case "regexTarget":
		a.target, err = asString(v)
		if a.target != "match" && a.target != "line" && a.target != "secret" {
			return fmt.Errorf("unknown regexTarget %q", a.target)
		}
		if a.target == "secret" {
			a.target = ""
		}
	case "regexes":
		a.regexes, err = asStrings(v)
	case "stopwords":
		a.stopwords, err = asStrings(v)
	case "paths":
		a.paths = true
	case "commits":
		a.commits = true
	default:
		return fmt.Errorf("unknown allowlist key %s", key)
	}
	return err
}

func asString(v any) (string, error) {
	if s, ok := v.(string); ok {
		return s, nil
	}
	return "", fmt.Errorf("expected a string, got %T", v)
}

func asNumber(v any) (float64, error) {
	if n, ok := v.(float64); ok {
		return n, nil
	}
	return 0, fmt.Errorf("expected a number, got %T", v)
}

func asStrings(v any) ([]string, error) {
	list, ok := v.([]any)
	if !ok {
		return nil, fmt.Errorf("expected an array, got %T", v)
	}
	out := make([]string, 0, len(list))
	for _, item := range list {
		s, err := asString(item)
		if err != nil {
			return nil, err
		}
		out = append(out, s)
	}
	return out, nil
}

type parser struct {
	src string
	pos int
}

func (p *parser) eof() bool  { return p.pos >= len(p.src) }
func (p *parser) peek() byte { return p.src[p.pos] }

func (p *parser) errorf(format string, args ...any) error {
	line := strings.Count(p.src[:min(p.pos, len(p.src))], "\n") + 1
	return fmt.Errorf("line %d: %s", line, fmt.Sprintf(format, args...))
}

func (p *parser) consume(c byte) bool {
	if !p.eof() && p.peek() == c {
		p.pos++
		return true
	}
	return false
}

func (p *parser) until(c byte) string {
	start := p.pos
	for !p.eof() && p.peek() != c {
		p.pos++
	}
	return p.src[start:p.pos]
}

// skipSpace skips blanks and comments, and line breaks when newlines is set.
func (p *parser) skipSpace(newlines bool) {
	for !p.eof() {
		switch c := p.peek(); {
		case c == ' ' || c == '\t' || c == '\r':
			p.pos++
		case c == '\n' && newlines:
			p.pos++
		case c == '#':
			p.until('\n')
		default:
			return
		}
	}
}

func (p *parser) key() string {
	start := p.pos
	for !p.eof() && (unicode.IsLetter(rune(p.peek())) || unicode.IsDigit(rune(p.peek())) || p.peek() == '_') {
		p.pos++
	}
	return p.src[start:p.pos]
}

func (p *parser) value() (any, error) {
	p.skipSpace(false)
	if p.eof() {
		return nil, p.errorf("missing value")
	}
	switch c := p.peek(); {
	case strings.HasPrefix(p.src[p.pos:], "'''"):
		end := strings.Index(p.src[p.pos+3:], "'''")
		if end < 0 {
			return nil, p.errorf("unterminated literal string")
		}
		s := p.src[p.pos+3 : p.pos+3+end]
		p.pos += end + 6
		// A literal string may end with up to two extra quotes.
		for i := 0; i < 2 && p.consume('\''); i++ {
			s += "'"
		}
		return strings.TrimPrefix(s, "\n"), nil
	case c == '\'':
		p.pos++
		s := p.until('\'')
		if !p.consume('\'') {
			return nil, p.errorf("unterminated literal string")
		}
		return s, nil
	case c == '"':
		start := p.pos
		p.pos++
		for !p.eof() && p.peek() != '"' {
			if p.peek() == '\\' {
				p.pos++
			}
			p.pos++
		}
		if !p.consume('"') {
			return nil, p.errorf("unterminated string")
		}
		s, err := strconv.Unquote(p.src[start:p.pos])
		if err != nil {
			return nil, p.errorf("string: %v", err)
		}
		return s, nil
	case c == '[':
		p.pos++
		var list []any
		for {
			p.skipSpace(true)
			if p.consume(']') {
				return list, nil
			}
			v, err := p.value()
			if err != nil {
				return nil, err
			}
			list = append(list, v)
			p.skipSpace(true)
			if !p.consume(',') {
				p.skipSpace(true)
				if !p.consume(']') {
					return nil, p.errorf("expected , or ] in array")
				}
				return list, nil
			}
		}
	case c == '-' || c == '+' || (c >= '0' && c <= '9'):
		start := p.pos
		for !p.eof() && strings.IndexByte("+-.0123456789eE_", p.peek()) >= 0 {
			p.pos++
		}
		n, err := strconv.ParseFloat(strings.ReplaceAll(p.src[start:p.pos], "_", ""), 64)
		if err != nil {
			return nil, p.errorf("number: %v", err)
		}
		return n, nil
	}
	return nil, p.errorf("unsupported value")
}
