// SPDX-License-Identifier: AGPL-3.0-only

package authz

import (
	"context"
	"errors"
	"strings"
)

// PublicRoute marks an explicitly public API route. Unknown routes have no
// declaration and must be denied by the authorization boundary.
const PublicRoute = "public"

// RoutePermissions declares the permission for each registered API pattern.
// Customer quote routes accept one of two permissions; the quote handler also
// verifies the recipient binding. Authentication and public capability routes
// remain explicit entries so route coverage can detect new unreviewed paths.
var RoutePermissions = map[string]string{
	"DELETE /api/agent-keys/{id}":                                    "keys.manage",
	"DELETE /api/members/invites/{id}":                               "members.manage",
	"DELETE /api/members/{principal_id}/aliases/{from_principal_id}": "members.manage",
	"DELETE /api/attachments/{id}":                                   "attachments.delete",
	"DELETE /api/crm/contacts/{contactId}":                           "crm.write",
	"DELETE /api/crm/organisations/{organisationId}":                 "crm.write",
	"DELETE /api/inbox/targets/{targetId}":                           "inbox.send|inbox.manage",
	"DELETE /api/kinds/{kindId}":                                     "kinds.manage",
	"DELETE /api/knowledge/{id}":                                     "knowledge.delete",
	"DELETE /api/me/avatar":                                          "profile.write|profile.portal_write",
	"DELETE /api/nodes/{nodeId}":                                     "nodes.delete",
	"DELETE /api/nodes/{nodeId}/comments/{commentId}":                "comments.delete",
	"DELETE /api/project-groups/{groupId}":                           "project_groups.write",
	"DELETE /api/quote-profiles/{profileId}":                         "quotes.write",
	"DELETE /api/quotes/{quoteId}":                                   "quotes.delete",
	"DELETE /api/quotes/{quoteId}/presence/{sessionId}":              "quotes.delete",
	"DELETE /api/relations/{relationId}":                             "relations.delete",
	"DELETE /api/roles/{id}":                                         "roles.manage",
	"DELETE /api/tags/{tagId}":                                       "tags.manage",
	"DELETE /api/time-entries/{id}":                                  "hours.write",
	"DELETE /api/views/{viewId}":                                     "views.write",
	"GET /api/agent-accounts":                                        "account.read",
	"GET /api/agent-keys":                                            "keys.read",
	"GET /api/approvals":                                             "approvals.read",
	"GET /api/audit":                                                 "audit.read",
	"GET /api/attachments/{id}/content":                              "attachments.read",
	"GET /api/auth/callback":                                         "public",
	"GET /api/auth/login":                                            "public",
	"GET /api/authz/permissions":                                     "roles.read",
	"GET /api/business/principals":                                   "members.read",
	"GET /api/cost-units/{costUnitId}/rates":                         "cost_units.read",
	"GET /api/crm/contacts/{contactId}":                              "crm.read",
	"GET /api/crm/organisations":                                     "crm.read",
	"GET /api/crm/organisations/{organisationId}":                    "crm.read",
	"GET /api/crm/organisations/{organisationId}/contacts":           "crm.read",
	"GET /api/crm/organisations/{organisationId}/note-ai":            "crm.manage",
	"GET /api/crm/organisations/{organisationId}/related":            "crm.read",
	"GET /api/crm/organisations/{organisationId}/sync-status":        "crm.read",
	"GET /api/crm/projects/{projectId}/cooperation":                  "crm.read",
	"GET /api/crm/providers":                                         "crm.read",
	"GET /api/crm/providers/search":                                  "crm.read",
	"GET /api/events":                                                "events.read",
	"GET /api/events/stream":                                         "events.read",
	"GET /api/from-classic":                                          "nodes.read",
	"GET /api/harness-sessions":                                      "harness.read",
	"GET /api/harness-sessions/live":                                 "nodes.read",
	"GET /api/health":                                                "public",
	"GET /api/imports":                                               "imports.read",
	"GET /api/imports/{importId}":                                    "imports.read",
	"GET /api/inbox/messages":                                        "inbox.read",
	"GET /api/inbox/messages/{messageId}/receipt":                    "inbox.receipt",
	"GET /api/inbox/stream":                                          "inbox.read",
	"GET /api/inbox/targets":                                         "inbox.read",
	"GET /api/kinds":                                                 "nodes.read",
	"GET /api/kinds/{kindId}":                                        "nodes.read",
	"GET /api/knowledge":                                             "knowledge.read",
	"GET /api/knowledge/graph":                                       "knowledge.read",
	"GET /api/knowledge/resolve":                                     "knowledge.read",
	"GET /api/knowledge/{id}":                                        "knowledge.read",
	"GET /api/me":                                                    "profile.read|profile.portal_read",
	"GET /api/me/greeting":                                           "profile.read|profile.portal_read",
	"GET /api/me/permissions":                                        "authz.read",
	"GET /api/me/profile":                                            "profile.read|profile.portal_read",
	"GET /api/members":                                               "members.read",
	"GET /api/models":                                                "models.read",
	"GET /api/models/resolve":                                        "models.read",
	"GET /api/node-keys/{key}":                                       "nodes.read",
	"GET /api/nodes":                                                 "nodes.read",
	"GET /api/nodes/lookup":                                          "nodes.read",
	"GET /api/nodes/tree":                                            "nodes.read",
	"GET /api/nodes/{nodeId}":                                        "nodes.read",
	"GET /api/nodes/{nodeId}/activity":                               "events.read",
	"GET /api/nodes/{nodeId}/attachments":                            "attachments.read",
	"GET /api/nodes/{nodeId}/time-totals":                            "hours.read",
	"GET /api/people/{principalId}/avatar/{size}":                    "profile.read",
	"GET /api/plugins":                                               "plugins.read",
	"GET /api/preferences/{key}":                                     "views.read",
	"GET /api/project-groups":                                        "project_groups.read",
	"GET /api/projects":                                              "nodes.read",
	"GET /api/projects/{projectId}/harness-sessions":                 "harness.read",
	"GET /api/projects/{projectId}/harness-sessions/orchestrator":    "harness.read",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}":     "harness.read",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/controls/{controlId}": "harness.read",
	"GET /api/projects/{projectId}/intake":                                            "intake.read",
	"GET /api/projects/{projectId}/journey":                                           "journey.read",
	"GET /api/projects/{projectId}/members":                                           "members.read",
	"PUT /api/projects/{projectId}/members/{principal_id}":                            "members.manage",
	"DELETE /api/projects/{projectId}/members/{principal_id}":                         "members.manage",
	"GET /api/projects/{projectId}/message-deliveries":                                "inbox.manage",
	"GET /api/projects/{projectId}/message-targets":                                   "inbox.manage",
	"GET /api/projects/{projectId}/messages":                                          "inbox.manage",
	"GET /api/projects/{projectId}/messages/listen":                                   "inbox.read",
	"GET /api/projects/{projectId}/releases/{releaseId}/walker":                       "releases.read",
	"GET /api/projects/{projectId}/requirements":                                      "requirements.read",
	"GET /api/public/quotes/{publicTenant}/{token}":                                   "public",
	"GET /api/public/quotes/{publicTenant}/{token}/pdf":                               "public",
	"GET /api/quote-profiles":                                                         "quotes.read",
	"GET /api/quote-profiles/assets/{assetId}":                                        "quotes.read",
	"GET /api/quote-profiles/{profileId}":                                             "quotes.read",
	"GET /api/quotes":                                                                 "quotes.read",
	"GET /api/quotes/acceptances":                                                     "quotes.read",
	"GET /api/quotes/readiness":                                                       "quotes.read",
	"GET /api/quotes/settings":                                                        "settings.manage",
	"GET /api/quotes/{quoteId}":                                                       "quotes.read|quotes.portal_read",
	"GET /api/quotes/{quoteId}/collaboration/stream":                                  "quotes.read",
	"GET /api/quotes/{quoteId}/draft":                                                 "quotes.read",
	"GET /api/quotes/{quoteId}/presence":                                              "quotes.read",
	"GET /api/quotes/{quoteId}/versions":                                              "quotes.read",
	"GET /api/quotes/{quoteId}/versions/{version}":                                    "quotes.read|quotes.portal_read",
	"GET /api/quotes/{quoteId}/versions/{version}/confirmation":                       "quotes.read",
	"GET /api/quotes/{quoteId}/versions/{version}/confirmation/receipt":               "quotes.read",
	"GET /api/quotes/{quoteId}/versions/{version}/export":                             "quotes.read|quotes.portal_read",
	"GET /api/quotes/{quoteId}/versions/{version}/public-link":                        "quotes.manage",
	"GET /api/relations":                                                              "relations.read",
	"GET /api/releases":                                                               "releases.read",
	"GET /api/releases/{version}":                                                     "releases.read",
	"GET /api/roles":                                                                  "roles.read",
	"GET /api/runs":                                                                   "run.read",
	"GET /api/runs/queued":                                                            "run.read",
	"GET /api/runs/{runId}":                                                           "run.read",
	"GET /api/search":                                                                 "search.read",
	// Readers, or the routed plugin agent holding that handoff's operation scope,
	// can inspect attempt, supersession and current authority on the existing route.
	"GET /api/stage-handoffs/{handoffId}":                                             "stage_handoffs.read|stage.prepare|stage.deploy|stage.verify|stage.apply",
	"GET /api/tickets/graph":                                                          "nodes.read",
	"GET /api/time-entries":                                                           "hours.read",
	"GET /api/time-periods":                                                           "hours.read",
	"GET /api/time-periods/{periodId}":                                                "hours.read",
	"GET /api/version":                                                                "public",
	"GET /api/views":                                                                  "views.read",
	"GET /api/views/{viewId}":                                                         "views.read",
	"GET /api/work-orders":                                                            "work_orders.read",
	"GET /api/work-orders/{workOrderId}":                                              "work_orders.read",
	"PATCH /api/agent-accounts/{accountId}":                                           "account.manage",
	"PATCH /api/attachments/{id}":                                                     "attachments.write",
	"PATCH /api/crm/contacts/{contactId}":                                             "crm.write",
	"PATCH /api/crm/organisations/{organisationId}":                                   "crm.write",
	"PATCH /api/crm/organisations/{organisationId}/visibility":                        "crm.write",
	"PATCH /api/kinds/{kindId}":                                                       "kinds.manage",
	"PATCH /api/knowledge/{id}":                                                       "knowledge.write",
	"PATCH /api/me/profile":                                                           "profile.write|profile.portal_write",
	"PATCH /api/nodes/{nodeId}":                                                       "nodes.write",
	"PATCH /api/nodes/{nodeId}/comments/{commentId}":                                  "comments.write",
	"PATCH /api/project-groups/{groupId}":                                             "project_groups.write",
	"PATCH /api/projects/{projectId}/harness-sessions/{sessionId}/binding":            "harness.write",
	"PATCH /api/quote-profiles/{profileId}":                                           "quotes.write",
	"PATCH /api/quotes/settings":                                                      "settings.manage",
	"PATCH /api/quotes/{quoteId}/draft":                                               "quotes.write",
	"PATCH /api/quotes/{quoteId}/presence/{sessionId}":                                "quotes.write",
	"PATCH /api/quotes/{quoteId}/visibility":                                          "quotes.write",
	"PATCH /api/roles/{id}":                                                           "roles.manage",
	"PATCH /api/tags/{tagId}":                                                         "tags.write",
	"PATCH /api/time-entries/{id}":                                                    "hours.write",
	"PATCH /api/views/{viewId}":                                                       "views.write",
	"PATCH /api/work-orders/{workOrderId}":                                            "work_orders.write",
	"POST /api/agent-accounts":                                                        "account.manage",
	"POST /api/agent-accounts/route":                                                  "account.route",
	"POST /api/agent-accounts/{accountId}/probe":                                      "account.probe",
	"POST /api/agent-accounts/{accountId}/windows":                                    "account.manage",
	"POST /api/agent-keys":                                                            "keys.manage",
	"POST /api/members/invites":                                                       "members.manage",
	"POST /api/members/{principal_id}/aliases":                                        "members.manage",
	"POST /api/members/{principal_id}/deactivate":                                     "members.manage",
	"POST /api/members/{principal_id}/reactivate":                                     "members.manage",
	"POST /api/approvals":                                                             "approvals.request",
	"POST /api/approvals/{approvalId}/decision":                                       "approvals.decide",
	"POST /api/approvals/{approvalId}/revoke":                                         "approvals.revoke",
	"POST /api/auth/dev-login":                                                        "public",
	"POST /api/auth/logout":                                                           "public",
	"POST /api/cost-units/{costUnitId}/rates":                                         "cost_units.manage",
	"POST /api/crm/contacts/{contactId}/principals":                                   "crm.manage",
	"POST /api/crm/organisations":                                                     "crm.write",
	"POST /api/crm/organisations/{organisationId}/contacts":                           "crm.write",
	"POST /api/crm/organisations/{organisationId}/note-ai/generate":                   "crm.manage",
	"POST /api/crm/organisations/{organisationId}/note-rewrite":                       "crm.manage",
	"POST /api/crm/organisations/{organisationId}/note-rewrite/{draftId}/apply":       "crm.manage",
	"POST /api/crm/organisations/{organisationId}/number/reformat":                    "crm.write",
	"POST /api/crm/organisations/{organisationId}/primary-contact":                    "crm.write",
	"POST /api/crm/organisations/{organisationId}/sync":                               "crm.write",
	"POST /api/crm/providers/{providerId}/import":                                     "crm.manage",
	"POST /api/events/{eventId}/undo":                                                 "events.undo",
	"POST /api/inbox/messages":                                                        "inbox.send",
	"POST /api/inbox/messages/{messageId}/ack":                                        "inbox.send",
	"POST /api/inbox/targets":                                                         "inbox.send|inbox.manage",
	"POST /api/kinds":                                                                 "kinds.manage",
	"POST /api/knowledge":                                                             "knowledge.write",
	"POST /api/me/avatar":                                                             "profile.write|profile.portal_write",
	"POST /api/models":                                                                "models.manage",
	"POST /api/nodes":                                                                 "nodes.write",
	"POST /api/nodes/bulk":                                                            "nodes.write",
	"POST /api/nodes/{nodeId}/attachments":                                            "attachments.write",
	"POST /api/nodes/{nodeId}/comments":                                               "comments.write",
	"POST /api/nodes/{nodeId}/move":                                                   "nodes.move",
	"POST /api/nodes/{nodeId}/project-move":                                           "nodes.move",
	"POST /api/project-groups":                                                        "project_groups.write",
	"POST /api/project-groups/assign":                                                 "project_groups.write",
	"POST /api/projects/{projectId}/baseline-batches/batches/{batchId}/built-receipt": "stage.verify",
	"POST /api/projects/{projectId}/harness-sessions":                                 "harness.write",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/complete-delivery":   "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/controls/interrupt":  "harness.control",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/controls/stop":       "harness.control",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/controls/{controlId}/complete": "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/drain":                         "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/heartbeat":                     "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/stop":                          "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/yield":                         "harness.worker",
	"POST /api/projects/{projectId}/intake/drafts":                                              "intake.write",
	"POST /api/projects/{projectId}/intake/drafts/{draftId}/accept":                             "intake.decide",
	"POST /api/projects/{projectId}/intake/sources":                                             "intake.write",
	"POST /api/projects/{projectId}/intake/transcript-turns":                                    "intake.write",
	"POST /api/projects/{projectId}/journey/actions":                                            "journey.act",
	"POST /api/projects/{projectId}/message-targets":                                            "inbox.manage",
	"POST /api/projects/{projectId}/messages":                                                   "inbox.send",
	"POST /api/projects/{projectId}/messages/delivery-claim":                                    "inbox.send",
	"POST /api/projects/{projectId}/messages/delivery-complete":                                 "inbox.send",
	"POST /api/projects/{projectId}/messages/delivery-unavailable":                              "inbox.send",
	"POST /api/projects/{projectId}/messages/{messageId}/ack":                                   "inbox.send",
	"POST /api/projects/{projectId}/messages/{messageId}/resolution":                            "inbox.manage",
	"POST /api/projects/{projectId}/releases/{releaseId}/tickets":                               "releases.write",
	"POST /api/projects/{projectId}/requirements":                                               "requirements.write",
	"POST /api/projects/{projectId}/requirements/agree":                                         "requirements.agree",
	"POST /api/public/quotes/{publicTenant}/{token}/accept":                                     "public",
	"POST /api/quote-profiles":                                                                  "quotes.write",
	"POST /api/quote-profiles/assets":                                                           "quotes.write",
	"POST /api/quote-profiles/{profileId}/undo":                                                 "quotes.write",
	"POST /api/quotes":                                                 "quotes.write",
	"POST /api/quotes/{quoteId}/draft/branch":                          "quotes.write",
	"POST /api/quotes/{quoteId}/duplicate":                             "quotes.write",
	"POST /api/quotes/{quoteId}/finalize":                              "quotes.write",
	"POST /api/quotes/{quoteId}/presence":                              "quotes.write",
	"POST /api/quotes/{quoteId}/versions":                              "quotes.write",
	"POST /api/quotes/{quoteId}/versions/{version}/accept":             "quotes.accept|quotes.portal_accept",
	"POST /api/quotes/{quoteId}/versions/{version}/confirmation/retry": "quotes.manage",
	"POST /api/quotes/{quoteId}/versions/{version}/issue":              "quotes.issue",
	"POST /api/quotes/{quoteId}/versions/{version}/public-link":        "quotes.manage",
	"POST /api/quotes/{quoteId}/versions/{version}/public-link/revoke": "quotes.manage",
	"POST /api/relations":                                              "relations.write",
	"POST /api/roles":                                                  "roles.manage",
	"POST /api/runs/{runId}/claim":                                     "run.claim",
	"POST /api/runs/{runId}/telemetry":                                 "run.telemetry",
	"POST /api/stage-handoffs":                                         "stage_handoffs.write",
	"POST /api/stage-handoffs/{handoffId}/classic-batch-alias":         "stage_handoffs.decide",
	"POST /api/stage-handoffs/{handoffId}/evidence":                    "stage_handoffs.write|stage.prepare|stage.deploy|stage.verify|stage.apply",
	"POST /api/stage-handoffs/{handoffId}/launch/admit":                "stage.deploy",
	"POST /api/stage-handoffs/{handoffId}/launch/consume":              "stage.deploy",
	"POST /api/stage-handoffs/{handoffId}/result":                      "stage_handoffs.decide|stage.prepare|stage.deploy|stage.verify|stage.apply",
	"POST /api/time-entries":                                           "hours.write",
	"POST /api/time-periods":                                           "hours.write",
	"POST /api/time-periods/{periodId}/approve":                        "hours.approve",
	"POST /api/views":                                                  "views.write",
	"POST /api/views/{viewId}/restore":                                 "views.write",
	"POST /api/work-orders":                                            "work_orders.write",
	"POST /api/work-orders/{workOrderId}/criteria/{criterionId}/check": "work_orders.write",
	"POST /api/work-orders/{workOrderId}/evidence":                     "work_orders.write",
	"POST /api/work-orders/{workOrderId}/runs":                         "run.create", // Account choice only constrains routing; reservation/claim retain their scopes.
	"PUT /api/crm/documents/{attachmentId}/metadata":                   "crm.write",
	"PUT /api/crm/projects/{projectId}/cooperation":                    "crm.write",
	"PUT /api/crm/projects/{projectId}/customer":                       "crm.write",
	"PUT /api/crm/providers/{providerId}/config":                       "crm.manage",
	"PUT /api/members/{principal_id}/workspace-role":                   "members.manage",
	"PUT /api/models/routes":                                           "models.manage",
	"PUT /api/plugins/{pluginId}/installation":                         "plugins.manage",
	"PUT /api/preferences/{key}":                                       "views.write",
	"PUT /api/projects/{projectId}/journey/profile":                    "journey.act",
	"PUT /api/projects/{projectId}/releases/{releaseId}/plan":          "releases.write",
	"PUT /api/quotes/{quoteId}/profile":                                "quotes.write",
}

func PermissionForPattern(pattern string) (string, bool) {
	permission, ok := RoutePermissions[pattern]
	return permission, ok
}

// RequirePattern denies missing declarations. A public declaration leaves the
// route's own capability or login checks in place. Quote portal declarations
// allow either staff or customer authority; the handler checks ownership.
func RequirePattern(ctx context.Context, pattern string, scope Scope) error {
	declaration, ok := PermissionForPattern(pattern)
	if !ok {
		return ErrForbidden
	}
	if declaration == PublicRoute {
		return nil
	}
	for _, permission := range strings.Split(declaration, "|") {
		err := Require(ctx, permission, scope)
		if err == nil {
			return nil
		}
		if !errors.Is(err, ErrForbidden) {
			return err
		}
	}
	return ErrForbidden
}
