// SPDX-License-Identifier: AGPL-3.0-only

package authz

// Route and scope declarations for modelregistry.
func init() {
	registerRoutes("modelregistry", map[string]string{
		"DELETE /api/model-preferences/levels/{level}":               "models.read|model_prefs.manage",
		"DELETE /api/model-preferences/levels/{level}/rows/{kindId}": "models.read|model_prefs.manage",
		"DELETE /api/model-preferences/orders/{column}/{situation}":  "models.read|model_prefs.manage",
		"DELETE /api/models/{id}/retire":                             "models.manage",
		"DELETE /api/projects/{projectId}/lead-settings":             "model_prefs.manage",
		"DELETE /api/settings/lead-policy":                           "model_prefs.manage",
		"DELETE /api/work-kinds/{kindId}":                            "model_prefs.manage",
		"GET /api/model-preferences":                                 "models.read",
		"GET /api/model-preferences/board":                           "models.read",
		"GET /api/model-preferences/coverage":                        "models.read",
		"GET /api/model-preferences/evidence":                        "models.read",
		"GET /api/model-preferences/simple":                          "models.read",
		"GET /api/model-preferences/situations":                      "models.read",
		"GET /api/model-rules":                                       "models.read",
		"GET /api/models":                                            "models.read",
		"GET /api/models/lines/{harness}/{model}/usage":              "models.read",
		"GET /api/models/refresh":                                    "models.read",
		"GET /api/models/resolve":                                    "models.read",
		"GET /api/models/routes":                                     "models.read",
		"GET /api/projects/{projectId}/lead-settings":                "nodes.read",
		"GET /api/settings/lead-policy":                              "model_prefs.manage",
		"GET /api/work-kinds":                                        "models.read",
		"PATCH /api/work-kinds/{kindId}":                             "model_prefs.manage",
		"POST /api/model-preferences/tray/{line}/dismiss":            "models.read|model_prefs.manage",
		"POST /api/models":                                           "models.manage",
		"POST /api/models/proposals/accept":                          "models.manage",
		"POST /api/models/refresh":                                   "models.refresh",
		"POST /api/models/reports":                                   "models.report",
		"POST /api/models/{id}/retire":                               "models.manage",
		"POST /api/work-kinds":                                       "model_prefs.manage",
		"POST /api/work-kinds/{kindId}/restore":                      "model_prefs.manage",
		// Level-specific, person-only authority is rechecked under the mutation fence.
		"PUT /api/model-preferences/levels/{level}":                       "models.read|model_prefs.manage",
		"PUT /api/model-preferences/levels/{level}/rows/{kindId}":         "models.read|model_prefs.manage",
		"PUT /api/model-preferences/orders/{column}/{situation}":          "models.read|model_prefs.manage",
		"PUT /api/model-preferences/orders/{column}/{situation}/thinking": "models.read|model_prefs.manage",
		"PUT /api/model-preferences/profile":                              "models.read|model_prefs.manage",
		"PUT /api/model-preferences/situations":                           "model_prefs.manage",
		"PUT /api/model-rules/{scope}/{column}":                           "model_prefs.manage",
		"PUT /api/models/lines/{harness}/{model}":                         "models.manage",
		"PUT /api/models/refresh/credentials/{accountId}":                 "models.manage",
		"PUT /api/models/refresh/settings":                                "models.manage",
		"PUT /api/models/routes":                                          "models.manage",
		"PUT /api/projects/{projectId}/lead-settings":                     "model_prefs.manage",
		"PUT /api/settings/lead-policy":                                   "model_prefs.manage",
		"PUT /api/work-kinds/order":                                       "model_prefs.manage",
	})
	registerDeclarations("modelregistry", "project_decided", ProjectDecidedRoutes, map[string]bool{
		"DELETE /api/model-preferences/levels/{level}":               true,
		"DELETE /api/model-preferences/levels/{level}/rows/{kindId}": true,
		"DELETE /api/work-kinds/{kindId}":                            true,
		"PATCH /api/work-kinds/{kindId}":                             true,
		"POST /api/work-kinds":                                       true,
		"POST /api/work-kinds/{kindId}/restore":                      true,
		"PUT /api/model-preferences/levels/{level}":                  true,
		"PUT /api/model-preferences/levels/{level}/rows/{kindId}":    true,
		"PUT /api/model-rules/{scope}/{column}":                      true,
		"PUT /api/work-kinds/order":                                  true,
	})
}
