// SPDX-License-Identifier: AGPL-3.0-only

package authz

import (
	"context"
	"errors"
	"strings"

	"github.com/inspr-at/paimos/internal/tenant"
)

// PublicRoute marks a matched route that is public. Unknown routes have no
// declaration and must be denied by the authorization boundary. Session
// refresh uses the same marker, so it cannot disagree with authorization.
const PublicRoute = "public"

// AuthenticatedRoute requires a principal resolved by authentication, without
// a role or key scope. It is reserved for the caller's own identity endpoint.
const AuthenticatedRoute = "authenticated"

// RoutePermissions declares the permission for each registered API pattern.
// Customer quote routes accept one of two permissions; the quote handler also
// verifies the recipient binding. Authentication and public capability routes
// remain explicit entries so route coverage can detect new unreviewed paths.
var RoutePermissions = map[string]string{
	// Lead handlers retain their actor/owner checks inside the final transaction.
	"GET /api/projects/{projectId}/lead":                            "harness.read",
	"POST /api/projects/{projectId}/lead":                           "harness.control",
	"POST /api/projects/{projectId}/lead/yield":                     "harness.worker",
	"POST /api/projects/{projectId}/lead/claim":                     "harness.worker",
	"POST /api/projects/{projectId}/lead/pause":                     "harness.control|harness.worker",
	"GET /api/projects/{projectId}/lead/usage":                      "harness.read",
	"POST /api/projects/{projectId}/chat-roles":                     "chat.bind",
	"POST /api/projects/{projectId}/chat-threads/resolve":           "chat.read",
	"GET /api/chat-threads/{id}":                                    "chat.read",
	"POST /api/chat-threads/{id}/binding":                           "chat.bind",
	"POST /api/chat-deliveries/binding/resolve":                     "chat.receive",
	"GET /api/me/phone-approvals":                                   "profile.read",
	"PUT /api/me/phone-approvals/settings":                          "profile.write",
	"POST /api/me/phone-approvals/passkeys/options":                 "profile.write",
	"POST /api/me/phone-approvals/passkeys":                         "profile.write",
	"DELETE /api/me/phone-approvals/passkeys/{credentialId}":        "profile.write",
	"POST /api/me/phone-approvals/subscriptions":                    "profile.write",
	"DELETE /api/me/phone-approvals/subscriptions/{subscriptionId}": "profile.write",
	"GET /api/phone-approvals/{kind}/{requestId}":                   "profile.read",
	"POST /api/phone-approvals/{kind}/{requestId}/options":          "profile.write",
	"POST /api/phone-approvals/{kind}/{requestId}/decision":         "profile.write",

	"GET /api/features":                              "nodes.read",
	"GET /api/settings/features":                     "settings.manage",
	"PUT /api/settings/features/{key}":               "settings.manage",
	"GET /api/agentd/step-ups/{challenge_id}":        "harness.worker",
	"PUT /api/agent-keys/{id}/owner-workstation":     "keys.manage",
	"GET /api/model-preferences":                     "models.read",
	"GET /api/settings/lead-policy":                  "model_prefs.manage",
	"PUT /api/settings/lead-policy":                  "model_prefs.manage",
	"DELETE /api/settings/lead-policy":               "model_prefs.manage",
	"GET /api/projects/{projectId}/lead-settings":    "nodes.read",
	"PUT /api/projects/{projectId}/lead-settings":    "model_prefs.manage",
	"DELETE /api/projects/{projectId}/lead-settings": "model_prefs.manage",
	// Theme handlers decide person ownership or workspace settings authority
	// again inside the final fenced mutation transaction.
	"GET /api/themes":                      "profile.read|profile.portal_read",
	"GET /api/themes/{themeId}":            "profile.read|profile.portal_read",
	"GET /api/me/theme":                    "profile.read|profile.portal_read",
	"POST /api/themes":                     "profile.write|profile.portal_write|settings.manage",
	"PATCH /api/themes/{themeId}":          "profile.write|profile.portal_write|settings.manage",
	"DELETE /api/themes/{themeId}":         "profile.write|profile.portal_write|settings.manage",
	"POST /api/themes/{themeId}/duplicate": "profile.write|profile.portal_write|settings.manage",
	"PUT /api/me/theme":                    "profile.write|profile.portal_write",

	"GET /api/nodes/{nodeId}/work-lifecycle":                      "nodes.read",
	"POST /api/nodes/{nodeId}/work-lifecycle":                     "nodes.write",
	"POST /api/nodes/{nodeId}/work-lifecycle/{actionId}/continue": "nodes.write",
	"DELETE /api/nodes/{nodeId}/work-lifecycle/{actionId}":        "nodes.write",

	"GET /api/nodes/{nodeId}/benefit-generation":         "nodes.read",
	"POST /api/nodes/{nodeId}/benefit-generation/retry":  "nodes.write",
	"POST /api/agent-keys/{id}/trim-proposals":           "approvals.request",
	"GET /api/key-trim-proposals":                        "keys.manage",
	"POST /api/key-trim-proposals/{proposalId}/decision": "keys.manage",
	"POST /api/key-trim-proposals/{proposalId}/restore":  "keys.manage",
	// Level-specific, person-only authority is rechecked under the mutation fence.
	"PUT /api/model-preferences/levels/{level}":                  "models.read|model_prefs.manage",
	"DELETE /api/model-preferences/levels/{level}":               "models.read|model_prefs.manage",
	"PUT /api/model-preferences/levels/{level}/rows/{kindId}":    "models.read|model_prefs.manage",
	"DELETE /api/model-preferences/levels/{level}/rows/{kindId}": "models.read|model_prefs.manage",
	"GET /api/work-kinds":                                        "models.read",
	"POST /api/work-kinds":                                       "model_prefs.manage",
	"PATCH /api/work-kinds/{kindId}":                             "model_prefs.manage",
	"DELETE /api/work-kinds/{kindId}":                            "model_prefs.manage",
	"POST /api/work-kinds/{kindId}/restore":                      "model_prefs.manage",
	"POST /api/models/{id}/retire":                               "models.manage",
	"DELETE /api/models/{id}/retire":                             "models.manage",

	// AEON-619: additive product-scoped routes.
	"GET /api/portal/products/{productId}/pace":                                          "settings.manage",
	"PUT /api/portal/products/{productId}/pace":                                          "settings.manage",
	"GET /api/portal/products/{productId}/market":                                        "settings.manage",
	"GET /api/portal/products/{productId}/settings":                                      "settings.manage",
	"PUT /api/portal/products/{productId}/settings":                                      "settings.manage",
	"GET /api/public/portal/{tenantSlug}/participation":                                  "public",
	"GET /api/public/portal/{tenantSlug}/products/{productSlug}":                         "public",
	"GET /api/public/portal/{tenantSlug}/products/{productSlug}/catalog":                 "public",
	"GET /api/public/portal/{tenantSlug}/products/{productSlug}/wishes":                  "public",
	"GET /api/public/portal/{tenantSlug}/products/{productSlug}/comparison":              "public",
	"GET /api/public/portal/{tenantSlug}/products/{productSlug}/pace":                    "public",
	"GET /api/public/portal/{tenantSlug}/products/{productSlug}/participation":           "public",
	"GET /api/public/portal/{tenantSlug}/products/{productSlug}/catalog.json":            "public",
	"GET /api/public/portal/{tenantSlug}/products/{productSlug}/llms.txt":                "public",
	"GET /api/public/portal/{tenantSlug}/products/{productSlug}/releases":                "public",
	"GET /api/public/portal/{tenantSlug}/products/{productSlug}/roadmap":                 "public",
	"GET /api/public/portal/{tenantSlug}/products/{productSlug}/roadmap.json":            "public",
	"POST /api/public/portal/{tenantSlug}/products/{productSlug}/wishes":                 "public",
	"POST /api/public/portal/{tenantSlug}/products/{productSlug}/wishes/{wishKey}/votes": "public",
	"POST /api/public/portal/{tenantSlug}/products/{productSlug}/corrections":            "public",
	"GET /portal/{tenantSlug}/products/{productSlug}":                                    "public",
	"GET /portal/{tenantSlug}/products/{productSlug}/roadmap":                            "public",
	"GET /portal/{tenantSlug}/products/{productSlug}/llms.txt":                           "public",
	"GET /portal/{tenantSlug}/products/{productSlug}/catalog.json":                       "public",
	"GET /portal/{tenantSlug}/products/{productSlug}/roadmap.json":                       "public",

	"GET /api/agents/plan": "agents.plan.read",
	// Read-only people enter with nodes.read. Recurrence handlers still require
	// recurrences.manage for agents, including their explicit role and key scope.
	"GET /api/recurrences":                                                      "nodes.read|recurrences.manage",
	"POST /api/recurrences":                                                     "recurrences.manage",
	"POST /api/recurrences/preview":                                             "recurrences.manage",
	"GET /api/recurrences/{recurrenceId}":                                       "nodes.read|recurrences.manage",
	"PUT /api/recurrences/{recurrenceId}":                                       "recurrences.manage",
	"DELETE /api/recurrences/{recurrenceId}":                                    "recurrences.manage",
	"POST /api/recurrences/{recurrenceId}/pause":                                "recurrences.manage",
	"POST /api/recurrences/{recurrenceId}/resume":                               "recurrences.manage",
	"POST /api/recurrences/{recurrenceId}/run-now":                              "recurrences.manage",
	"GET /api/recurrences/{recurrenceId}/preview":                               "nodes.read|recurrences.manage",
	"GET /api/recurrences/{recurrenceId}/history":                               "nodes.read|recurrences.manage",
	"GET /api/recurrences/{recurrenceId}/releases":                              "nodes.read|recurrences.manage",
	"POST /api/projects/{projectId}/questions":                                  "questions.ask",
	"GET /api/projects/{projectId}/questions":                                   "questions.read",
	"GET /api/questions/{questionId}":                                           "questions.read",
	"GET /api/questions/{questionId}/status":                                    "questions.read",
	"POST /api/questions/{questionId}/decision":                                 "questions.decide",
	"GET /api/decision-desk":                                                    "questions.read",
	"GET /api/decision-desk/projection":                                         "profile.read",
	"GET /api/models/refresh":                                                   "models.read",
	"POST /api/models/refresh":                                                  "models.refresh",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/model-reports": "harness.worker",
	"POST /api/models/proposals/accept":                                         "models.manage",
	"POST /api/models/reports":                                                  "models.report",
	"PUT /api/models/refresh/settings":                                          "models.manage",
	"PUT /api/models/refresh/credentials/{accountId}":                           "models.manage",

	"GET /api/journey/next-actions":                                           "journey.read",
	"POST /api/agent-pairing/account-link":                                    "account.probe",
	"POST /api/agent-pairing/account-link/lookup":                             "profile.write",
	"POST /api/agent-pairing/account-link/{requestId}/approve":                "profile.write",
	"GET /api/agent-pairing/account-links":                                    "profile.write",
	"POST /api/agent-pairing/account-links/{accountId}/unlink":                "profile.write",
	"GET /api/queue/{nodeId}/readiness":                                       "nodes.read",
	"POST /api/queue/{nodeId}/estimate":                                       "nodes.read",
	"POST /api/queue/{nodeId}/undo":                                           "nodes.read", // Handler rechecks queue write permission and receipt ownership in the mutation transaction.
	"GET /api/queue":                                                          "nodes.read",
	"POST /api/queue":                                                         "nodes.read",
	"POST /api/queue/{nodeId}/snapshots":                                      "nodes.read",
	"GET /api/queue-snapshots/{snapshotId}":                                   "nodes.read",
	"POST /api/queue-snapshots/{snapshotId}/apply":                            "nodes.read",
	"DELETE /api/queue-snapshots/{snapshotId}":                                "nodes.read",
	"DELETE /api/queue/{nodeId}":                                              "nodes.read",
	"POST /api/queue/{nodeId}/move":                                           "nodes.read",
	"POST /api/queue/reset":                                                   "nodes.read",
	"POST /api/queue/next":                                                    "nodes.read",
	"GET /api/plugins/aithema/settings":                                       "plugins.manage",
	"PUT /api/plugins/aithema/settings":                                       "plugins.manage",
	"POST /api/projects/{projectId}/aithema/sessions":                         "intake.write",
	"POST /api/projects/{projectId}/aithema/sessions/{sid}/tokens":            "intake.write",
	"POST /api/projects/{projectId}/aithema/sessions/{sid}/control":           "intake.write",
	"POST /api/projects/{projectId}/aithema/sessions/{sid}/host-event":        "intake.write",
	"POST /api/aithema/deprovision":                                           "plugins.manage",
	"GET /api/aithema/callbacks/{callbackId}":                                 "plugins.manage",
	"POST /api/projects/{projectId}/aithema/sessions/{sid}/proxy/{operation}": "intake.write",
	"GET /api/projects/{projectId}/aithema/sessions/{sid}/proxy/{operation}":  "intake.write",

	// Aithema delegates authentication to the journal module: a public outer
	// declaration never bypasses its JWT, exact capability or transaction fence.
	"POST /api/aithema/journal/sessions/{sid}/records":   "public",
	"POST /api/aithema/journal/sessions/{sid}/snapshots": "public",
	"POST /api/aithema/journal/sessions/{sid}/op.result": "public",
	"GET /api/aithema/journal/sessions/{sid}/records":    "public",
	"GET /api/aithema/journal/sessions/{sid}/cursor":     "public",
	"GET /api/aithema/journal/sessions/{sid}/authority":  "public",
	"POST /api/aithema/ledger/sessions/{sid}/admit":      "public",
	"POST /api/aithema/ledger/sessions/{sid}/claim":      "public",
	"POST /api/aithema/ledger/sessions/{sid}/settle":     "public",
	"POST /api/aithema/ledger/sessions/{sid}/recover":    "public",
	"GET /api/aithema/ledger/sessions/{sid}/holds":       "public",

	"GET /api/nodes/{nodeId}/reviews":                                                   "work_orders.read",
	"POST /api/nodes/{nodeId}/reviews":                                                  "work_orders.write",
	"DELETE /api/agent-accounts/{accountId}/{resource}":                                 "account.manage",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/reparent":              "harness.write",
	"GET /api/rules/doctrine/proposals":                                                 "rules.read",
	"GET /api/rules/doctrine/analysis":                                                  "rules.read",
	"POST /api/rules/doctrine/proposals":                                                "rules.write",
	"POST /api/rules/doctrine/proposals/{proposalId}/refresh":                           "rules.write",
	"POST /api/rules/doctrine/proposals/{proposalId}/approve":                           "rules.publish",
	"POST /api/rules/doctrine/proposals/{proposalId}/pins":                              "settings.manage",
	"GET /api/rules/doctrine/inbox":                                                     "rules.read",
	"GET /api/rules/doctrine/inbox/summary":                                             "rules.read",
	"POST /api/rules/doctrine/inbox":                                                    "rules.write",
	"POST /api/rules/doctrine/inbox/{proposalId}/pull-request":                          "rules.write",
	"POST /api/rules/doctrine/inbox/{proposalId}/dismiss":                               "rules.write",
	"POST /api/rules/doctrine/inbox/{proposalId}/notified":                              "rules.read",
	"GET /api/me/security/session-watching":                                             "profile.read",
	"PUT /api/me/security/session-watching":                                             "profile.write",
	"POST /api/agent-pairing/attach":                                                    "harness.worker",
	"POST /api/agent-pairing/attach/lookup":                                             "account.manage",
	"GET /api/agent-pairing/attach/pending":                                             "account.manage",
	"POST /api/agent-pairing/attach/{requestId}/approve":                                "account.manage",
	"POST /api/agent-pairing/attach/{requestId}/revoke":                                 "account.manage",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/watch":                  "harness.watch",
	"GET /api/rules/layers":                                                             "rules.read",
	"POST /api/rules/layers":                                                            "rules.write",
	"GET /api/rules/sets":                                                               "rules.read",
	"POST /api/rules/sets":                                                              "rules.write",
	"GET /api/rules/sets/{setId}":                                                       "rules.read",
	"PUT /api/rules/sets/{setId}/draft":                                                 "rules.write",
	"POST /api/rules/sets/{setId}/publish":                                              "rules.publish",
	"POST /api/rules/sets/{setId}/restore":                                              "rules.publish",
	"GET /api/rules/sets/{setId}/versions":                                              "rules.read",
	"GET /api/rules/sets/{setId}/versions/{version}":                                    "rules.read",
	"GET /api/rules/merged":                                                             "rules.read",
	"GET /api/rules/channels":                                                           "rules.read",
	"GET /api/rules/comparisons":                                                        "rules.read",
	"POST /api/rules/comparisons":                                                       "rules.write",
	"GET /api/rules/explained":                                                          "rules.read",
	"PUT /api/rules/sets/{setId}/tldr":                                                  "rules.write",
	"GET /api/rules/budget":                                                             "rules.read",
	"PUT /api/rules/budget":                                                             "settings.manage",
	"POST /api/rules/publish":                                                           "rules.publish",
	"GET /api/rules/doctrine":                                                           "rules.read",
	"POST /api/rules/doctrine/sources":                                                  "settings.manage",
	"PUT /api/rules/doctrine/sources/{sourceId}":                                        "settings.manage",
	"DELETE /api/rules/doctrine/sources/{sourceId}":                                     "settings.manage",
	"POST /api/rules/doctrine/sources/{sourceId}/index":                                 "settings.manage",
	"GET /api/agent-pairing/guide":                                                      "public",
	"POST /api/agent-pairing/device":                                                    "public",
	"POST /api/agent-pairing/redeem":                                                    "public",
	"POST /api/agent-pairing/reconcile":                                                 "public",
	"POST /api/agent-pairing/lookup":                                                    "account.manage",
	"POST /api/agent-pairing/requests/{requestId}/approve":                              "account.manage",
	"POST /api/agent-pairing/requests/{requestId}/deny":                                 "account.manage",
	"GET /api/agent-pairing/computers":                                                  "account.read",
	"GET /api/agent-pairing/computers/{computerId}":                                     "account.read",
	"POST /api/agent-pairing/computers/{computerId}/disconnect":                         "account.manage",
	"POST /api/agent-pairing/computers/{computerId}/enrollments/{accountId}/disconnect": "account.manage",
	"POST /api/agent-pairing/computers/{computerId}/enrollments/{accountId}/verify":     "account.manage",
	"POST /api/agent-pairing/computers/{computerId}/remove":                             "account.manage",
	"GET /api/agent-pairing/self":                                                       "run.claim",
	"POST /api/agent-pairing/self/disconnect":                                           "run.claim",

	"GET /api/agent-keys/{id}/scopes":                                        "keys.manage",
	"PATCH /api/agent-keys/{id}/scopes":                                      "keys.manage",
	"DELETE /api/agent-keys/{id}":                                            "keys.manage",
	"DELETE /api/members/invites/{id}":                                       "members.manage",
	"DELETE /api/members/{principal_id}/aliases/{from_principal_id}":         "members.manage",
	"DELETE /api/attachments/{id}":                                           "attachments.delete",
	"DELETE /api/crm/contacts/{contactId}":                                   "crm.write",
	"DELETE /api/crm/organisations/{organisationId}":                         "crm.write",
	"DELETE /api/inbox/targets/{targetId}":                                   "inbox.send|inbox.manage",
	"DELETE /api/kinds/{kindId}":                                             "kinds.manage",
	"DELETE /api/knowledge/{id}":                                             "knowledge.delete",
	"DELETE /api/me/avatar":                                                  "profile.write|profile.portal_write",
	"DELETE /api/nodes/{nodeId}":                                             "nodes.delete",
	"DELETE /api/nodes/{nodeId}/comments/{commentId}":                        "comments.delete",
	"DELETE /api/project-groups/{groupId}":                                   "project_groups.write",
	"DELETE /api/quote-profiles/{profileId}":                                 "quotes.write",
	"DELETE /api/quotes/{quoteId}":                                           "quotes.delete",
	"DELETE /api/quotes/{quoteId}/presence/{sessionId}":                      "quotes.delete",
	"DELETE /api/relations/{relationId}":                                     "relations.delete",
	"DELETE /api/roles/{id}":                                                 "roles.manage",
	"DELETE /api/tags/{tagId}":                                               "tags.manage",
	"DELETE /api/time-entries/{id}":                                          "hours.write",
	"DELETE /api/views/{viewId}":                                             "views.write",
	"GET /api/agent-accounts/readiness":                                      "account.read",
	"POST /api/agent-accounts/{accountId}/check":                             "account.manage",
	"PUT /api/agent-accounts/{accountId}/sharing":                            "account.manage",
	"GET /api/agent-accounts":                                                "account.read",
	"GET /api/agent-accounts/catalog":                                        "account.read",
	"PUT /api/agent-accounts/{accountId}/model":                              "account.manage",
	"PUT /api/agent-accounts/quota-pool":                                     "account.manage",
	"GET /api/agent-accounts/groups":                                         "account.read",
	"POST /api/agent-accounts/groups":                                        "account.manage",
	"PATCH /api/agent-accounts/groups/{id}":                                  "account.manage",
	"DELETE /api/agent-accounts/groups/{id}":                                 "account.manage",
	"GET /api/agent-accounts/pins":                                           "account.read",
	"PUT /api/agent-accounts/pins":                                           "run.create",
	"DELETE /api/agent-accounts/pins":                                        "run.create",
	"GET /api/agent-accounts/use":                                            "account.read|account.probe",
	"POST /api/agent-accounts/runs/{runId}/target":                           "run.create",
	"PUT /api/agent-accounts/{accountId}/metadata":                           "account.manage",
	"GET /api/agent-accounts/{accountId}/residency-evidence":                 "account.read",
	"PUT /api/agent-accounts/{accountId}/residency-evidence":                 "account.manage|account.probe", // Handler distinguishes owning person from bound host key.
	"PUT /api/agent-accounts/{accountId}/label":                              "account.manage",
	"PUT /api/agent-accounts/{accountId}/limit":                              "account.manage",
	"GET /api/agent-keys":                                                    "keys.read",
	"GET /api/approvals":                                                     "approvals.read",
	"GET /api/audit":                                                         "audit.read",
	"GET /api/attachments/{id}/content":                                      "attachments.read",
	"POST /api/attachments/{id}/preview":                                     "attachments.read",
	"GET /api/auth/callback":                                                 "public",
	"GET /api/auth/login":                                                    "public",
	"GET /api/authz/permissions":                                             "roles.read",
	"GET /api/business/principals":                                           "members.read",
	"GET /api/cost-units/{costUnitId}/rates":                                 "cost_units.read",
	"GET /api/crm/contacts/{contactId}":                                      "crm.read",
	"GET /api/crm/organisations":                                             "crm.read",
	"GET /api/crm/organisations/{organisationId}":                            "crm.read",
	"GET /api/crm/organisations/{organisationId}/contacts":                   "crm.read",
	"GET /api/crm/organisations/{organisationId}/note-ai":                    "crm.manage",
	"GET /api/crm/organisations/{organisationId}/related":                    "crm.read",
	"GET /api/crm/organisations/{organisationId}/sync-status":                "crm.read",
	"GET /api/crm/projects/{projectId}/cooperation":                          "crm.read",
	"GET /api/crm/providers":                                                 "crm.read",
	"GET /api/crm/providers/search":                                          "crm.read",
	"GET /api/events":                                                        "events.read",
	"GET /api/events/activity":                                               "events.read",
	"GET /api/events/stream":                                                 "events.read",
	"GET /api/from-classic":                                                  "nodes.read",
	"GET /api/harness-sessions":                                              "harness.read",
	"GET /api/me/agent-pause-settings":                                       "harness.read",
	"PUT /api/me/agent-pause-settings":                                       "harness.read",
	"GET /api/me/leaving-at":                                                 "harness.read",
	"PUT /api/me/leaving-at":                                                 "harness.control",
	"DELETE /api/me/leaving-at":                                              "harness.control",
	"POST /api/harness-sessions/pause":                                       "harness.control",
	"POST /api/harness-sessions/resume":                                      "harness.control",
	"GET /api/harness-sessions/live":                                         "nodes.read",
	"GET /api/harness-sessions/{sessionId}/delivery-rating":                  "nodes.read",
	"PUT /api/harness-sessions/{sessionId}/delivery-rating":                  "nodes.read",
	"DELETE /api/harness-sessions/{sessionId}/delivery-rating":               "nodes.read",
	"GET /api/usage/dashboard":                                               "harness.read",
	"GET /api/usage/model-estimates":                                         "harness.read",
	"GET /api/health":                                                        "public",
	"POST /api/reviews/github":                                               "public", // Authenticated by host-owned GitHub HMAC, never a tenant session.
	"GET /api/aithema/jwks":                                                  "public",
	"GET /api/ready":                                                         "public",
	"GET /api/imports":                                                       "imports.read",
	"GET /api/imports/{importId}":                                            "imports.read",
	"GET /api/inbox/messages":                                                "inbox.read",
	"GET /api/inbox/messages/{messageId}/receipt":                            "inbox.receipt",
	"GET /api/inbox/stream":                                                  "inbox.read",
	"GET /api/inbox/targets":                                                 "inbox.read",
	"GET /api/kinds":                                                         "nodes.read",
	"GET /api/status/help":                                                   "nodes.read", // Authenticated agents have a read-only exception in RequirePattern.
	"GET /api/kinds/{kindId}":                                                "nodes.read",
	"GET /api/knowledge":                                                     "knowledge.read",
	"GET /api/knowledge/graph":                                               "knowledge.read",
	"GET /api/knowledge/learnings":                                           "knowledge.read",
	"GET /api/knowledge/resolve":                                             "knowledge.read",
	"GET /api/knowledge/{id}":                                                "knowledge.read",
	"GET /api/me":                                                            AuthenticatedRoute,
	"GET /api/me/greeting":                                                   "profile.read|profile.portal_read",
	"GET /api/me/host-labels":                                                "harness.read",
	"PUT /api/me/host-labels":                                                "harness.read",
	"GET /api/me/permissions":                                                "authz.read",
	"GET /api/me/profile":                                                    "profile.read|profile.portal_read",
	"GET /api/members":                                                       "members.read",
	"GET /api/models":                                                        "models.read",
	"GET /api/models/resolve":                                                "models.read",
	"GET /api/node-keys/{key}":                                               "nodes.read",
	"GET /api/outcomes/measurement":                                          "outcome.read",
	"GET /api/nodes/{nodeId}/escalation":                                     "outcome.read",
	"GET /api/outcomes":                                                      "outcome.read",
	"GET /api/nodes":                                                         "nodes.read",
	"GET /api/nodes/lookup":                                                  "nodes.read",
	"GET /api/nodes/tree":                                                    "nodes.read",
	"GET /api/nodes/{nodeId}":                                                "nodes.read",
	"GET /api/nodes/{nodeId}/activity":                                       "events.read",
	"GET /api/nodes/{nodeId}/agent-work":                                     "nodes.read",
	"GET /api/nodes/{nodeId}/delivery-ratings":                               "nodes.read",
	"GET /api/nodes/{nodeId}/attachments":                                    "attachments.read",
	"GET /api/nodes/{nodeId}/time-totals":                                    "hours.read",
	"GET /api/people/{principalId}/avatar/{size}":                            "profile.read",
	"GET /api/plugins":                                                       "plugins.read",
	"GET /api/portal/settings":                                               "settings.manage",
	"GET /api/preferences/{key}":                                             "views.read",
	"GET /api/project-groups":                                                "project_groups.read",
	"GET /api/projects":                                                      "nodes.read",
	"GET /api/projects/{projectId}/harness-sessions":                         "harness.read",
	"GET /api/projects/{projectId}/harness-sessions/orchestrator":            "harness.read",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}":             "harness.read",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/lookup":      "harness.read",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/read-marker": "harness.read",
	"GET /api/inbox/message-status":                                          "inbox.receipt",
	"POST /api/agent-accounts/{accountId}/capacity/approve":                  "account.manage",
	"GET /api/agent-accounts/capacity/next":                                  "account.read|account.probe",
	"GET /api/agent-accounts/capacity":                                       "account.read",
	"GET /api/agent-accounts/{accountId}/readings":                           "account.read|account.probe", // Handler requires read for people, probe + ownership for agents.
	"POST /api/agent-accounts/{accountId}/readings":                          "account.probe",
	"PUT /api/agent-accounts/{accountId}/signals":                            "account.probe",
	"GET /api/agent-accounts/{accountId}/statusline":                         "account.probe",
	"PUT /api/agent-accounts/{accountId}/statusline":                         "account.manage",
	"POST /api/agent-accounts/{accountId}/quota-key":                         "account.probe",
	"POST /api/agent-accounts/capacity/preview":                              "account.read",
	"GET /api/agent-accounts/capacity/schedule":                              "account.read",
	"PUT /api/agent-accounts/capacity/schedule":                              "account.manage",
	"GET /api/inbox/feedback-recipient":                                      "inbox.send",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/controls/{controlId}":      "harness.read",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/recover-agent":             "harness.control",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/recover-agent":            "harness.control",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/recover-agent/{requestId}": "harness.read",
	"POST /api/harness-recoveries/claim":                                                   "harness.worker",
	"POST /api/harness-recoveries/{requestId}/complete":                                    "harness.worker",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/recovery":                  "harness.read",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/remove":                   "harness.read",
	"POST /api/projects/{projectId}/harness-sessions/remove-stale":                         "harness.read",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/archive":                  "harness.recover",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/controls/force-stop":      "harness.force_stop",
	"GET /api/projects/{projectId}/intake":                                                 "intake.read",
	"GET /api/projects/{projectId}/journey":                                                "journey.read",
	"GET /api/projects/{projectId}/members":                                                "members.read",
	"PUT /api/projects/{projectId}/members/{principal_id}":                                 "members.manage",
	"DELETE /api/projects/{projectId}/members/{principal_id}":                              "members.manage",
	"GET /api/projects/{projectId}/message-deliveries":                                     "inbox.manage",
	"GET /api/projects/{projectId}/message-targets":                                        "inbox.manage",
	"GET /api/projects/{projectId}/messages":                                               "inbox.manage",
	"GET /api/projects/{projectId}/messages/listen":                                        "inbox.read",
	"GET /api/projects/{projectId}/releases/{releaseId}/candidate-artifact":                "stage_handoffs.read",
	"PUT /api/projects/{projectId}/releases/{releaseId}/candidate-artifact":                "stage_handoffs.write",
	"GET /api/projects/{projectId}/releases/{releaseId}/note-snapshot":                     "releases.read",
	"GET /api/projects/{projectId}/releases/{releaseId}/walker":                            "releases.read",
	"GET /api/projects/{projectId}/release-memberships":                                    "releases.read",
	"GET /api/projects/{projectId}/releases/{releaseId}/ticket-options":                    "releases.read",
	"GET /api/projects/{projectId}/requirements":                                           "requirements.read",
	"GET /api/public/portal/{tenantSlug}":                                                  "public",
	"GET /api/public/portal/{tenantSlug}/catalog.json":                                     "public",
	"GET /api/public/portal/{tenantSlug}/llms.txt":                                         "public",
	"GET /api/public/portal/{tenantSlug}/releases":                                         "public",
	"GET /api/public/portal/{tenantSlug}/roadmap":                                          "public",
	"GET /api/public/portal/{tenantSlug}/roadmap.json":                                     "public",
	"GET /portal/{tenantSlug}":                                                             "public",
	"GET /portal/{tenantSlug}/catalog.json":                                                "public",
	"GET /portal/{tenantSlug}/llms.txt":                                                    "public",
	"GET /portal/{tenantSlug}/roadmap":                                                     "public",
	"GET /portal/{tenantSlug}/roadmap.json":                                                "public",
	"GET /api/public/quotes/{publicTenant}/{token}":                                        "public",
	"GET /api/public/quotes/{publicTenant}/{token}/pdf":                                    "public",
	"GET /api/quote-profiles":                                                              "quotes.read",
	"GET /api/quote-profiles/assets/{assetId}":                                             "quotes.read",
	"GET /api/quote-profiles/{profileId}":                                                  "quotes.read",
	"GET /api/quotes":                                                                      "quotes.read",
	"GET /api/quotes/acceptances":                                                          "quotes.read",
	"GET /api/quotes/readiness":                                                            "quotes.read",
	"GET /api/quotes/settings":                                                             "settings.manage",
	"GET /api/quotes/{quoteId}":                                                            "quotes.read|quotes.portal_read",
	"GET /api/quotes/{quoteId}/collaboration/stream":                                       "quotes.read",
	"GET /api/quotes/{quoteId}/draft":                                                      "quotes.read",
	"GET /api/quotes/{quoteId}/presence":                                                   "quotes.read",
	"GET /api/quotes/{quoteId}/versions":                                                   "quotes.read",
	"GET /api/quotes/{quoteId}/versions/{version}":                                         "quotes.read|quotes.portal_read",
	"GET /api/quotes/{quoteId}/versions/{version}/confirmation":                            "quotes.read",
	"GET /api/quotes/{quoteId}/versions/{version}/confirmation/receipt":                    "quotes.read",
	"GET /api/quotes/{quoteId}/versions/{version}/export":                                  "quotes.read|quotes.portal_read",
	"GET /api/quotes/{quoteId}/versions/{version}/public-link":                             "quotes.manage",
	"GET /api/relations":                                                                   "relations.read",
	"GET /api/releases":                                                                    "releases.read",
	"GET /api/releases/pending":                                                            "releases.read",
	"GET /api/releases/{version}":                                                          "releases.read",
	"PUT /api/releases/{version}/presentation":                                             "releases.deploy",
	"DELETE /api/releases/{version}/presentation":                                          "releases.deploy",
	"GET /api/roles":                "roles.read",
	"GET /api/runs":                 "run.read",
	"GET /api/runs/queued":          "run.read",
	"GET /api/runs/{runId}":         "run.read",
	"GET /api/runs/{runId}/handoff": "run.read",
	"GET /api/search":               "search.read",
	// Readers, or the routed plugin agent holding that handoff's operation scope,
	// can inspect attempt, supersession and current authority on the existing route.
	"GET /api/stage-handoffs/{handoffId}":                                                       "stage_handoffs.read|stage.prepare|stage.deploy|stage.verify|stage.apply",
	"GET /api/tickets/graph":                                                                    "nodes.read",
	"GET /api/time-entries":                                                                     "hours.read",
	"GET /api/time-periods":                                                                     "hours.read",
	"GET /api/time-periods/{periodId}":                                                          "hours.read",
	"GET /api/version":                                                                          "public",
	"GET /api/views":                                                                            "views.read",
	"GET /api/views/{viewId}":                                                                   "views.read",
	"GET /api/work-orders":                                                                      "work_orders.read",
	"GET /api/work-orders/{workOrderId}":                                                        "work_orders.read",
	"PATCH /api/agent-accounts/{accountId}":                                                     "account.manage",
	"POST /api/agent-accounts/{accountId}/archive":                                              "account.manage", // Person-only Remove (AEON-402).
	"PATCH /api/attachments/{id}":                                                               "attachments.write",
	"PATCH /api/crm/contacts/{contactId}":                                                       "crm.write",
	"PATCH /api/crm/organisations/{organisationId}":                                             "crm.write",
	"PATCH /api/crm/organisations/{organisationId}/visibility":                                  "crm.write",
	"PATCH /api/kinds/{kindId}":                                                                 "kinds.manage",
	"PATCH /api/knowledge/{id}":                                                                 "knowledge.write",
	"PATCH /api/me/profile":                                                                     "profile.write|profile.portal_write",
	"PATCH /api/nodes/{nodeId}":                                                                 "nodes.write",
	"PATCH /api/nodes/{nodeId}/comments/{commentId}":                                            "comments.write",
	"DELETE /api/portal/aspects/{aspectId}":                                                     "settings.manage",
	"DELETE /api/portal/competitors/{competitorId}":                                             "settings.manage",
	"GET /api/portal/market":                                                                    "settings.manage",
	"GET /api/portal/pace":                                                                      "settings.manage",
	"PATCH /api/portal/aspects/{aspectId}":                                                      "settings.manage",
	"PATCH /api/portal/competitors/{competitorId}":                                              "settings.manage",
	"PATCH /api/portal/features/{featureId}":                                                    "settings.manage",
	"PATCH /api/portal/products/{productId}":                                                    "settings.manage",
	"PATCH /api/portal/settings":                                                                "settings.manage",
	"POST /api/portal/aspects":                                                                  "settings.manage",
	"POST /api/portal/cells/{cellId}/approve":                                                   "settings.manage",
	"POST /api/portal/competitors":                                                              "settings.manage",
	"POST /api/portal/corrections/{correctionId}/close":                                         "settings.manage",
	"PUT /api/portal/cells":                                                                     "settings.manage",
	"PUT /api/portal/pace":                                                                      "settings.manage",
	"PUT /api/portal/wishes/{wishId}/fulfillment":                                               "settings.manage",
	"PATCH /api/project-groups/{groupId}":                                                       "project_groups.write",
	"PATCH /api/projects/{projectId}/harness-sessions/{sessionId}/binding":                      "harness.write",
	"PATCH /api/quote-profiles/{profileId}":                                                     "quotes.write",
	"PATCH /api/quotes/settings":                                                                "settings.manage",
	"PATCH /api/quotes/{quoteId}/draft":                                                         "quotes.write",
	"PATCH /api/quotes/{quoteId}/presence/{sessionId}":                                          "quotes.write",
	"PATCH /api/quotes/{quoteId}/visibility":                                                    "quotes.write",
	"PATCH /api/roles/{id}":                                                                     "roles.manage",
	"PATCH /api/tags/{tagId}":                                                                   "tags.write",
	"PATCH /api/time-entries/{id}":                                                              "hours.write",
	"PATCH /api/views/{viewId}":                                                                 "views.write",
	"PATCH /api/work-orders/{workOrderId}":                                                      "work_orders.write",
	"POST /api/agent-accounts":                                                                  "account.manage",
	"POST /api/agent-accounts/route":                                                            "account.route",
	"POST /api/agent-accounts/{accountId}/probe":                                                "account.probe",
	"POST /api/agent-accounts/{accountId}/windows":                                              "account.manage",
	"DELETE /api/agent-accounts/{accountId}/windows/{windowId}":                                 "account.manage",
	"POST /api/agent-accounts/{accountId}/windows/{windowId}/repeat":                            "account.manage",
	"POST /api/agent-keys":                                                                      "keys.manage",
	"POST /api/members/agents":                                                                  "keys.manage",
	"POST /api/members/invites":                                                                 "members.manage",
	"POST /api/members/invites/{id}/provision":                                                  "members.manage",
	"POST /api/members/{principal_id}/aliases":                                                  "members.manage",
	"POST /api/members/{principal_id}/deactivate":                                               "members.manage",
	"POST /api/members/{principal_id}/reactivate":                                               "members.manage",
	"POST /api/approvals":                                                                       "approvals.request",
	"POST /api/approvals/{approvalId}/decision":                                                 "approvals.decide",
	"POST /api/approvals/{approvalId}/revoke":                                                   "approvals.revoke",
	"POST /api/auth/dev-login":                                                                  "public",
	"POST /api/auth/logout":                                                                     "public",
	"POST /api/cost-units/{costUnitId}/rates":                                                   "cost_units.manage",
	"POST /api/crm/contacts/{contactId}/principals":                                             "crm.manage",
	"POST /api/crm/organisations":                                                               "crm.write",
	"POST /api/crm/organisations/{organisationId}/contacts":                                     "crm.write",
	"POST /api/crm/organisations/{organisationId}/note-ai/generate":                             "crm.manage",
	"POST /api/crm/organisations/{organisationId}/note-rewrite":                                 "crm.manage",
	"POST /api/crm/organisations/{organisationId}/note-rewrite/{draftId}/apply":                 "crm.manage",
	"POST /api/crm/organisations/{organisationId}/number/reformat":                              "crm.write",
	"POST /api/crm/organisations/{organisationId}/primary-contact":                              "crm.write",
	"POST /api/crm/organisations/{organisationId}/sync":                                         "crm.write",
	"POST /api/crm/providers/{providerId}/import":                                               "crm.manage",
	"POST /api/events/{eventId}/undo":                                                           "events.undo",
	"GET /api/events/{eventId}/undo-preview":                                                    "events.undo",
	"POST /api/inbox/messages":                                                                  "inbox.send",
	"POST /api/inbox/messages/{messageId}/ack":                                                  "inbox.send",
	"POST /api/inbox/session-binding":                                                           "inbox.send",
	"POST /api/inbox/targets":                                                                   "inbox.send|inbox.manage",
	"POST /api/kinds":                                                                           "kinds.manage",
	"POST /api/knowledge":                                                                       "knowledge.write",
	"POST /api/knowledge/learnings/{learningId}/accept":                                         "knowledge.write",
	"POST /api/knowledge/learnings/{learningId}/dismiss":                                        "knowledge.write",
	"POST /api/knowledge/learnings/{learningId}/draft":                                          "knowledge.write",
	"POST /api/me/avatar":                                                                       "profile.write|profile.portal_write",
	"GET /api/model-prices":                                                                     "harness.read",
	"POST /api/model-prices":                                                                    "models.manage",
	"GET /api/projects/{projectId}/instruction-provenance":                                      "harness.read",
	"GET /api/projects/{projectId}/lead-decisions":                                              "nodes.read",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/lead-decisions":                  "harness.worker",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/provenance":                     "harness.read",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/usage":                          "harness.read",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/provenance":                    "harness.worker",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/rules-receipts":                 "harness.read",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/rules-receipts":                "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/usage":                         "harness.worker",
	"POST /api/models":                                                                          "models.manage",
	"POST /api/outcomes":                                                                        "outcome.write",
	"POST /api/nodes":                                                                           "nodes.write",
	"POST /api/nodes/bulk":                                                                      "nodes.write",
	"POST /api/portal/wishes/{wishId}/hide":                                                     "settings.manage",
	"POST /api/portal/wishes/{wishId}/publish":                                                  "settings.manage",
	"POST /api/portal/wishes/{wishId}/reject":                                                   "settings.manage",
	"POST /api/nodes/{nodeId}/attachments":                                                      "attachments.write",
	"POST /api/nodes/{nodeId}/comments":                                                         "comments.write",
	"POST /api/nodes/{nodeId}/convert":                                                          "nodes.write",
	"POST /api/nodes/{nodeId}/move":                                                             "nodes.move",
	"POST /api/nodes/{nodeId}/project-move":                                                     "nodes.move",
	"POST /api/project-groups":                                                                  "project_groups.write",
	"POST /api/project-groups/assign":                                                           "project_groups.write",
	"POST /api/projects/{projectId}/baseline-batches/batches/{batchId}/built-receipt":           "stage.verify",
	"POST /api/projects/{projectId}/harness-sessions":                                           "harness.write",
	"POST /api/projects/{projectId}/harness-sessions/pause":                                     "harness.control",
	"POST /api/projects/{projectId}/harness-sessions/resume":                                    "harness.control",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/pause":                         "harness.control",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/pause-plan":                    "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/resume":                        "harness.control",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/complete-delivery":             "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/managed-controls":              "harness.control",
	"GET /api/projects/{projectId}/harness-sessions/{sessionId}/managed-settings":               "harness.control",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/managed-context":               "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/requests":                      "harness.control",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/controls/interrupt":            "harness.control",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/controls/stop":                 "harness.control",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/controls/{controlId}/complete": "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/drain":                         "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/heartbeat":                     "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/stop":                          "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/confirm-exit":                  "harness.worker",
	"POST /api/projects/{projectId}/harness-sessions/{sessionId}/yield":                         "harness.worker",
	"POST /api/projects/{projectId}/intake/drafts":                                              "intake.write",
	"POST /api/projects/{projectId}/intake/drafts/{draftId}/replace":                            "intake.write",
	"POST /api/projects/{projectId}/intake/drafts/{draftId}/accept":                             "intake.decide",
	"POST /api/projects/{projectId}/intake/sources":                                             "intake.write",
	"POST /api/projects/{projectId}/intake/transcript-turns":                                    "intake.write",
	"POST /api/projects/{projectId}/journey/actions":                                            "journey.act",
	"POST /api/projects/{projectId}/message-targets":                                            "inbox.manage",
	"POST /api/projects/{projectId}/messages":                                                   "inbox.send",
	"POST /api/projects/{projectId}/messages/delivery-claim":                                    "inbox.send",
	"POST /api/projects/{projectId}/messages/delivery-complete":                                 "inbox.send",
	"POST /api/projects/{projectId}/messages/delivery-unavailable":                              "inbox.send",
	"POST /api/projects/{projectId}/messages/{messageId}/ack":                                   "inbox.send",
	"POST /api/projects/{projectId}/messages/{messageId}/resolution":                            "inbox.manage",
	"POST /api/projects/{projectId}/releases/{releaseId}/tickets":                               "releases.write",
	"POST /api/projects/{projectId}/releases/{releaseId}/membership":                            "releases.write",
	"POST /api/projects/{projectId}/requirements":                                               "requirements.write",
	"POST /api/projects/{projectId}/requirements/agree":                                         "requirements.agree",
	"POST /api/public/portal/{tenantSlug}/corrections":                                          "public",
	"POST /api/public/portal/{tenantSlug}/wishes":                                               "public",
	"POST /api/public/portal/{tenantSlug}/wishes/{wishKey}/votes":                               "public",
	"POST /api/public/quotes/{publicTenant}/{token}/accept":                                     "public",
	"POST /api/quote-profiles":                                                                  "quotes.write",
	"POST /api/quote-profiles/assets":                                                           "quotes.write",
	"POST /api/quote-profiles/{profileId}/undo":                                                 "quotes.write",
	"POST /api/quotes":                                                                          "quotes.write",
	"POST /api/quotes/{quoteId}/draft/branch":                                                   "quotes.write",
	"POST /api/quotes/{quoteId}/duplicate":                                                      "quotes.write",
	"POST /api/quotes/{quoteId}/finalize":                                                       "quotes.write",
	"POST /api/quotes/{quoteId}/presence":                                                       "quotes.write",
	"POST /api/quotes/{quoteId}/versions":                                                       "quotes.write",
	"POST /api/quotes/{quoteId}/versions/{version}/accept":                                      "quotes.accept|quotes.portal_accept",
	"POST /api/quotes/{quoteId}/versions/{version}/confirmation/retry":                          "quotes.manage",
	"POST /api/quotes/{quoteId}/versions/{version}/issue":                                       "quotes.issue",
	"POST /api/quotes/{quoteId}/versions/{version}/public-link":                                 "quotes.manage",
	"POST /api/quotes/{quoteId}/versions/{version}/public-link/revoke":                          "quotes.manage",
	"POST /api/relations":                                                                       "relations.write",
	"POST /api/roles":                                                                           "roles.manage",
	"POST /api/runs/{runId}/claim":                                                              "run.claim",
	"POST /api/runs/{runId}/capacity-override":                                                  "run.create", // Person-only, queued managed run; handler checks work-order edit access.
	"POST /api/runs/{runId}/cancel":                                                             "run.create", // Person-only, queued run; handler checks work-order edit access (AEON-402).
	"POST /api/runs/{runId}/telemetry":                                                          "run.telemetry",
	"POST /api/stage-handoffs":                                                                  "stage_handoffs.write",
	"POST /api/stage-handoffs/{handoffId}/classic-batch-alias":                                  "stage_handoffs.decide",
	"POST /api/stage-handoffs/{handoffId}/evidence":                                             "stage_handoffs.write|stage.prepare|stage.deploy|stage.verify|stage.apply",
	"POST /api/stage-handoffs/{handoffId}/launch/admit":                                         "stage.deploy",
	"POST /api/stage-handoffs/{handoffId}/launch/consume":                                       "stage.deploy",
	"POST /api/stage-handoffs/{handoffId}/result":                                               "stage_handoffs.decide|stage.prepare|stage.deploy|stage.verify|stage.apply",
	"POST /api/time-entries":                                                                    "hours.write",
	"POST /api/time-periods":                                                                    "hours.write",
	"POST /api/time-periods/{periodId}/approve":                                                 "hours.approve",
	"POST /api/views":                                                                           "views.write",
	"POST /api/views/{viewId}/restore":                                                          "views.write",
	"POST /api/work-orders":                                                                     "work_orders.write",
	"POST /api/work-orders/{workOrderId}/criteria/{criterionId}/check":                          "work_orders.write",
	"POST /api/work-orders/{workOrderId}/evidence":                                              "work_orders.write",
	"POST /api/work-orders/{workOrderId}/runs":                                                  "run.create", // Account choice only constrains routing; reservation/claim retain their scopes.
	"PUT /api/crm/documents/{attachmentId}/metadata":                                            "crm.write",
	"PUT /api/crm/projects/{projectId}/cooperation":                                             "crm.write",
	"PUT /api/crm/projects/{projectId}/customer":                                                "crm.write",
	"PUT /api/crm/providers/{providerId}/config":                                                "crm.manage",
	"PUT /api/members/{principal_id}/workspace-role":                                            "members.manage",
	"PUT /api/models/routes":                                                                    "models.manage",
	"PUT /api/plugins/{pluginId}/installation":                                                  "plugins.manage",
	"PUT /api/preferences/{key}":                                                                "views.write",
	"PUT /api/projects/{projectId}/journey/profile":                                             "journey.act",
	"PUT /api/projects/{projectId}/releases/{releaseId}/plan":                                   "releases.write",
	"PUT /api/quotes/{quoteId}/profile":                                                         "quotes.write",
	"GET /api/settings/quota-warnings":                                                          "settings.manage",
	"PUT /api/settings/quota-warnings":                                                          "settings.manage",
	"GET /api/agent-accounts/quota-warnings":                                                    "account.read",
	"GET /api/settings/work-vocabulary":                                                         "nodes.read",
	"PUT /api/settings/work-vocabulary":                                                         "settings.manage",
	"GET /api/settings/eta-interval":                                                            "settings.manage",
	"PUT /api/settings/eta-interval":                                                            "settings.manage",
	"GET /api/settings/brand":                                                                   "settings.manage",
	"PUT /api/settings/brand":                                                                   "settings.manage",
	"GET /api/settings/model-provider":                                                          "settings.manage",
	"PUT /api/settings/model-provider":                                                          "settings.manage",
	"POST /api/settings/model-provider/test":                                                    "settings.manage",
	"PUT /api/settings/brand/logo/{variant}":                                                    "settings.manage",
	"DELETE /api/settings/brand/logo/{variant}":                                                 "settings.manage",
	"GET /api/brand/logo/{variant}":                                                             "profile.read|profile.portal_read",
	"GET /api/settings/status-autopilot":                                                        "nodes.read",
	"PUT /api/settings/status-autopilot":                                                        "settings.manage",
	"GET /api/projects/{projectId}/status-autopilot":                                            "nodes.read",
	"PUT /api/projects/{projectId}/status-autopilot":                                            "settings.manage",
	"GET /api/status-autopilot/attention":                                                       "nodes.read",
	"POST /api/status-autopilot/attention/actions":                                              "nodes.write",
	"GET /api/status-autopilot/changes":                                                         "nodes.read",
	"GET /api/status-autopilot/proposals":                                                       "nodes.read",
	"PUT /api/status-autopilot/proposals/{eventId}":                                             "settings.manage",
	"GET /api/settings/agent-activity":                                                          "settings.manage",
	"PUT /api/settings/agent-activity":                                                          "settings.manage",
	"GET /api/settings/heartbeat-lost":                                                          "settings.manage",
	"PUT /api/settings/heartbeat-lost":                                                          "settings.manage",
	"PUT /api/nodes/{nodeId}/live-eta":                                                          "harness.worker",
	"PUT /api/projects/{projectId}/harness-sessions/{sessionId}/read-marker":                    "harness.read",
	"GET /api/settings/inbox-delivery":                                                          "settings.read",
	"PUT /api/settings/inbox-delivery":                                                          "settings.manage",
}

// Tier reads, worker reports and person decisions use the existing session permissions.
func init() {
	RoutePermissions["GET /api/projects/{projectId}/harness-sessions/{sessionId}/tier"] = "harness.read"
	RoutePermissions["POST /api/projects/{projectId}/harness-sessions/{sessionId}/tier"] = "harness.control"
	RoutePermissions["POST /api/projects/{projectId}/harness-sessions/{sessionId}/tier/report"] = "harness.worker"
	RoutePermissions["POST /api/projects/{projectId}/harness-sessions/{sessionId}/tier/ask"] = "harness.worker"
	RoutePermissions["POST /api/projects/{projectId}/harness-sessions/{sessionId}/tier/requests/{requestId}/decision"] = "harness.control"
}

func PermissionForPattern(pattern string) (string, bool) {
	permission, ok := RoutePermissions[pattern]
	return permission, ok
}

// PatternIsPublic reports whether the router's matched pattern is a public
// declaration. Session refresh and the authentication gate use this and not
// the request URL: the router accepts other spellings of the same pattern.
func PatternIsPublic(pattern string) bool {
	declaration, ok := PermissionForPattern(pattern)
	return ok && declaration == PublicRoute
}

// RequirePattern denies missing declarations. A public declaration leaves the
// route's own capability or login checks in place. An authenticated declaration
// requires the trusted principal set by authentication. Quote portal declarations
// allow either staff or customer authority; the handler checks ownership.
// Status help is scope-free tenant metadata for agents; people retain nodes.read.
func RequirePattern(ctx context.Context, pattern string, scope Scope) error {
	declaration, ok := PermissionForPattern(pattern)
	if !ok {
		return ErrForbidden
	}
	if declaration == PublicRoute {
		return nil
	}
	if pattern == "GET /api/status/help" {
		p, ok := tenant.PrincipalFrom(ctx)
		if !ok || p.ID == "" || p.TenantID == "" {
			return ErrForbidden
		}
		if p.Kind == tenant.Agent {
			return nil
		}
	}
	if declaration == AuthenticatedRoute {
		if p, ok := tenant.PrincipalFrom(ctx); ok && p.ID != "" && p.TenantID != "" {
			return nil
		}
		return ErrForbidden
	}
	var denialErr error = ErrForbidden
	for _, permission := range strings.Split(declaration, "|") {
		err := Require(ctx, permission, scope)
		if err == nil {
			return nil
		}
		if !errors.Is(err, ErrForbidden) {
			return err
		}
		// Prefer a missing key scope only after this route alternative's role
		// authority passed; otherwise keep the first denial.
		var d *denial
		if denialErr == ErrForbidden || errors.As(err, &d) && d.reason == "missing_key_scope" {
			denialErr = err
		}
	}
	return denialErr
}
