// SPDX-License-Identifier: AGPL-3.0-only
// Plain words of the Delivery page's Simple level (AEON-994 draft 5, section 7 and
// the approved mock). English and German, impersonal. Placeholders in braces are
// filled with the selected window's own numbers, never with the mock's.
import type { DeliveryLanguage } from './delivery'
import type { MetricTextKey } from './deliveryNumbersText'

const TO = '→'

export interface SimpleMetricText {
  name: string; say: string; sayAlt?: string; wants: string; learn: string; learnPart?: string; src: string; part?: string
}

const EN = {
  learn: 'Learn', lower: 'lower is better', higher: 'higher is better', better: 'better',
  on: 'On target', close: 'Close', far: 'Far off', none: 'No target yet', nodataV: 'No data yet', notLoaded: 'Not loaded',
  target: 'target', theTarget: 'the target', wanted: 'wanted', about: 'about',
  tBetter: 'Better than the {w} days before', tWorse: 'Worse than the {w} days before', tSame: 'Steady vs. the {w} days before',
  tNone: 'No data in the {w} days before', tLoading: 'History still loading: no comparison yet', tNoData: 'Nothing to compare yet',
  partial: 'Partial', noDataYet: 'no data yet', eachNight: 'one square per night', learnHead: 'Learn', expertName: 'In the Expert view', arion: 'Project Arion',
  units: { min: 'min', h: 'h', times: 'times', byScript: 'by script', nightsGreen: 'nights green', nightGreen: 'night green', of: 'of', per100: 'per 100 PRs', recorded: 'recorded',
    count: { review_audits: 'audits', escaped_defects: 'defects' }, countOne: { review_audits: 'audit', escaped_defects: 'defect' } },
  // Summary card
  sumNone: 'None of the {t} numbers with a target is on target yet.', sumSome: '{k} of {t} numbers are on target.',
  closest: 'Closest', biggest: 'Biggest gap',
  week: 'Last {w} days vs. the {w} before: {b} better · {x} worse · {s} steady · {n} without a comparison',
  charts: 'Small charts: one point per {u}', chartsHatch: ' · hatched = no data yet (history starts {d})', per: { day: 'day', week: 'week', month: 'month' },
  legend: 'Legend', nodataT: 'No numbers yet.', nodataB: 'They appear with the first pull request. The targets below already apply.',
  onTarget: '{k} of {t} on target',
  nightsNote: { day: 'Last {n} nights · empty = no run', week: 'Last {n} weeks · empty = no run', month: 'Last {n} months · empty = no run' },
  redSince: 'red every night since {d}', redRan: 'red every night it ran', greenOf: '{k} of {n} nights green',
  sections: [
    { title: 'Making a change ready', sub: 'Checks, re-runs and review, before a change can merge.' },
    { title: 'Getting it merged', sub: 'From opening the PR to merged, through the merge queue.' },
    { title: 'Shipping it', sub: 'From release to live, and the full test run each night.' },
    { title: 'Keeping it safe', sub: 'Audits of merged changes, and defects that reached production.' },
  ],
  defsTitle: 'The technical words, explained simply',
  defs: [
    ['Median (p50)', 'The middle value: half were faster, half slower. A few extreme cases do not distort it.'],
    ['Slow tail (p90)', 'Nine in ten were faster. It shows how bad the bad cases are.'],
    ['First try vs. until green', '“PR checks” measures one run. “Until checks are green” counts every re-run and fix as well.'],
    ['Run time vs. waiting', `Run time (wall) is start ${TO} end of one run. Waiting for a runner or in the queue is not in it; “From PR opened to merged” includes all waiting.`],
    ['Flaky test', 'A test that sometimes fails without a real bug. A re-run without any code change turns green. “Confirmed” means a re-run of the same commit passed; “suspect” only that the next commit passed on the very same files.'],
    ['Thrown out of the queue', 'The merge queue builds a change with the newest main. When a required check fails there, the change is taken out and must go in again.'],
    ['Partial and no data yet', 'Partial: the source sees only part of the picture (e.g. reported only recently). No data yet: nothing recorded, never shown as 0.'],
  ] as [string, string][],
  metrics: {
    pr_ci_wall: { name: 'How long the PR checks take', say: 'Every change waits about {v} for its checks.', wants: 'Arion wants 10 min, later 7.',
      learn: 'p50 (median) {p50}: half of the runs were faster than this. p90 {p90}: nine in ten were faster; it shows the slow tail. Wall time: start to end of one run; waiting for a free runner before the start is not counted.', src: 'Measured from GitHub' },
    queue_run_wall: { name: 'One merge-queue run', say: 'One pass through the merge queue takes about {v}.', wants: 'Arion wants 10 min, later 7.',
      learn: 'Merge-queue run duration (wall), p50 {p50} · p90 {p90}. One run of the full checks in the merge queue; the wait in the queue before it starts is not counted.', src: 'Measured from GitHub' },
    first_attempt_green: { name: 'Checks green on the first try', say: '{v} of changes pass every check on the first try; counted the way the merge rule counts, {v2} do.', sayAlt: '{v} of changes pass every check on the first try.',
      wants: 'Arion wants at least 70 %, later 80 %.',
      learn: 'First-attempt green rate: {v} of {n} first attempts ended green. Counted by the merge rule, only the required checks decide, so a run that is red only outside them is green ({v2}). Arion target: green on the first try ≥ {t} (D4″).', src: 'Measured from GitHub' },
    time_to_first_green: { name: 'Time until checks are green', say: 'Until its checks are green, a branch needs about {v}, re-runs and fixes included.', wants: 'Arion wants 30 min, later 20.',
      learn: 'Time to first green per branch, p50 {p50} · p90 {p90}. Counted from the first CI run of a PR branch to the first green one, with every re-run and fix in between. {never} of {total} branches never went green and are not in this time; {first} were green on their very first run.', src: 'Measured from GitHub' },
    pr_open_to_merged: { name: 'From PR opened to merged', say: 'From opening a PR to merging it takes about {v}.', wants: 'Arion wants 80 min, later 60.',
      learn: `PR opened ${TO} merged, p50 {p50} · p90 {p90}. Clock time, including review, fix rounds, waiting in the queue and being sent back.`, src: 'Measured from GitHub' },
    queue_runs_per_pr: { name: 'Queue tries per change', say: 'On average a change goes through the queue {v} times before it lands.', wants: 'Arion wants 1.25, later 1.1: almost every change in one go.',
      learn: 'Queue runs per PR, mean {v} · p90 {p90}. Every extra run means the change was sent back, usually by a flaky test or a conflict.', src: 'Measured from GitHub' },
    review_time: { name: 'How long a review takes', say: 'A review takes about {v}, and {k} of {n} reviews ask for changes.', sayAlt: 'A review takes about {v}.', wants: 'Arion wants 10 min, later 8, and changes in at most 1 of 4.',
      learn: `Review time (first round), p50 {p50} · p90 {p90}: review requested ${TO} verdict posted. Share of “changes” verdicts: {k} of {n}. Partial: only PRs with an aeon/review status are counted.`,
      src: 'From review statuses on GitHub', part: 'only reviews with a status count' },
    merge_rounds_model_share: { name: 'Conflicts solved by script', say: 'When a change collides with a newer main, a script solved it {k} times out of {n}; an agent did the rest.', wants: 'Arion wants 8 of 10 by script.',
      learn: 'Merge rounds, model share {m} ({km} of {n}). A merge round is a PR that conflicts with a moved main; scripted means the merge driver resolved it.', learnPart: ' Partial: the merge tooling reports rounds since {d}.',
      src: 'Reported by the merge tooling', part: 'reports since {d}' },
    release_queue_to_live: { name: 'From release to live', say: 'Release {r} took about {v} from the queue to live on csb1.', sayAlt: 'A release takes about {v} from the queue to live on csb1 ({n} releases).', wants: 'Arion wants about 61 min, later 54, plus the wait for a person.',
      learn: `Release, merge queue ${TO} live on csb1, p50 {p50} over {n}.`, learnPart: ' Partial: the release tooling reports since {d}.',
      src: 'Reported by the release tooling', part: 'reported since {d}' },
    nightly_green: { name: 'Full test run each night', say: 'The full test run failed on all {n} nights it ran, since it started on {d}.', sayAlt: 'The full test run was green on {k} of {n} nights it ran.', wants: 'Arion wants it green every night.',
      learn: 'Nightly full run, {k} of {n} nights green. One verdict per night from the scheduled full run; a night without a run is shown as “no run”, never as red.', src: 'Measured from GitHub' },
    time_to_first_green_commit: { name: 'Time until a commit is green', say: 'A commit needs about {v} until one of its runs is green.', wants: 'Arion has no target for this yet.',
      learn: 'Time to first green per commit, p50 {p50} · p90 {p90}. {never} of {total} commits never went green, {sup} of them because a newer commit on the branch replaced them.', src: 'Measured from GitHub' },
    flaked_failures: { name: 'Runs that failed, then passed', say: '{v} of first attempts failed and then passed on a re-run of the same commit; {suspect} more look suspicious.', wants: 'Arion wants 2 % or less.',
      learn: 'Confirmed flaky runs: a run failed, then passed on a later attempt of the same run, so same commit and same workflow ({confirmed} of {n} first attempts, {v}). Suspects ({suspect}): a run failed on a commit and the next commit passed on the very same tree. They are not confirmed and not in the share.', src: 'Measured from GitHub' },
    queue_ejections: { name: 'Changes thrown out of the queue', say: 'About {v} of every 100 merged changes were thrown out of the merge queue first because a required check failed ({e} runs for {b} merged changes).', wants: 'Arion wants 25 or fewer, later 10.',
      learn: 'Inferred ejections per 100 merged PRs: {e} merge-queue runs with a red required check for {b} merged PRs. Inferred, because the queue’s own events are not joined to the runs yet.', src: 'Measured from GitHub' },
    queue_unclassified: { name: 'Extra queue runs, cause unknown', say: 'For every 100 merged changes, {v} extra queue runs were not caused by a failed required check ({e} runs for {b} merged changes).', wants: 'Arion sets a target once the causes are sorted out.',
      learn: 'Queue runs before the one that merged that were cancelled or green in the required checks: {e} for {b} merged PRs. A failing predecessor, a reordering and a manual removal cannot be told apart yet.', src: 'Measured from GitHub' },
    runner_wait: { name: 'Waiting for a runner', say: 'One run in ten waits {v} or longer for a runner, counting its slowest job.', wants: 'Arion wants 3 min, later 1.',
      learn: 'Worst job wait per run: p90 {p90}, p50 {p50}. The longest time any job of a run waited between being created and being started; skipped jobs have no wait.', src: 'Measured from GitHub' },
    preflight_red_rate: { name: 'Pre-checks that failed', say: '{v} of the pre-checks before a PR opens ended red ({n} runs).', wants: 'Arion has no target: it stands beside the first-try numbers.',
      learn: 'Preflight red rate: the exact-commit preflight runs the builder starts before opening a PR; {v} of {n} first attempts ended red. They never count as CI green.', src: 'Measured from GitHub' },
    review_audits: { name: 'Findings in review audits', say: 'Merged changes re-reviewed by a second model: {n}, {high} with a high finding, {medium} medium, {low} low, {clean} clean.', sayAlt: 'No review audit was reported in this window.', wants: 'Findings are watched, not capped.',
      learn: 'Each week a few merged PRs are re-reviewed by a model of another family. The highest severity of each audit’s findings is counted here.', learnPart: ' Partial: audits are reported since {d}.', src: 'Reported by the audit tooling', part: 'reports since {d}' },
    escaped_defects: { name: 'Defects that reached production', say: 'Defects that escaped to production: {n}, {high} high, {medium} medium, {low} low.', sayAlt: 'No escaped defect was recorded in this window.', wants: 'Arion wants this number falling.',
      learn: 'Bug or incident tickets linked as caused by a merged PR or a release, and rollout incidents of releases (down counts as high, degraded as medium). Red on main alone is not a defect that escaped.', learnPart: ' Partial: recording starts on {d}.', src: 'Reported links and rollouts', part: 'recorded since {d}' },
  } satisfies Record<MetricTextKey, SimpleMetricText> as Record<MetricTextKey, SimpleMetricText>,
  releaseOne: '1 release', releaseMany: '{n} releases',
}
export type SimpleText = typeof EN

const DE: SimpleText = {
  learn: 'Lernen', lower: 'niedriger ist besser', higher: 'höher ist besser', better: 'besser',
  on: 'Im Ziel', close: 'Knapp dran', far: 'Weit weg', none: 'Noch kein Ziel', nodataV: 'Noch keine Daten', notLoaded: 'Nicht geladen',
  target: 'Ziel', theTarget: 'das Ziel', wanted: 'gewollt', about: 'etwa',
  tBetter: 'Besser als die {w} Tage davor', tWorse: 'Schlechter als die {w} Tage davor', tSame: 'Stabil ggü. den {w} Tagen davor',
  tNone: 'Keine Daten in den {w} Tagen davor', tLoading: 'Historie lädt noch: noch kein Vergleich', tNoData: 'Noch nichts zu vergleichen',
  partial: 'Teilweise', noDataYet: 'noch keine Daten', eachNight: 'ein Feld pro Nacht', learnHead: 'Lernen', expertName: 'In der Expertenansicht', arion: 'Project Arion',
  units: { min: 'min', h: 'h', times: '-mal', byScript: 'per Skript', nightsGreen: 'Nächten grün', nightGreen: 'Nacht grün', of: 'von', per100: 'pro 100 PRs', recorded: 'erfasst',
    count: { review_audits: 'Prüfungen', escaped_defects: 'Fehler' }, countOne: { review_audits: 'Prüfung', escaped_defects: 'Fehler' } },
  sumNone: 'Noch keine der {t} Zahlen mit Ziel ist im Ziel.', sumSome: '{k} von {t} Zahlen sind im Ziel.',
  closest: 'Am nächsten dran', biggest: 'Größte Lücke',
  week: 'Letzte {w} Tage gegen die {w} davor: {b} besser · {x} schlechter · {s} stabil · {n} ohne Vergleich',
  charts: 'Kleine Diagramme: ein Punkt pro {u}', chartsHatch: ' · schraffiert = noch keine Daten (die Historie beginnt am {d})', per: { day: 'Tag', week: 'Woche', month: 'Monat' },
  legend: 'Legende', nodataT: 'Noch keine Zahlen.', nodataB: 'Sie erscheinen mit dem ersten Pull Request. Die Ziele unten gelten schon.',
  onTarget: '{k} von {t} im Ziel',
  nightsNote: { day: 'Letzte {n} Nächte · leer = kein Lauf', week: 'Letzte {n} Wochen · leer = kein Lauf', month: 'Letzte {n} Monate · leer = kein Lauf' },
  redSince: 'seit {d} jede Nacht rot', redRan: 'jede Nacht mit Lauf rot', greenOf: '{k} von {n} Nächten grün',
  sections: [
    { title: 'Eine Änderung fertig machen', sub: 'Checks, Wiederholungen und Review, bevor eine Änderung mergen kann.' },
    { title: 'Sie in main bringen', sub: 'Vom Öffnen des PR bis zum Merge, durch die Merge-Queue.' },
    { title: 'Ausliefern', sub: 'Vom Release bis live, und der volle Testlauf jede Nacht.' },
    { title: 'Sicher bleiben', sub: 'Audits gemergter Änderungen, und Fehler, die live gingen.' },
  ],
  defsTitle: 'Die Fachwörter, einfach erklärt',
  defs: [
    ['Median (p50)', 'Der mittlere Wert: Die Hälfte war schneller, die Hälfte langsamer. Ausreißer verzerren ihn nicht.'],
    ['Langsame Ausreißer (p90)', 'Neun von zehn waren schneller. Zeigt, wie schlimm die schlechten Fälle sind.'],
    ['Erster Versuch vs. bis grün', '„PR-Checks“ misst einen Lauf. „Bis die Checks grün sind“ zählt alle Wiederholungen und Fixes mit.'],
    ['Laufzeit vs. Wartezeit', `Laufzeit (Wall) ist Start ${TO} Ende eines Laufs. Warten auf einen Runner oder in der Queue zählt dort nicht; „Vom PR bis zum Merge“ enthält alles Warten.`],
    ['Wackeliger Test (Flake)', 'Ein Test, der manchmal ohne echten Fehler scheitert. Eine Wiederholung ohne Codeänderung wird grün. „Bestätigt“ heißt: Eine Wiederholung desselben Commits lief durch; „verdächtig“ nur: Der nächste Commit lief auf genau denselben Dateien durch.'],
    ['Aus der Queue geworfen', 'Die Merge-Queue baut eine Änderung mit dem neuesten main. Scheitert dort eine Pflichtprüfung, wird die Änderung herausgenommen und muss erneut hinein.'],
    ['Teilweise und noch keine Daten', 'Teilweise: Die Quelle sieht nur einen Teil (z. B. erst seit Kurzem gemeldet). Noch keine Daten: nichts erfasst, nie als 0 gezeigt.'],
  ],
  metrics: {
    pr_ci_wall: { name: 'Wie lange die PR-Checks dauern', say: 'Jede Änderung wartet etwa {v} auf ihre Checks.', wants: 'Arion will 10 min, später 7.',
      learn: 'p50 (Median) {p50}: Die Hälfte der Läufe war schneller. p90 {p90}: Neun von zehn waren schneller; das zeigt die langsamen Ausreißer. Wall-Zeit: Start bis Ende eines Laufs; das Warten auf einen freien Runner davor zählt nicht.', src: 'Gemessen über GitHub' },
    queue_run_wall: { name: 'Ein Merge-Queue-Durchlauf', say: 'Ein Durchlauf der Merge-Queue dauert etwa {v}.', wants: 'Arion will 10 min, später 7.',
      learn: 'Merge-Queue-Laufdauer (Wall), p50 {p50} · p90 {p90}. Ein Lauf der vollen Checks in der Merge-Queue; die Wartezeit davor zählt nicht.', src: 'Gemessen über GitHub' },
    first_attempt_green: { name: 'Checks beim ersten Versuch grün', say: '{v} der Änderungen bestehen alle Checks beim ersten Versuch; so gezählt, wie die Merge-Regel zählt, sind es {v2}.', sayAlt: '{v} der Änderungen bestehen alle Checks beim ersten Versuch.',
      wants: 'Arion will mindestens 70 %, später 80 %.',
      learn: 'Grün-Quote beim ersten Versuch: {v} von {n} ersten Versuchen endeten grün. Nach der Merge-Regel entscheiden nur die Pflichtprüfungen; ein Lauf, der nur außerhalb davon rot ist, gilt als grün ({v2}). Arion-Ziel: grün beim ersten Versuch ≥ {t} (D4″).', src: 'Gemessen über GitHub' },
    time_to_first_green: { name: 'Zeit, bis die Checks grün sind', say: 'Bis ihre Checks grün sind, braucht ein Branch etwa {v}, Wiederholungen und Fixes inklusive.', wants: 'Arion will 30 min, später 20.',
      learn: 'Zeit bis zum ersten Grün pro Branch, p50 {p50} · p90 {p90}. Gezählt vom ersten CI-Lauf eines PR-Branches bis zum ersten grünen, mit allen Wiederholungen und Fixes dazwischen. {never} von {total} Branches wurden nie grün und stehen nicht in dieser Zeit; {first} waren schon beim ersten Lauf grün.', src: 'Gemessen über GitHub' },
    pr_open_to_merged: { name: 'Vom PR bis zum Merge', say: 'Vom Öffnen eines PR bis zum Merge vergehen etwa {v}.', wants: 'Arion will 80 min, später 60.',
      learn: `PR geöffnet ${TO} gemergt, p50 {p50} · p90 {p90}. Uhrzeit inklusive Review, Fix-Runden, Warten in der Queue und Zurückschicken.`, src: 'Gemessen über GitHub' },
    queue_runs_per_pr: { name: 'Queue-Versuche pro Änderung', say: 'Im Schnitt geht eine Änderung {v}-mal durch die Queue, bevor sie landet.', wants: 'Arion will 1,25, später 1,1: fast jede Änderung im ersten Anlauf.',
      learn: 'Queue-Läufe pro PR, Mittel {v} · p90 {p90}. Jeder zusätzliche Lauf heißt: Die Änderung kam zurück, meist wegen eines Flakes oder eines Konflikts.', src: 'Gemessen über GitHub' },
    review_time: { name: 'Wie lange ein Review dauert', say: 'Ein Review dauert etwa {v}, und {k} von {n} verlangen Änderungen.', sayAlt: 'Ein Review dauert etwa {v}.', wants: 'Arion will 10 min, später 8, und Änderungen in höchstens 1 von 4.',
      learn: `Review-Dauer (erste Runde), p50 {p50} · p90 {p90}: Review angefordert ${TO} Urteil gesetzt. Anteil „Änderungen“: {k} von {n}. Teilweise: Es zählen nur PRs mit aeon/review-Status.`,
      src: 'Aus Review-Status auf GitHub', part: 'nur Reviews mit Status zählen' },
    merge_rounds_model_share: { name: 'Konflikte per Skript gelöst', say: 'Kollidiert eine Änderung mit einem neueren main, löste ein Skript das {k}-mal von {n}; den Rest machte ein Agent.', wants: 'Arion will 8 von 10 per Skript.',
      learn: 'Merge-Runden, Modell-Anteil {m} ({km} von {n}). Eine Merge-Runde ist ein PR, der mit einem weitergezogenen main kollidiert; per Skript heißt: Der Merge-Treiber hat sie gelöst.', learnPart: ' Teilweise: Meldungen seit {d}.',
      src: 'Vom Merge-Tooling gemeldet', part: 'Meldungen seit {d}' },
    release_queue_to_live: { name: 'Vom Release bis live', say: 'Release {r} brauchte etwa {v} von der Queue bis live auf csb1.', sayAlt: 'Ein Release braucht etwa {v} von der Queue bis live auf csb1 ({n} Releases).', wants: 'Arion will etwa 61 min, später 54, plus die Wartezeit auf eine Person.',
      learn: `Release, Merge-Queue ${TO} live auf csb1, p50 {p50} über {n}.`, learnPart: ' Teilweise: Das Release-Tooling meldet seit {d}.',
      src: 'Vom Release-Tooling gemeldet', part: 'gemeldet seit {d}' },
    nightly_green: { name: 'Voller Testlauf jede Nacht', say: 'Der volle Testlauf scheiterte in allen {n} Nächten, seit er am {d} startete.', sayAlt: 'Der volle Testlauf war in {k} von {n} Nächten mit Lauf grün.', wants: 'Arion will ihn jede Nacht grün.',
      learn: 'Nightly-Volllauf, {k} von {n} Nächten grün. Ein Urteil pro Nacht aus dem geplanten Volllauf; eine Nacht ohne Lauf heißt „kein Lauf“, nie rot.', src: 'Gemessen über GitHub' },
    time_to_first_green_commit: { name: 'Zeit, bis ein Commit grün ist', say: 'Ein Commit braucht etwa {v}, bis einer seiner Läufe grün ist.', wants: 'Arion hat dafür noch kein Ziel.',
      learn: 'Zeit bis zum ersten Grün pro Commit, p50 {p50} · p90 {p90}. {never} von {total} Commits wurden nie grün, {sup} davon, weil ein neuerer Commit des Branches sie ersetzt hat.', src: 'Gemessen über GitHub' },
    flaked_failures: { name: 'Läufe, die scheiterten und dann durchliefen', say: '{v} der ersten Versuche scheiterten und liefen bei einer Wiederholung desselben Commits durch; {suspect} weitere sind verdächtig.', wants: 'Arion will 2 % oder weniger.',
      learn: 'Bestätigt flackernde Läufe: Ein Lauf scheiterte und lief bei einem späteren Versuch desselben Laufs durch, also derselbe Commit und derselbe Workflow ({confirmed} von {n} ersten Versuchen, {v}). Verdächtige ({suspect}): Ein Lauf scheiterte auf einem Commit und der nächste Commit lief auf demselben Tree durch. Sie sind nicht bestätigt und nicht im Anteil.', src: 'Gemessen über GitHub' },
    queue_ejections: { name: 'Aus der Queue geworfene Änderungen', say: 'Etwa {v} von je 100 gemergten Änderungen flogen vorher aus der Merge-Queue, weil eine Pflichtprüfung scheiterte ({e} Läufe für {b} gemergte Änderungen).', wants: 'Arion will 25 oder weniger, später 10.',
      learn: 'Abgeleitete Auswürfe pro 100 gemergte PRs: {e} Merge-Queue-Läufe mit roter Pflichtprüfung für {b} gemergte PRs. Abgeleitet, weil die Queue-Ereignisse selbst den Läufen noch nicht zugeordnet sind.', src: 'Gemessen über GitHub' },
    queue_unclassified: { name: 'Zusätzliche Queue-Läufe, Ursache offen', say: 'Auf je 100 gemergte Änderungen kamen {v} zusätzliche Queue-Läufe, die nicht an einer gescheiterten Pflichtprüfung lagen ({e} Läufe für {b} gemergte Änderungen).', wants: 'Arion setzt ein Ziel, sobald die Ursachen geklärt sind.',
      learn: 'Queue-Läufe vor dem, der gemergt hat, die abgebrochen oder in den Pflichtprüfungen grün waren: {e} für {b} gemergte PRs. Ausfall eines Vorgängers, Umordnung und manuelles Entfernen lassen sich noch nicht unterscheiden.', src: 'Gemessen über GitHub' },
    runner_wait: { name: 'Warten auf einen Runner', say: 'Jeder zehnte Lauf wartet {v} oder länger auf einen Runner, gerechnet nach seinem langsamsten Job.', wants: 'Arion will 3 min, später 1.',
      learn: 'Längste Job-Wartezeit pro Lauf: p90 {p90}, p50 {p50}. Die längste Zeit, die ein Job eines Laufs zwischen Anlegen und Start wartete; übersprungene Jobs haben keine Wartezeit.', src: 'Gemessen über GitHub' },
    preflight_red_rate: { name: 'Vorab-Checks, die scheiterten', say: '{v} der Vorab-Checks vor dem Öffnen eines PR endeten rot ({n} Läufe).', wants: 'Arion hat dafür kein Ziel: Es steht neben den Zahlen zum ersten Versuch.',
      learn: 'Preflight-Rotanteil: die Preflight-Läufe auf dem genauen Commit, die der Builder vor dem Öffnen eines PR startet; {v} von {n} ersten Versuchen endeten rot. Sie zählen nie als CI-Grün.', src: 'Gemessen über GitHub' },
    review_audits: { name: 'Befunde der Review-Audits', say: 'Von einem zweiten Modell erneut geprüfte gemergte Änderungen: {n}, {high} mit hohem Befund, {medium} mittel, {low} niedrig, {clean} sauber.', sayAlt: 'In diesem Zeitraum wurde kein Review-Audit gemeldet.', wants: 'Befunde werden beobachtet, nicht gedeckelt.',
      learn: 'Jede Woche prüft ein Modell einer anderen Familie einige gemergte PRs erneut. Der schwerste Befund jeder Prüfung zählt hier.', learnPart: ' Teilweise: Audits werden seit {d} gemeldet.', src: 'Vom Audit-Tooling gemeldet', part: 'Meldungen seit {d}' },
    escaped_defects: { name: 'Fehler, die live gingen', say: 'In die Produktion gelangte Fehler: {n}, {high} hoch, {medium} mittel, {low} niedrig.', sayAlt: 'In diesem Zeitraum wurde kein entkommener Fehler erfasst.', wants: 'Arion will, dass diese Zahl fällt.',
      learn: 'Bug- oder Störungs-Tickets, die als verursacht durch einen gemergten PR oder ein Release verknüpft sind, und Rollout-Störungen von Releases (Ausfall zählt als hoch, beeinträchtigt als mittel). Rot auf main allein ist kein entkommener Fehler.', learnPart: ' Teilweise: Die Erfassung beginnt am {d}.', src: 'Gemeldete Verknüpfungen und Rollouts', part: 'erfasst seit {d}' },
  },
  releaseOne: '1 Release', releaseMany: '{n} Releases',
}

export const simpleText = (lang: DeliveryLanguage): SimpleText => lang === 'de' ? DE : EN
