// SPDX-License-Identifier: AGPL-3.0-only
// Words of the Delivery page (AEON-994 draft 5, section 7). English and German,
// impersonal; the page reads the shared app display language.
import type { DeliveryLanguage } from './delivery'

// The approved copy reads "start → end" and "PR opened → merged": the arrow is the word "to" in text, never an icon.
const TO = '→'

export type MetricTextKey = 'pr_ci_wall' | 'queue_run_wall' | 'first_attempt_green' | 'time_to_first_green' | 'pr_open_to_merged'
  | 'queue_runs_per_pr' | 'review_time' | 'merge_rounds_model_share' | 'release_queue_to_live' | 'nightly_green'
  // The Arion v5 readings (AEON-1016), after the ten numbers.
  | 'time_to_first_green_commit' | 'flaked_failures' | 'queue_ejections' | 'queue_unclassified' | 'runner_wait'
  | 'preflight_red_rate' | 'review_audits' | 'escaped_defects'
export interface MetricText { label: string; definition: string; target: string; line: string; count: string; one: string; many: string }

const EN = {
  title: 'Delivery',
  sub: 'How fast changes move from pull request to live, measured all the time against the Project Arion targets.',
  views: { numbers: 'Numbers', flow: 'Flow' }, viewsLabel: 'Delivery views',
  windowLabel: 'Chart window', days: 'days',
  level: { simple: 'Simple', expert: 'Expert' }, levelLabel: 'Level of detail',
  updated: 'Updated {t}', live: 'live',
  srcApp: ['GitHub App events', ' · live'], srcAppOff: ['GitHub App', ' · not receiving events'],
  srcBack: ['Backfill', ' from the GitHub API · back to {d}'], srcRun: ['Backfill running', ' · complete since {d}'], srcRunNone: ['Backfill running', ' · older days still loading'],
  srcNone: ['No backfill yet', ' · only events from now on'], srcTool: ['Reported by tooling', ' · merge rounds, releases'],
  nodataT: 'No delivery data yet.', nodataB: 'PAIMOS starts counting with the first pull request the GitHub App sees in {repo}. History is backfilled once from the GitHub API.',
  norepoT: 'No repository is linked yet.', norepoB: 'Someone who manages delivery for this project links its GitHub repository; history is then backfilled once from the GitHub API.',
  errT: 'Delivery numbers could not be loaded.', errB: 'Nothing on this page is stale: no old numbers are shown in place of new ones.', retry: 'Retry',
  prefErr: 'The window and level could not be saved. This choice stays on this page.', prefRetry: 'Save again',
  cap: 'Key numbers · last {w} days · change against the {w} days before',
  trends: 'Trends', perDay: 'One point per day', perWeek: 'One point per week', perMonth: 'One point per month', lastDays: 'last {w} days',
  lgP50: { day: 'p50 per day', week: 'p50 per week', month: 'p50 per month' }, lgBand: 'p50 to p90', lgTarget: 'Arion target', lgPartial: 'partial', lgNone: 'no data yet',
  partial: 'Partial', noData: 'No data yet', notLoaded: 'Not loaded', nothing: 'Nothing recorded', loading: 'Loading',
  better: 'better', worse: 'worse', same: 'steady', pts: 'pts',
  tNone: 'No data in the {w} days before', tLoading: 'History still loading: no comparison yet',
  covers: 'covers {k} of {n} {u}', units: { day: 'days', week: 'weeks', month: 'months' },
  infoFor: 'Definition of', why: 'Why partial', whyNone: 'Why no data yet', source: 'Source', window: 'Window', windowT: 'last {w} days; the change compares with the {w} days before', arion: 'Project Arion',
  chartOf: 'Chart of', keys: 'Arrow keys move through the points.', clip: 'p90 above the scale', upTo: 'up to',
  today: 'Today', thisWeek: 'This week', thisWk: 'this wk', weekOf: 'Week of', soFar: 'so far',
  green: 'Green', red: 'Red', noRun: 'No run', failed: 'failed', firstTry: 'green 1st try', required: 'required checks', changes: 'changes', changesShare: 'Share of “changes”, %',
  greenWord: 'green', byModel: 'by a model', mean: 'mean', of: 'of', nightsGreen: 'nights green', nightGreen: 'night green',
  requiredChecks: 'Required checks', changesVerdicts: '“changes” verdicts', scripted: 'scripted', solvedByModel: 'solved by a model', reported: 'reported',
  release: 'Release', releaseOne: 'release', releaseMany: 'releases', redRow: 'Red {n} in a row', greenRow: 'Green {n} in a row', withoutRun: '{n} nights without a run', withoutRunOne: '1 night without a run',
  targetGreen: 'Target green ≥ {v}', targetChanges: 'Target ≤ {v}',
  // The lines under a reading's number (AEON-1016): exact counts, never rounded back from a share.
  counts: {
    branches: '{n} went green · {never} never green', commits: '{n} went green · {never} never, {sup} superseded',
    flakes: '{c} confirmed · {s} suspect · {r} workflow rescues', firstAttempts: '{n} first attempts', preflights: '{n} preflight runs',
    ejections: '{e} ejections · {b} merged PRs', unclassified: '{e} runs · {b} merged PRs', audits: '{n} audited', defects: '{n} recorded',
    severity: '{high} high · {medium} medium · {low} low', severityClean: '{high} high · {medium} medium · {low} low · {clean} clean',
    inferred: 'Inferred from required checks', unclassifiedNote: 'Cause not classified yet', preflightNote: 'Not counted as CI green',
    auditNote: 'Highest finding of each audit', defectNote: 'Linked tickets and rollout incidents', runnerNote: 'Worst job of each run',
    nothingRecorded: 'None recorded', noneGreen: 'No branch went green',
  },
  unitRecorded: 'recorded', unitPerHundred: 'per 100 PRs', unitAudits: 'audits', unitDefects: 'defects', unitAuditOne: 'audit', unitDefectOne: 'defect',
  flowSub: 'What is moving right now, what it waits for and when it will be done. Replay any run, or race it against the target.',
  defsTitle: 'How these numbers are counted',
  defs: [
    ['First attempt vs. time to green', 'PR CI run measures one run’s first attempt. Time to first green counts from the first run to the first green one, with every re-run and fix in between.'],
    ['Wall time vs. queue delay', `Wall time is run start ${TO} run end. Waiting for a runner or a merge-queue slot happens before the start and is not in it; PR opened ${TO} merged includes all waiting.`],
    ['p50 and p90', 'p50 is the median: half were faster. p90: nine in ten were faster; it shows the slow tail.'],
    ['Partial and no data yet', 'Partial: the source covers only part of the window (backfill limit, a review status on only some PRs, reports that started recently). No data yet: nothing recorded, never shown as 0.'],
    ['Change vs. the window before', 'The last {w} days against the {w} days before. Within 10 % (3 points for shares) counts as about the same.'],
    ['Confirmed and suspect flakes', 'Confirmed needs the same case, the same commit, the same workflow revision and the same runner class. This release does not store that evidence, so the share is withheld, never shown as 0%. A later attempt of the same run that passes is a workflow rescue, listed beside the share and not inside it. Suspect: a run failed on a commit and the next commit passed on the very same tree. Suspects never enter the share.'],
    ['Required checks and queue readings', 'Required checks: only the checks the merge rule demands decide, so a run red only outside them is green. Inferred ejections and extra queue runs are counted per 100 merged PRs; their cause stays unclassified until the queue events are joined.'],
    ['Sources', 'GitHub App events (live), history backfilled once from the GitHub API, and facts reported by the merge, release and audit tooling.'],
  ] as [string, string][],
  sources: { gh: 'GitHub App + backfill', review: 'aeon/review status', merge: 'Merge tooling', release: 'Release tooling', nightly: '{wf} · GitHub App', jobs: 'GitHub jobs + backfill', preflight: 'ci-preflight · GitHub App', audit: 'Audit tooling', defects: 'Defects reported · rollouts' },
  metrics: {
    pr_ci_wall: { label: 'PR CI run (wall)', definition: `First attempt of each pull-request CI run: run started ${TO} run completed (wall clock), counted on the day the run was created. Runner wait before the start is not included; re-runs count in Time to first green.`, target: 'Target 10 min, then 7', line: `Target 10 ${TO} 7`, count: 'runs', one: 'run', many: 'runs' },
    queue_run_wall: { label: 'Merge-queue run', definition: `First attempt of each merge-queue CI run: started ${TO} completed. Waiting in the queue before the run starts is not included.`, target: 'Target 10 min, then 7', line: `Target 10 ${TO} 7`, count: 'queue runs', one: 'run', many: 'runs' },
    first_attempt_green: { label: 'Green on first try', definition: 'Share of first attempts of PR CI runs that ended green; cancelled runs (replaced by a newer push) are left out. Below it, the same runs counted the way the merge rule counts them: only the required checks decide, so a run red only outside them is green.', target: 'Target ≥ 70 %, then ≥ 80 %', line: 'Target ≥ 80 %', count: 'first attempts', one: 'run', many: 'runs' },
    time_to_first_green: { label: 'Time to first green (branch)', definition: `Per PR branch: first CI run created ${TO} first green run completed, including re-runs and fix pushes. Not the duration of one run. Branches that never went green are counted beside it, never as a time.`, target: 'Target p50 30 min, then 20', line: `Target 30 ${TO} 20`, count: 'PR branches', one: 'branch', many: 'branches' },
    pr_open_to_merged: { label: `PR opened ${TO} merged`, definition: `PR opened ${TO} PR merged, wall clock: review, fix rounds, queue waits and re-queues included.`, target: 'Target p50 80 min, then 60', line: `Target 80 ${TO} 60`, count: 'merged PRs', one: 'PR', many: 'PRs' },
    queue_runs_per_pr: { label: 'Queue runs per PR', definition: 'Average number of merge-queue runs a PR needs until it merges. 1.0 means every PR merged on its first queue run.', target: 'Target 1.25, then 1.1 runs per PR', line: `Target 1.25 ${TO} 1.1`, count: 'merged PRs', one: 'PR', many: 'PRs' },
    review_time: { label: 'Review time', definition: `First review round: review requested (aeon/review pending) ${TO} verdict posted. “Changes” share: verdicts that ask for changes. Only PRs with a review status count, so this number is always partial.`, target: 'Target 10 min, then 8; changes ≤ 40 %, then 25 %', line: `Target 10 ${TO} 8`, count: 'reviews', one: 'review', many: 'reviews' },
    merge_rounds_model_share: { label: 'Merge rounds', definition: 'A merge round is a PR that conflicts with a moved main. Scripted: the merge driver resolved it; model: an agent had to. Reported by the merge tooling; PAIMOS cannot see merge rounds by itself.', target: 'Target ≤ 20 % by a model', line: 'Target ≤ 20 %', count: 'merge rounds', one: 'merge round', many: 'merge rounds' },
    release_queue_to_live: { label: `Release ${TO} live`, definition: `Per release: the release PR enters the merge queue ${TO} the version is live on the production target, as reported by the release tooling. The wait for a person (W) is inside this time. PAIMOS cannot observe the host itself.`, target: 'Target ~61 min + W, then ~54 + W', line: `Target 61 ${TO} 54 + W`, count: 'releases', one: 'release', many: 'releases' },
    nightly_green: { label: 'Nightly full run', definition: 'One verdict per night: the scheduled full run’s last attempt. Green only on success. A night without a run shows as “no run”, never as red.', target: 'Target: green every night', line: '', count: 'nights', one: 'night', many: 'nights' },
    time_to_first_green_commit: { label: 'Time to first green (commit)', definition: `Per head commit of a PR branch: its first CI run created ${TO} its first green attempt completed, on that same commit. Commits that never went green are counted beside it, with how many a later commit on the branch superseded.`, target: 'No Arion target yet', line: '', count: 'commits', one: 'commit', many: 'commits' },
    flaked_failures: { label: 'Confirmed flaky runs', definition: 'The confirmed share needs the same case, the same commit, the same workflow revision and the same runner class, red then green. This release does not store case, revision or runner class, so the share is withheld and is never shown as 0%. A first attempt that failed and then passed on a later attempt of the same run is a workflow rescue, counted beside the share, not inside it. A suspect failed on a commit whose next commit passed on the very same tree. Suspects never enter the share.', target: 'Target ≤ 2 % of runs', line: 'Target ≤ 2 %', count: 'first attempts', one: 'run', many: 'runs' },
    queue_ejections: { label: 'Inferred ejections', definition: 'Merge-queue runs whose required check was red, per 100 merged PRs that had a queue run. Inferred: GitHub took such a PR out of the queue; the queue’s own events are not joined yet.', target: 'Target ≤ 25 per 100, then ≤ 10', line: `Target 25 ${TO} 10`, count: 'merged PRs', one: 'PR', many: 'PRs' },
    queue_unclassified: { label: 'Extra queue runs, cause unclassified', definition: 'Per 100 merged PRs: queue runs before the one that merged that were not red in a required check (cancelled, or green). Predecessor failure, reordering and manual removal cannot be told apart yet; queue event correlation (WP1.6) classifies them.', target: 'Target set after the causes are classified', line: '', count: 'merged PRs', one: 'PR', many: 'PRs' },
    runner_wait: { label: 'Runner wait, worst job', definition: `Per first attempt of a PR CI run: the longest wait of any job that ran, job created ${TO} job started. The big number is p90 across runs; p50 sits beside it. Skipped jobs have no wait.`, target: 'Target p90 ≤ 3 min, then 1', line: `Target 3 ${TO} 1`, count: 'first attempts', one: 'run', many: 'runs' },
    preflight_red_rate: { label: 'Preflight red rate', definition: 'Share of exact-commit preflight runs (first attempt) that ended red. Preflight runs before a PR opens; it is its own line and never counts as CI green.', target: 'No Arion target: shown beside first-try green', line: '', count: 'preflight runs', one: 'run', many: 'runs' },
    review_audits: { label: 'Review audit findings', definition: 'Merged PRs re-reviewed by a second model of another family, with the highest severity of each audit’s findings: clean, low, medium or high. Reported by the audit tooling; PAIMOS cannot see audits itself.', target: 'No target: findings are watched', line: '', count: 'audits', one: 'audit', many: 'audits' },
    escaped_defects: { label: 'Escaped defects', definition: 'Bug or incident tickets linked as caused by a merged PR or a release, plus rollout incidents of releases (down counts as high, degraded as medium). Main-branch red is not a defect that escaped.', target: 'Target: falling', line: '', count: 'defects', one: 'defect', many: 'defects' },
  } satisfies Record<MetricTextKey, MetricText>,
}
export type DeliveryText = typeof EN

const DE: DeliveryText = {
  title: 'Lieferung',
  sub: 'Wie schnell Änderungen vom Pull Request bis live kommen, laufend gemessen an den Zielen von Project Arion.',
  views: { numbers: 'Zahlen', flow: 'Ablauf' }, viewsLabel: 'Ansichten der Lieferung',
  windowLabel: 'Zeitraum der Diagramme', days: 'Tage',
  level: { simple: 'Einfach', expert: 'Experte' }, levelLabel: 'Detailgrad',
  updated: 'Aktualisiert {t}', live: 'live',
  srcApp: ['GitHub-App-Ereignisse', ' · live'], srcAppOff: ['GitHub-App', ' · empfängt keine Ereignisse'],
  srcBack: ['Nachgeladen', ' aus der GitHub-API · bis {d}'], srcRun: ['Nachladen läuft', ' · vollständig seit {d}'], srcRunNone: ['Nachladen läuft', ' · ältere Tage laden noch'],
  srcNone: ['Noch nicht nachgeladen', ' · nur Ereignisse ab jetzt'], srcTool: ['Vom Tooling gemeldet', ' · Merge-Runden, Releases'],
  nodataT: 'Noch keine Lieferdaten.', nodataB: 'PAIMOS zählt ab dem ersten Pull Request, den die GitHub-App in {repo} sieht. Die Historie wird einmal aus der GitHub-API nachgeladen.',
  norepoT: 'Noch kein Repository verknüpft.', norepoB: 'Wer die Lieferung dieses Projekts verwaltet, verknüpft sein GitHub-Repository; die Historie wird dann einmal aus der GitHub-API nachgeladen.',
  errT: 'Die Lieferzahlen konnten nicht geladen werden.', errB: 'Nichts hier ist veraltet: Alte Zahlen werden nicht anstelle neuer gezeigt.', retry: 'Erneut versuchen',
  prefErr: 'Zeitraum und Detailgrad konnten nicht gespeichert werden. Die Auswahl bleibt auf dieser Seite.', prefRetry: 'Erneut speichern',
  cap: 'Kennzahlen · letzte {w} Tage · Änderung gegenüber den {w} Tagen davor',
  trends: 'Verlauf', perDay: 'Ein Punkt pro Tag', perWeek: 'Ein Punkt pro Woche', perMonth: 'Ein Punkt pro Monat', lastDays: 'letzte {w} Tage',
  lgP50: { day: 'p50 pro Tag', week: 'p50 pro Woche', month: 'p50 pro Monat' }, lgBand: 'p50 bis p90', lgTarget: 'Arion-Ziel', lgPartial: 'teilweise', lgNone: 'noch keine Daten',
  partial: 'Teilweise', noData: 'Noch keine Daten', notLoaded: 'Nicht geladen', nothing: 'Nichts erfasst', loading: 'Lädt',
  better: 'besser', worse: 'schlechter', same: 'stabil', pts: 'Pp.',
  tNone: 'Keine Daten in den {w} Tagen davor', tLoading: 'Historie lädt noch: noch kein Vergleich',
  covers: 'deckt {k} von {n} {u} ab', units: { day: 'Tagen', week: 'Wochen', month: 'Monaten' },
  infoFor: 'Definition von', why: 'Warum teilweise', whyNone: 'Warum noch keine Daten', source: 'Quelle', window: 'Zeitraum', windowT: 'letzte {w} Tage; die Änderung vergleicht mit den {w} Tagen davor', arion: 'Project Arion',
  chartOf: 'Diagramm von', keys: 'Pfeiltasten wechseln den Punkt.', clip: 'p90 über der Skala', upTo: 'bis',
  today: 'Heute', thisWeek: 'Diese Woche', thisWk: 'diese W.', weekOf: 'Woche ab', soFar: 'bisher',
  green: 'Grün', red: 'Rot', noRun: 'Kein Lauf', failed: 'gescheitert', firstTry: 'grün beim 1. Versuch', required: 'Pflichtprüfungen', changes: 'Änderungen', changesShare: 'Anteil „Änderungen“, %',
  greenWord: 'grün', byModel: 'durch ein Modell', mean: 'Mittel', of: 'von', nightsGreen: 'Nächte grün', nightGreen: 'Nacht grün',
  requiredChecks: 'Pflichtprüfungen', changesVerdicts: '„Änderungen“', scripted: 'per Skript', solvedByModel: 'durch ein Modell gelöst', reported: 'gemeldet',
  release: 'Release', releaseOne: 'Release', releaseMany: 'Releases', redRow: '{n} Nächte in Folge rot', greenRow: '{n} Nächte in Folge grün', withoutRun: '{n} Nächte ohne Lauf', withoutRunOne: '1 Nacht ohne Lauf',
  targetGreen: 'Ziel grün ≥ {v}', targetChanges: 'Ziel ≤ {v}',
  counts: {
    branches: '{n} wurden grün · {never} nie grün', commits: '{n} wurden grün · {never} nie, {sup} überholt',
    flakes: '{c} bestätigt · {s} verdächtig · {r} Workflow-Rettungen', firstAttempts: '{n} erste Versuche', preflights: '{n} Preflight-Läufe',
    ejections: '{e} Auswürfe · {b} gemergte PRs', unclassified: '{e} Läufe · {b} gemergte PRs', audits: '{n} geprüft', defects: '{n} erfasst',
    severity: '{high} hoch · {medium} mittel · {low} niedrig', severityClean: '{high} hoch · {medium} mittel · {low} niedrig · {clean} sauber',
    inferred: 'Aus den Pflichtprüfungen abgeleitet', unclassifiedNote: 'Ursache noch nicht eingeordnet', preflightNote: 'Zählt nicht als CI-Grün',
    auditNote: 'Schwerster Befund je Prüfung', defectNote: 'Verknüpfte Tickets und Rollout-Störungen', runnerNote: 'Langsamster Job je Lauf',
    nothingRecorded: 'Nichts erfasst', noneGreen: 'Kein Branch wurde grün',
  },
  unitRecorded: 'erfasst', unitPerHundred: 'pro 100 PRs', unitAudits: 'Prüfungen', unitDefects: 'Fehler', unitAuditOne: 'Prüfung', unitDefectOne: 'Fehler',
  flowSub: 'Was gerade läuft, worauf es wartet und wann es fertig ist. Jeden Lauf wiedergeben oder gegen das Ziel antreten lassen.',
  defsTitle: 'So werden die Zahlen gezählt',
  defs: [
    ['Erster Versuch vs. Zeit bis Grün', 'PR-CI-Lauf misst den ersten Versuch eines Laufs. Zeit bis erstes Grün zählt vom ersten Lauf bis zum ersten grünen, mit allen Wiederholungen und Fixes dazwischen.'],
    ['Wanduhrzeit vs. Wartezeit', `Wanduhrzeit ist Start ${TO} Ende eines Laufs. Das Warten auf einen Runner oder einen Platz in der Merge-Queue liegt davor und zählt nicht; „PR geöffnet ${TO} gemergt“ enthält alles Warten.`],
    ['p50 und p90', 'p50 ist der Median: Die Hälfte war schneller. p90: Neun von zehn waren schneller; das zeigt die langsamen Ausreißer.'],
    ['Teilweise und noch keine Daten', 'Teilweise: Die Quelle deckt nur einen Teil des Zeitraums ab (Nachlade-Grenze, Review-Status nur auf manchen PRs, Meldungen erst seit Kurzem). Noch keine Daten: nichts erfasst, nie als 0 gezeigt.'],
    ['Änderung ggü. dem Zeitraum davor', 'Die letzten {w} Tage gegen die {w} Tage davor. Weniger als 10 % (bei Anteilen 3 Pp.) gilt als etwa gleich.'],
    ['Bestätigte und verdächtige Flakes', 'Bestätigt verlangt denselben Fall, denselben Commit, dieselbe Workflow-Revision und dieselbe Runner-Klasse. Diese Fassung speichert diese Belege nicht, daher bleibt der Anteil aus, nie als 0 % gezeigt. Ein späterer Versuch desselben Laufs, der durchläuft, ist eine Workflow-Rettung und steht neben dem Anteil, nicht darin. Verdächtig: Ein Lauf scheiterte auf einem Commit und der nächste Commit lief auf demselben Tree durch. Verdächtige zählen nie im Anteil.'],
    ['Pflichtprüfungen und Queue-Werte', 'Pflichtprüfungen: Nur die Prüfungen, die die Merge-Regel verlangt, entscheiden; ein Lauf, der nur außerhalb davon rot ist, gilt als grün. Abgeleitete Auswürfe und zusätzliche Queue-Läufe zählen pro 100 gemergte PRs; ihre Ursache bleibt offen, bis die Queue-Ereignisse zugeordnet sind.'],
    ['Quellen', 'GitHub-App-Ereignisse (live), einmal aus der GitHub-API nachgeladene Historie und Fakten, die Merge-, Release- und Audit-Tooling melden.'],
  ],
  sources: { gh: 'GitHub-App + Nachladen', review: 'aeon/review-Status', merge: 'Merge-Tooling', release: 'Release-Tooling', nightly: '{wf} · GitHub-App', jobs: 'GitHub-Jobs + Nachladen', preflight: 'ci-preflight · GitHub-App', audit: 'Audit-Tooling', defects: 'Gemeldete Fehler · Rollouts' },
  metrics: {
    pr_ci_wall: { label: 'PR-CI-Lauf (Wall)', definition: `Erster Versuch jedes PR-CI-Laufs: Start ${TO} Ende (Wanduhrzeit), gezählt am Tag, an dem der Lauf angelegt wurde. Die Wartezeit auf einen Runner vor dem Start zählt nicht; Wiederholungen zählen bei „Zeit bis erstes Grün“.`, target: 'Ziel 10 min, danach 7', line: `Ziel 10 ${TO} 7`, count: 'Läufe', one: 'Lauf', many: 'Läufe' },
    queue_run_wall: { label: 'Merge-Queue-Lauf', definition: `Erster Versuch jedes Merge-Queue-Laufs: Start ${TO} Ende. Die Wartezeit in der Queue vor dem Start zählt nicht.`, target: 'Ziel 10 min, danach 7', line: `Ziel 10 ${TO} 7`, count: 'Queue-Läufe', one: 'Lauf', many: 'Läufe' },
    first_attempt_green: { label: 'Grün beim 1. Versuch', definition: 'Anteil der ersten Versuche von PR-CI-Läufen, die grün enden; abgebrochene Läufe (durch einen neueren Push ersetzt) zählen nicht. Darunter dieselben Läufe so gezählt, wie die Merge-Regel zählt: Nur die Pflichtprüfungen entscheiden, ein Lauf, der nur außerhalb davon rot ist, gilt als grün.', target: 'Ziel ≥ 70 %, danach ≥ 80 %', line: 'Ziel ≥ 80 %', count: 'erste Versuche', one: 'Lauf', many: 'Läufe' },
    time_to_first_green: { label: 'Zeit bis erstes Grün (Branch)', definition: `Pro PR-Branch: erster CI-Lauf angelegt ${TO} erster grüner Lauf fertig, inklusive Wiederholungen und Fix-Pushes. Nicht die Dauer eines Laufs. Branches, die nie grün wurden, zählen daneben, nie als Zeit.`, target: 'Ziel p50 30 min, danach 20', line: `Ziel 30 ${TO} 20`, count: 'PR-Branches', one: 'Branch', many: 'Branches' },
    pr_open_to_merged: { label: `PR geöffnet ${TO} gemergt`, definition: `PR geöffnet ${TO} PR gemergt, Wanduhrzeit: Review, Fix-Runden, Queue-Wartezeit und erneutes Einreihen inklusive.`, target: 'Ziel p50 80 min, danach 60', line: `Ziel 80 ${TO} 60`, count: 'gemergte PRs', one: 'PR', many: 'PRs' },
    queue_runs_per_pr: { label: 'Queue-Läufe pro PR', definition: 'Durchschnittliche Zahl der Merge-Queue-Läufe, bis ein PR gemergt ist. 1,0 heißt: Jeder PR ging im ersten Queue-Lauf durch.', target: 'Ziel 1,25, danach 1,1 Läufe pro PR', line: `Ziel 1,25 ${TO} 1,1`, count: 'gemergte PRs', one: 'PR', many: 'PRs' },
    review_time: { label: 'Review-Dauer', definition: `Erste Review-Runde: Review angefordert (aeon/review pending) ${TO} Urteil gesetzt. Anteil „Änderungen“: Urteile, die Änderungen verlangen. Es zählen nur PRs mit Review-Status, daher immer teilweise.`, target: 'Ziel 10 min, danach 8; Änderungen ≤ 40 %, danach 25 %', line: `Ziel 10 ${TO} 8`, count: 'Reviews', one: 'Review', many: 'Reviews' },
    merge_rounds_model_share: { label: 'Merge-Runden', definition: 'Eine Merge-Runde ist ein PR, der mit einem weitergezogenen main kollidiert. Per Skript: Der Merge-Treiber hat sie gelöst; Modell: Ein Agent musste ran. Gemeldet vom Merge-Tooling; PAIMOS sieht Merge-Runden nicht selbst.', target: 'Ziel ≤ 20 % durch Modell', line: 'Ziel ≤ 20 %', count: 'Merge-Runden', one: 'Merge-Runde', many: 'Merge-Runden' },
    release_queue_to_live: { label: `Release ${TO} live`, definition: `Pro Release: Der Release-PR kommt in die Merge-Queue ${TO} die Version läuft live auf dem Produktionsziel, gemeldet vom Release-Tooling. Die Wartezeit auf eine Person (W) steckt in dieser Zeit. PAIMOS kann den Host nicht selbst beobachten.`, target: 'Ziel ~61 min + W, danach ~54 + W', line: `Ziel 61 ${TO} 54 + W`, count: 'Releases', one: 'Release', many: 'Releases' },
    nightly_green: { label: 'Nightly-Volllauf', definition: 'Ein Urteil pro Nacht: der letzte Versuch des geplanten Volllaufs. Grün nur bei Erfolg. Eine Nacht ohne Lauf heißt „kein Lauf“, nie rot.', target: 'Ziel: jede Nacht grün', line: '', count: 'Nächte', one: 'Nacht', many: 'Nächte' },
    time_to_first_green_commit: { label: 'Zeit bis erstes Grün (Commit)', definition: `Pro Head-Commit eines PR-Branches: erster CI-Lauf angelegt ${TO} erster grüner Versuch fertig, auf demselben Commit. Commits, die nie grün wurden, zählen daneben, samt der Zahl derer, die ein späterer Commit des Branches überholt hat.`, target: 'Noch kein Arion-Ziel', line: '', count: 'Commits', one: 'Commit', many: 'Commits' },
    flaked_failures: { label: 'Bestätigt flackernde Läufe', definition: 'Der bestätigte Anteil verlangt denselben Fall, denselben Commit, dieselbe Workflow-Revision und dieselbe Runner-Klasse, erst rot, dann grün. Diese Fassung speichert Fall, Revision und Runner-Klasse nicht, daher bleibt der Anteil aus und wird nie als 0 % gezeigt. Ein erster Versuch, der scheiterte und bei einem späteren Versuch desselben Laufs durchlief, ist eine Workflow-Rettung, gezählt neben dem Anteil, nicht darin. Ein Verdächtiger scheiterte auf einem Commit, dessen nächster Commit auf demselben Tree durchlief. Verdächtige zählen nie im Anteil.', target: 'Ziel ≤ 2 % der Läufe', line: 'Ziel ≤ 2 %', count: 'erste Versuche', one: 'Lauf', many: 'Läufe' },
    queue_ejections: { label: 'Abgeleitete Auswürfe', definition: 'Merge-Queue-Läufe, deren Pflichtprüfung rot war, pro 100 gemergte PRs mit Queue-Lauf. Abgeleitet: GitHub hat so einen PR aus der Queue genommen; die Queue-Ereignisse selbst sind noch nicht zugeordnet.', target: 'Ziel ≤ 25 pro 100, danach ≤ 10', line: `Ziel 25 ${TO} 10`, count: 'gemergte PRs', one: 'PR', many: 'PRs' },
    queue_unclassified: { label: 'Zusätzliche Queue-Läufe, Ursache offen', definition: 'Pro 100 gemergte PRs: Queue-Läufe vor dem, der gemergt hat, die nicht in einer Pflichtprüfung rot waren (abgebrochen oder grün). Ausfall eines Vorgängers, Umordnung und manuelles Entfernen lassen sich noch nicht unterscheiden; die Queue-Ereignis-Zuordnung (WP1.6) ordnet sie ein.', target: 'Ziel folgt, wenn die Ursachen eingeordnet sind', line: '', count: 'gemergte PRs', one: 'PR', many: 'PRs' },
    runner_wait: { label: 'Runner-Wartezeit, langsamster Job', definition: `Pro ersten Versuch eines PR-CI-Laufs: die längste Wartezeit eines Jobs, der lief, Job angelegt ${TO} Job gestartet. Die große Zahl ist p90 über die Läufe; p50 steht daneben. Übersprungene Jobs haben keine Wartezeit.`, target: 'Ziel p90 ≤ 3 min, danach 1', line: `Ziel 3 ${TO} 1`, count: 'erste Versuche', one: 'Lauf', many: 'Läufe' },
    preflight_red_rate: { label: 'Preflight-Rotanteil', definition: 'Anteil der Preflight-Läufe auf dem genauen Commit (erster Versuch), die rot endeten. Das Preflight läuft, bevor ein PR geöffnet wird; es hat seine eigene Zeile und zählt nie als CI-Grün.', target: 'Kein Arion-Ziel: steht neben Grün beim 1. Versuch', line: '', count: 'Preflight-Läufe', one: 'Lauf', many: 'Läufe' },
    review_audits: { label: 'Befunde der Review-Audits', definition: 'Gemergte PRs, die ein zweites Modell einer anderen Familie erneut geprüft hat, mit dem schwersten Befund je Prüfung: sauber, niedrig, mittel oder hoch. Gemeldet vom Audit-Tooling; PAIMOS sieht Audits nicht selbst.', target: 'Kein Ziel: Befunde werden beobachtet', line: '', count: 'Prüfungen', one: 'Prüfung', many: 'Prüfungen' },
    escaped_defects: { label: 'Entkommene Fehler', definition: 'Bug- oder Störungs-Tickets, die als verursacht durch einen gemergten PR oder ein Release verknüpft sind, plus Rollout-Störungen von Releases (Ausfall zählt als hoch, beeinträchtigt als mittel). Rot auf main ist kein entkommener Fehler.', target: 'Ziel: fallend', line: '', count: 'Fehler', one: 'Fehler', many: 'Fehler' },
  },
}

export const deliveryText = (lang: DeliveryLanguage): DeliveryText => lang === 'de' ? DE : EN
/** Replaces {name} placeholders. */
export function fill(text: string, values: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (whole, name: string) => name in values ? String(values[name]) : whole)
}
