// SPDX-License-Identifier: AGPL-3.0-only
// EN/DE pairs from the approved AEON-854 HTML. Tenant-authored kind wording
// stays exactly as stored; it is never replaced with the mock's example data.
// Kinds of work names Settings › Models in the lead and links there. openModels
// is the control on that link.
export const kindsCopy = {
  title: ['Kinds of work', 'Arten von Arbeit'], summary: ['What each column means', 'Was jede Spalte bedeutet'],
  intro: ['Every ticket has one kind of work, such as UI design or Backend build. It tells people and agents what the work needs, and which models take it on. Admins define the kinds; everyone can read them.', 'Jedes Ticket hat eine Art von Arbeit, etwa UI-Design oder Backend-Build. Sie sagt Menschen und Agenten, was die Arbeit braucht und welche Modelle sie übernehmen. Admins legen die Arten fest; alle können sie lesen.'],
  introRead: ['Every ticket has one kind of work, such as UI design or Backend build. It tells people and agents what the work needs, and which models take it on. Admins define the kinds; you can read them.', 'Jedes Ticket hat eine Art von Arbeit, etwa UI-Design oder Backend-Build. Sie sagt Menschen und Agenten, was die Arbeit braucht und welche Modelle sie übernehmen. Admins legen die Arten fest; Sie können sie lesen.'],
  lead: ['Each kind has a plain sentence and examples, so people and agents file a ticket the same way, and says how PAIMOS recognises it. Settings › Models picks a model for each kind, with one column per kind in this order; Everything else is always last.', 'Jede Art hat einen klaren Satz und Beispiele, damit Menschen und Agenten ein Ticket gleich einordnen, und sagt, woran PAIMOS sie erkennt. Einstellungen › Modelle wählt das Modell je Art, mit einer Spalte pro Art in dieser Reihenfolge; Alles andere steht immer am Ende.'],
  openModels: ['Open Models', 'Modelle öffnen'], edit: ['Edit', 'Bearbeiten'], archive: ['Archive', 'Archivieren'], restore: ['Restore', 'Wiederherstellen'], archived: ['Archived:', 'Archiviert:'], builtIn: ['Built in', 'Eingebaut'], systemHint: ['A system kind PAIMOS needs; it can’t be archived.', 'Eine Systemart, die PAIMOS braucht; sie kann nicht archiviert werden.'],
  example: ['For example', 'Zum Beispiel'], noExamples: ['No examples yet', 'Noch keine Beispiele'], recognition: ['How PAIMOS recognises it', 'Woran PAIMOS sie erkennt'], area: ['Ticket area', 'Ticket-Bereich'], labels: ['Labels', 'Labels'], labelWord: ['labels', 'Labels'], otherRecognition: ['and every kind without its own column', 'und jede Art ohne eigene Spalte'],
  newKind: ['New kind of work', 'Neue Art von Arbeit'], shortName: ['Short name', 'Kurzer Name'], nameHint: ['One line on the board, 40 characters', 'Eine Zeile auf dem Board, 40 Zeichen'], sentence: ['One plain sentence', 'Ein klarer Satz'], sentenceHint: ['Unambiguous for a first-time reader and for an agent, 120 characters', 'Eindeutig für Erstleser und für Agenten, 120 Zeichen'], examples: ['Two or three examples', 'Zwei oder drei Beispiele'], examplesHint: ['One per line', 'Eines pro Zeile'], areas: ['Ticket area values', 'Werte für Ticket-Bereich'], cancel: ['Cancel', 'Abbrechen'], create: ['Create', 'Anlegen'], save: ['Save', 'Speichern'],
  situations: ['Situations', 'Situationen'], situationsLead: ['PAIMOS defines these; admins set the limits. In Expert, Models orders models per situation.', 'PAIMOS legt diese fest; Admins setzen die Grenzen. Im Expertenmodus ordnet Modelle die Modelle je Situation.'],
  first: ['First build', 'Erster Build'], firstDefinition: ['The agent builds the ticket for the first time.', 'Der Agent baut das Ticket zum ersten Mal.'], small: ['Small work:', 'Kleine Arbeit:'], hours: ['h or less', 'h oder weniger'], lessThinking: ['· thinks one step less', '· denkt eine Stufe weniger'], fix: ['Fix rounds', 'Korrekturrunden'], fixHint: ['How many rounds: set under Stuck.', 'Wie viele Runden: unter Festgefahren festgelegt.'], stuck: ['Stuck', 'Festgefahren'], stuckAfter: ['Stuck after', 'Festgefahren nach'], rounds: ['fix rounds', 'Korrekturrunden'],
  review: ['Review gate', 'Prüf-Gate'], reviewDefinition: ['A model of another family checks finished work before it merges.', 'Ein Modell einer anderen Familie prüft fertige Arbeit, bevor sie gemergt wird.'], reviewHint: ['Who reviews: the three Review columns on Models. The cross-family rule lives in Policies.', 'Wer prüft: die drei Prüfspalten unter Modelle. Die modellübergreifende Regel steht in Richtlinien.'], concept: ['Concept on request', 'Konzept auf Anfrage'], conceptDefinition: ['Someone asks for a concept; PAIMOS never writes one on its own.', 'Jemand bittet um ein Konzept; PAIMOS schreibt nie von sich aus eines.'], conceptHint: ['Who writes it: the Concepts column on Models.', 'Wer es schreibt: die Spalte Konzepte unter Modelle.'],
  undo: ['Undo', 'Rückgängig'], loading: ['Loading…', 'Laden…'], retry: ['Try again', 'Erneut versuchen'],
  loadError: ['Kinds of work could not be loaded.', 'Arten von Arbeit konnten nicht geladen werden.'], limitsError: ['Situation limits could not be loaded.', 'Situationsgrenzen konnten nicht geladen werden.'], failed: ['The change could not be saved. Please try again.', 'Die Änderung konnte nicht gespeichert werden. Erneut versuchen.'], stale: ['This changed elsewhere. Reload before saving.', 'Dies wurde an anderer Stelle geändert. Vor dem Speichern neu laden.'], reload: ['Reload', 'Neu laden'],
  invalid: ['Use a name (up to 40 characters), a sentence (up to 120), up to 3 examples (120 each) and up to 32 distinct labels (48 each).', 'Einen Namen (bis 40 Zeichen), einen Satz (bis 120), bis zu 3 Beispiele (je 120) und bis zu 32 verschiedene Labels (je 48) verwenden.'],
  invalidLimit: ['Use whole hours from 1 to 8 and fix rounds from 1 to 6.', 'Ganze Stunden von 1 bis 8 und Korrekturrunden von 1 bis 6 verwenden.'],
  truncated: ['Only part of the kinds list could be loaded. Reordering is unavailable until the complete list is loaded.', 'Nur ein Teil der Arten konnte geladen werden. Die Reihenfolge kann erst mit der vollständigen Liste geändert werden.'], empty: ['No kinds of work yet.', 'Noch keine Arten von Arbeit.'],
  generatedArea: ['Assigned when created', 'Wird beim Anlegen vergeben'], areaHint: ['The ticket area value stays the same when its words change.', 'Der Ticket-Bereich bleibt beim Ändern der Texte gleich.'], undone: ['Change undone.', 'Änderung rückgängig gemacht.'],
} as const
export type KindsText = (key: keyof typeof kindsCopy) => string
export const textForKinds = (german: boolean): KindsText => key => kindsCopy[key][german ? 1 : 0]

// Shared by Kinds of work and the Expert picker; limits come from the server.
export function situationDefinition(situation: 'first' | 'fix' | 'stuck', rounds: number, german: boolean) {
  if (situation === 'first') return textForKinds(german)('firstDefinition')
  if (situation === 'fix') return german ? `Runden 1 bis ${rounds}: Der Agent behebt, was eine Prüfung gefunden hat.` : `Rounds 1 to ${rounds}: the agent fixes what a review found.`
  return german ? `Nach ${rounds} Korrekturrunden scheitert die Prüfung noch; eine andere Modellfamilie übernimmt.` : `After ${rounds} fix rounds review still fails; another model family takes over.`
}
