#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Regenerate pinned Unicode guard data; runtime and normal builds are offline.
Run from the repository root: python3 internal/unicodeguard/unicodegen/generate.py
UTS #39 is supplemented by UnicodeData's named Latin SMALL CAPITAL letters:
UTS #39 alone does not map all of these to their ordinary Latin forms (e.g. Q).
No hand-maintained codepoint exceptions are used.
"""
import hashlib
import json
from pathlib import Path
import re
import urllib.request

VERSION = '17.0.0'
SOURCES = {
    'confusables': ('security/confusables.txt', '091c7f82fc39ef208faf8f94d29c244de99254675e09de163160c810d13ef22a'),
    'derived': ('ucd/DerivedCoreProperties.txt', '24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08'),
    'names': ('ucd/UnicodeData.txt', '2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c'),
}


def read(name):
    suffix, digest = SOURCES[name]
    raw = urllib.request.urlopen(f'https://www.unicode.org/Public/{VERSION}/{suffix}', timeout=60).read()
    if hashlib.sha256(raw).hexdigest() != digest:
        raise ValueError(f'{name}: pinned Unicode SHA-256 mismatch')
    return raw.decode('utf-8')


def main():
    mappings = {}
    for line in read('confusables').splitlines():
        parts = line.split('#', 1)[0].strip().split(';')
        if len(parts) < 2:
            continue
        source = parts[0].split()
        assert len(source) == 1, 'UTS #39 source must be one codepoint'
        mappings[int(source[0], 16)] = ''.join(chr(int(c, 16)) for c in parts[1].split())
    ignored = []
    for line in read('derived').splitlines():
        parts = line.split('#', 1)[0].strip().split(';')
        if len(parts) < 2 or parts[1].strip() != 'Default_Ignorable_Code_Point':
            continue
        bounds = parts[0].strip().split('..')
        ignored.append((int(bounds[0], 16), int(bounds[-1], 16)))
    capitals = {}
    for line in read('names').splitlines():
        fields = line.split(';')
        match = re.fullmatch(r'LATIN LETTER SMALL CAPITAL ([A-Z])', fields[1])
        if match:
            capitals[int(fields[0], 16)] = match[1].lower()
    payload = json.dumps([mappings, ignored, capitals], ensure_ascii=True, separators=(',', ':')).encode()
    digest = hashlib.sha256(payload).hexdigest()
    # JSON surrogate pairs are not Go string escapes. Emit Go Unicode escapes directly.
    def quote(s):
        return '"' + ''.join(f'\\U{ord(c):08x}' for c in s) + '"'
    out = ['// SPDX-License-Identifier: Unicode-3.0',
           '// Code generated by unicodegen/generate.py; DO NOT EDIT.',
           '// Unicode 17.0.0. See unicodegen/LICENSE for the Unicode data license.',
           '// Source URLs and verified input hashes are pinned in the generator.',
           '', 'package unicodeguard', '',
           f'const Version = "{VERSION}"',
           f'const TableSHA256 = "{digest}"', '',
           'var Confusables = map[rune]string{']
    out += [f'0x{k:X}: {quote(v)},' for k, v in sorted(mappings.items())]
    out += ['}', '', 'var SmallCapitals = map[rune]string{']
    out += [f'0x{k:X}: {quote(v)},' for k, v in sorted(capitals.items())]
    out += ['}', '', 'var DefaultIgnorables = [...][2]rune{']
    out += [f'{{0x{lo:X}, 0x{hi:X}}},' for lo, hi in ignored]
    out += ['}', '']
    Path(__file__).resolve().parent.parent.joinpath('unicode_tables.go').write_text('\n'.join(out))
    print(f'Unicode {VERSION}: {len(mappings)} mappings, {len(capitals)} small capitals, {len(ignored)} ignorable ranges')


if __name__ == '__main__':
    main()
