// SPDX-License-Identifier: AGPL-3.0-only
// Knowledge (AEON-126): the project tab, an entry, edit mode with rename,
// conflict and undo, creation, knowledge across projects and the palette, on
// the mocked API, with axe in light and dark.
import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { fixtures, mockWork, watchErrors } from './work-fixtures'
import { knowledgeWorld, mockKnowledge, type KnowledgeMockOptions } from './knowledge-fixtures'

const entry = '/p/PHAROS/knowledge/runbook/deploy-release'
async function open(page: Page, path: string, options: KnowledgeMockOptions & { empty?: boolean } = {}) {
  await mockWork(page, fixtures(), { readOnly: options.readOnly })
  const world = knowledgeWorld({ empty: options.empty })
  const calls = await mockKnowledge(page, world, options)
  await page.goto(path)
  return { calls, world }
}
const rows = (page: Page) => page.locator('.k-row')
const groupTitles = (page: Page) => page.locator('.k-group h2')

test('Decision entries expose active and superseded history without generic mutation controls', async ({ page }) => {
  await page.setViewportSize({ width: 1100, height: 800 })
  const errors = watchErrors(page)
  await mockWork(page, fixtures())
  const world = knowledgeWorld()
  const base = world.entries[0]
  world.entries.push(
    { ...base, id: 'decision-new', key: 'DCS-2', type: 'decision', slug: 'decision-new', title: 'Use remote tests', body: 'Run the tests on the approved offload machine.', metadata: { decision_state: 'active', supersedes: 'decision-old' }, links: [] },
    { ...base, id: 'decision-old', key: 'DCS-1', type: 'decision', slug: 'decision-old', title: 'Earlier testing answer', body: 'The earlier approved answer.', status: 'archived', metadata: { decision_state: 'superseded', superseded_by: 'decision-new' }, links: [] },
  )
  const calls = await mockKnowledge(page, world)
  await page.goto('/p/PHAROS/knowledge?type=decision&view=entries')
  await expect(groupTitles(page)).toHaveText(['Decisions'])
  await expect(rows(page)).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'New decision', exact: true })).toHaveCount(0)
  await rows(page).first().click()
  await expect(page.locator('.e-note').filter({ hasText: 'Always answer' })).toContainText('Active; approved for reuse.')
  await expect(page.getByRole('button', { name: 'Edit', exact: true })).toHaveCount(0)
  await page.keyboard.press('e')
  await expect(page.getByRole('form', { name: /Edit decision/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'More actions' }).click()
  await expect(page.getByRole('menuitem', { name: /Delete|Archive/ })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.goto('/p/PHAROS/knowledge/decision/decision-old')
  await expect(page.locator('.e-body')).toContainText('The earlier approved answer.')
  await expect(page.locator('.e-note').filter({ hasText: 'Always answer' })).toContainText('Superseded; kept for its history.')
  await expect(page.locator('.e-note').filter({ hasText: 'Always answer' })).toContainText('decision-new')
  expect(calls.filter(call => ['POST', 'PATCH', 'DELETE'].includes(call.method))).toEqual([])
  expect(errors).toEqual([])
})

async function axe(page: Page) {
  const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
  expect(result.violations.map(v => `${v.id}: ${v.nodes.map(n => n.target.join(' ')).join(', ')}`)).toEqual([])
}

test('the Knowledge tab groups by kind, filters, searches the text and moves with keys', async ({ page }) => {
  // Below the docking width an entry opens on its own page (wide screens: knowledge-dock.spec.ts).
  await page.setViewportSize({ width: 1100, height: 800 })
  const errors = watchErrors(page)
  const { calls } = await open(page, '/p/PHAROS')
  await page.getByRole('tablist', { name: 'Project sections' }).getByRole('tab', { name: 'Knowledge' }).click()
  await expect(page).toHaveURL('/p/PHAROS/knowledge')
  await expect(groupTitles(page)).toHaveText(['Runbooks', 'Guidelines', 'Memory', 'External systems', 'Related projects'])
  // Archived entries wait until someone asks for them.
  await expect(rows(page)).toHaveCount(8)
  await expect(page.getByText('Recover a host from backup')).toHaveCount(0)
  const rail = page.getByRole('navigation', { name: 'Kinds of knowledge' })
  await expect(rail.getByRole('button', { name: /Runbooks/ })).toContainText('2')
  await expect(page.locator('.k-row').filter({ hasText: 'Hetzner API tokens' }).locator('.k-status')).toHaveText('Proposed')
  await expect(page.getByRole('navigation', { name: 'Breadcrumb' })).toContainText('Knowledge')

  // j and k move through every group, Enter opens, Esc comes back to the same row.
  await page.getByRole('heading', { name: 'Pharos' }).click()
  await page.keyboard.press('j')
  await expect(rows(page).first()).toHaveClass(/cursor/)
  await expect(rows(page).first()).toBeFocused()
  await page.keyboard.press('j')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL('/p/PHAROS/knowledge/runbook/rotate-host-keys')
  await expect(page.getByRole('heading', { level: 1, name: 'Rotate the fleet host keys' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page).toHaveURL('/p/PHAROS/knowledge')
  await expect(page.getByRole('heading', { level: 1, name: 'Rotate the fleet host keys' })).toBeHidden()
  await expect(rows(page).nth(1)).toHaveClass(/cursor/)

  // / searches titles, slugs and the text on the server; the match is marked.
  await page.keyboard.press('/')
  const search = page.getByRole('searchbox', { name: 'Search knowledge in Pharos' })
  await expect(search).toBeFocused()
  await search.fill('previous tag')
  await expect(page).toHaveURL('/p/PHAROS/knowledge?view=entries&q=previous+tag')
  await expect(rows(page)).toHaveCount(1)
  await expect(rows(page).first().locator('mark').first()).toBeVisible()
  expect(calls.some(call => call.query.get('q') === 'previous tag' && call.query.get('project_id') === 'p-pharos')).toBe(true)
  await search.fill('kubernetes')
  await expect(page.getByRole('heading', { name: 'Nothing matches “kubernetes”' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear the filters' }).click()
  await expect(rows(page)).toHaveCount(8)

  // Status and kind live in the address.
  await page.getByRole('button', { name: 'Status: Current' }).click()
  await page.getByRole('radio', { name: /Archived/ }).click()
  await expect(page).toHaveURL('/p/PHAROS/knowledge?view=entries&status=archived')
  await expect(rows(page)).toHaveText([/Recover a host from backup/])
  await page.getByRole('button', { name: 'Status: Archived' }).click()
  await page.getByRole('radio', { name: /All/ }).click()
  await rail.getByRole('button', { name: /Memory/ }).click()
  await expect(page).toHaveURL('/p/PHAROS/knowledge?view=entries&type=memory&status=all')
  await expect(groupTitles(page)).toHaveText(['Memory'])
  await page.getByRole('button', { name: 'Sort: Recently updated' }).click()
  await page.getByRole('radio', { name: 'Title' }).click()
  await expect(rows(page).locator('.k-title')).toHaveText(['Hetzner API tokens expire after 90 days', 'UI reviews happen on screenshots at five widths'])
  // An earlier kind address is the filtered tab.
  await page.goto('/p/PHAROS/knowledge/guideline')
  await expect(page).toHaveURL('/p/PHAROS/knowledge?type=guideline')
  await expect(groupTitles(page)).toHaveText(['Guidelines'])
  expect(errors).toEqual([])
})

test('an entry reads with a table of contents, anchors, how agents read it and what links here', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  const errors = watchErrors(page)
  await open(page, entry)
  // The body's own title heading is not repeated under the page title.
  await expect(page.getByRole('heading', { name: 'Deploy a release to production' })).toHaveCount(1)
  const toc = page.getByRole('navigation', { name: 'On this page' })
  await expect(toc.getByRole('link')).toHaveText(['Before you start', 'Build and pin the image', 'Roll out', 'Canary on csb1', 'The rest of the fleet', 'Roll back', 'After the deploy'])
  await toc.getByRole('link', { name: 'Roll back' }).click()
  await expect(page).toHaveURL(`${entry}#roll-back`)
  await expect(toc.getByRole('link', { name: 'Roll back' })).toHaveAttribute('aria-current', 'location')
  await page.getByRole('heading', { name: 'After the deploy' }).hover()
  await page.getByRole('link', { name: 'Copy a link to After the deploy' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('http://127.0.0.1:' + new URL(page.url()).port + `${entry}#after-the-deploy`)
  // Agents read it by kind, slug and project.
  const agents = page.getByRole('region', { name: 'Agents read this' })
  await expect(agents.locator('.k-command code')).toHaveText('paimos knowledge get runbook deploy-release --project PHAROS')
  await agents.getByRole('button', { name: 'Copy the agent command' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('paimos knowledge get runbook deploy-release --project PHAROS')
  await expect(page.getByRole('region', { name: 'Details' })).toContainText('Agents that run it')
  await expect(page.getByRole('region', { name: 'Details' })).toContainText('camy, kite')
  // Linked tickets and entries open where they live; j and k walk the list.
  const linked = page.getByRole('region', { name: /Linked/ })
  await expect(linked.getByRole('link')).toHaveText([/PHAROS-11/, /PHAROS-15/, /rotate-host-keys/])
  await page.keyboard.press('j')
  await expect(page).toHaveURL('/p/PHAROS/knowledge/runbook/rotate-host-keys')
  await expect(page.getByRole('heading', { level: 1, name: 'Rotate the fleet host keys' })).toBeVisible()
  await page.keyboard.press('k')
  await expect(page).toHaveURL('/p/PHAROS/knowledge/runbook/deploy-release')
  await linked.getByRole('link', { name: /PHAROS-11/ }).click()
  await expect(page).toHaveURL('/p/PHAROS/PHAROS-11?section=knowledge')
  expect(errors).toEqual([])
})

test('editing saves against the version read, warns before a rename and undoes it', async ({ page }) => {
  const { calls, world } = await open(page, entry)
  await expect(page.locator('.e-body')).toBeVisible()
  await page.keyboard.press('e')
  const form = page.getByRole('form', { name: 'Edit deploy-release' })
  await expect(form).toBeVisible()
  await expect(form.getByLabel('Title')).toBeFocused()
  const slug = form.getByLabel('Slug')
  await slug.fill('ship-a-release')
  await expect(page.getByRole('note').filter({ hasText: 'Agents look this entry up by its slug' })).toContainText('paimos knowledge get runbook deploy-release --project PHAROS')
  await slug.fill('Ship It')
  await expect(form.getByRole('alert')).toContainText('Use lower-case letters')
  await slug.fill('ship-a-release')
  await form.getByRole('radio', { name: 'Proposed' }).click()
  await page.getByRole('textbox', { name: 'Text, Markdown' }).fill('Build once, pin the image, roll out.\n\n## Roll back\n\nRevert the pin.')
  await expect(page.getByText('Unsaved')).toBeVisible()
  await page.keyboard.press('ControlOrMeta+Enter')
  await expect(page).toHaveURL('/p/PHAROS/knowledge/runbook/ship-a-release')
  const patch = calls.find(call => call.method === 'PATCH')!
  expect(patch.headers['if-unmodified-since']).toBe(new Date(Date.parse('2026-09-23T12:00:00Z') - 2 * 3_600_000).toISOString())
  expect(patch.body).toEqual({ body: 'Build once, pin the image, roll out.\n\n## Roll back\n\nRevert the pin.', status: 'proposed', slug: 'ship-a-release' })
  await expect(page.locator('.e-note.proposed')).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'On this page' })).toHaveCount(0)
  // Undo from the toast brings the old slug, text and status back.
  await page.getByRole('button', { name: 'Undo' }).click()
  await expect.poll(() => world.entries.find(item => item.id === 'k-deploy')?.slug).toBe('deploy-release')
  await expect(page).toHaveURL('/p/PHAROS/knowledge/runbook/deploy-release')
  await expect(page.getByRole('heading', { name: 'Canary on csb1' })).toBeVisible()
  await expect(page.locator('.e-note.proposed')).toHaveCount(0)
  // Escape with changes asks first.
  await page.keyboard.press('e')
  await page.getByRole('form', { name: 'Edit deploy-release' }).getByLabel('Title').fill('Deploy')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Discard your changes?' })).toBeVisible()
  await page.getByRole('button', { name: 'Discard' }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'Deploy a release to production' })).toBeVisible()
})

test('a newer version from someone else keeps the draft and lets you choose', async ({ page }) => {
  const { calls } = await open(page, entry, { conflictOn: 'k-deploy' })
  await expect(page.locator('.e-body')).toBeVisible()
  await page.getByRole('button', { name: /^Edit/ }).click()
  const text = page.getByRole('textbox', { name: 'Text, Markdown' })
  await text.fill('My draft of the deploy.')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  const banner = page.locator('.e-conflict')
  await expect(banner).toContainText('Mira Holm saved a newer version')
  await expect(banner).toContainText('They changed the title and text')
  await expect(text).toHaveValue('My draft of the deploy.')
  await banner.getByRole('button', { name: 'Compare the text' }).click()
  await expect(banner.getByRole('list', { name: 'Their text against your draft' })).toContainText('Mira added this line while you were editing.')
  await banner.getByRole('button', { name: 'Keep my changes' }).click()
  await expect(banner).toHaveCount(0)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.locator('.e-body')).toContainText('My draft of the deploy.')
  const patches = calls.filter(call => call.method === 'PATCH')
  expect(patches).toHaveLength(2)
  expect(patches[1].headers['if-unmodified-since']).not.toBe(patches[0].headers['if-unmodified-since'])
  // Their title is what stands now; the draft only changed the text.
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Deploy a release to production (checked)')
})

test('a conflict can also take their version', async ({ page }) => {
  await open(page, entry, { conflictOn: 'k-deploy' })
  await page.getByRole('button', { name: /^Edit/ }).click()
  await page.getByRole('textbox', { name: 'Text, Markdown' }).fill('Mine.')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('button', { name: 'Use their version' }).click()
  await expect(page.getByRole('textbox', { name: 'Text, Markdown' })).toHaveValue(/Mira added this line/)
  await expect(page.getByRole('form', { name: 'Edit deploy-release' }).getByLabel('Title')).toHaveValue('Deploy a release to production (checked)')
})

test('creating suggests a free slug, refuses a taken one and opens the new entry to write', async ({ page }) => {
  const { calls } = await open(page, '/p/PHAROS/knowledge')
  await expect(rows(page).first()).toBeVisible()
  await page.keyboard.press('n')
  const dialog = page.getByRole('dialog', { name: 'New knowledge entry' })
  await expect(dialog).toBeVisible()
  await dialog.getByText('Guideline', { exact: true }).click()
  await dialog.getByLabel('Title').fill('Write for people, not for the log')
  // The title's slug is taken by another guideline: the suggestion steps aside.
  await expect(dialog.getByLabel('Slug')).toHaveValue('write-for-people-not-for-the-log')
  await dialog.getByLabel('Title').fill('Plain words')
  await expect(dialog.getByLabel('Slug')).toHaveValue('plain-words-2')
  await dialog.getByLabel('Slug').fill('plain-words')
  await expect(dialog.getByRole('alert')).toContainText('Another guideline here already uses this slug.')
  await dialog.getByLabel('Slug').fill('tone-of-voice')
  await expect(dialog.locator('.cmd')).toHaveText('paimos knowledge get guideline tone-of-voice --project PHAROS')
  await dialog.getByRole('button', { name: 'Create and write' }).click()
  await expect(page).toHaveURL('/p/PHAROS/knowledge/guideline/tone-of-voice')
  const post = calls.find(call => call.method === 'POST')!
  expect(post.body).toEqual({ project_id: 'p-pharos', type: 'guideline', slug: 'tone-of-voice', title: 'Plain words', key_prefix: 'PHAROS' })
  await expect(page.getByRole('form', { name: 'Edit tone-of-voice' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Text, Markdown' })).toBeFocused()
})

test('knowledge across projects searches every project and opens entries where they live', async ({ page }) => {
  const errors = watchErrors(page)
  await open(page, '/knowledge')
  const search = page.getByRole('searchbox', { name: 'Search knowledge in every project' })
  await expect(search).toBeFocused()
  await expect(page.locator('.kp-group h2')).toHaveText(['Pharos', 'Aeon'])
  await search.fill('deploy')
  await expect(page).toHaveURL('/knowledge?q=deploy')
  await expect(page.locator('.kp-summary')).toHaveText('3 entries in 2 projects')
  await page.locator('.kp-kinds').getByRole('button', { name: /Runbooks/ }).click()
  await expect(page).toHaveURL('/knowledge?q=deploy&type=runbook')
  await expect(page.locator('.kp-row .kp-title')).toHaveText(['Deploy a release to production', 'Ship an Aeon release'])
  await page.locator('.kp-row').filter({ hasText: 'Ship an Aeon release' }).click()
  await expect(page).toHaveURL('/p/AEON/knowledge/runbook/deploy-release')
  await expect(page.getByRole('heading', { level: 1, name: 'Ship an Aeon release' })).toBeVisible()
  expect(errors).toEqual([])
})

test('the palette finds knowledge by its words and leads to the tab and the search', async ({ page }) => {
  await open(page, '/p/PHAROS')
  await expect(page.locator('tr.ticket-row:not(.ghost)').first()).toBeVisible()
  await page.keyboard.press('Control+k')
  const palette = page.getByRole('dialog', { name: 'Search and commands' })
  await expect(palette.getByRole('group', { name: 'Actions' }).getByRole('option', { name: /Go to Knowledge/ })).toBeVisible()
  await page.keyboard.type('rollback')
  const knowledge = palette.getByRole('group', { name: 'Knowledge' }).getByRole('option')
  await expect(knowledge).toHaveText([/Deploy a release to production.*runbook\/deploy-release/])
  await expect(palette.getByRole('option', { name: /Search all knowledge for “rollback”/ })).toBeVisible()
  await page.keyboard.press('Enter')
  // Wide, the entry opens docked beside its project's list.
  await expect(page).toHaveURL('/p/PHAROS/knowledge?entry=runbook/deploy-release')
  await expect(page.getByRole('complementary', { name: 'Runbook: Deploy a release to production' })).toBeVisible()
  await page.keyboard.press('Control+k')
  await page.keyboard.type('new knowledge')
  await palette.getByRole('option', { name: /New knowledge entry in PHAROS/ }).click()
  await expect(page.getByRole('dialog', { name: 'New knowledge entry' })).toBeVisible()
})

test('an old slug lands on the renamed entry; a missing one says so honestly', async ({ page }) => {
  await open(page, '/p/PHAROS/knowledge/runbook/deploy-flow')
  await expect(page).toHaveURL(entry)
  await expect(page.getByText('“deploy-flow” is now called “deploy-release”')).toBeVisible()
  await page.goto('/p/PHAROS/knowledge/runbook/nope')
  await expect(page.getByRole('heading', { name: 'No runbook called “nope” in Pharos' })).toBeVisible()
  await page.getByRole('link', { name: 'Search for “nope”' }).click()
  await expect(page).toHaveURL('/p/PHAROS/knowledge?q=nope')
})

test('deleting an entry asks, leaves and can be undone', async ({ page }) => {
  await open(page, '/p/PHAROS/knowledge/guideline/plain-words')
  await expect(page.getByRole('heading', { level: 1, name: 'Write for people, not for the log' })).toBeVisible()
  await page.getByRole('button', { name: 'More actions' }).click()
  await page.getByRole('menuitem', { name: /Delete guideline/ }).click()
  await page.getByRole('button', { name: 'Delete guideline' }).click()
  await expect(page).toHaveURL('/p/PHAROS/knowledge?view=entries')
  await expect(page.getByText('Write for people, not for the log')).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo' }).click()
  await expect(rows(page).filter({ hasText: 'Write for people, not for the log' })).toBeVisible()
})

test('a proposed entry is confirmed in one step, with undo', async ({ page }) => {
  await open(page, '/p/PHAROS/knowledge/memory/hetzner-token-expiry')
  const note = page.locator('.e-note.proposed')
  await expect(note).toContainText('Proposed by camy')
  await note.getByRole('button', { name: 'Confirm' }).click()
  await expect(note).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo' }).click()
  await expect(page.locator('.e-note.proposed')).toBeVisible()
})

test('people who can only read get no write controls', async ({ page }) => {
  await open(page, '/p/PHAROS/knowledge', { readOnly: true })
  await expect(rows(page).first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'New knowledge entry' })).toHaveCount(0)
  await page.keyboard.press('n')
  await expect(page.getByRole('dialog', { name: 'New knowledge entry' })).toBeHidden()
  await rows(page).first().click()
  await expect(page.locator('.e-body')).toBeVisible()
  await expect(page.getByRole('button', { name: /^Edit/ })).toHaveCount(0)
})

test('a project without knowledge says what belongs there and offers a start', async ({ page }) => {
  await open(page, '/p/PHAROS/knowledge', { empty: true })
  await expect(page.getByRole('heading', { name: 'No knowledge in Pharos yet' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Status/ })).toHaveCount(0)
  await page.getByRole('button', { name: /Write a runbook/ }).click()
  await expect(page.getByRole('dialog', { name: 'New knowledge entry' })).toBeVisible()
})

for (const scheme of ['light', 'dark'] as const) {
  test(`knowledge screens pass axe in ${scheme}`, async ({ page }) => {
    await page.emulateMedia({ colorScheme: scheme })
    await open(page, '/p/PHAROS/knowledge')
    await expect(rows(page).first()).toBeVisible()
    await axe(page)
    await page.keyboard.press('n')
    await expect(page.getByRole('dialog', { name: 'New knowledge entry' })).toBeVisible()
    await axe(page)
    await page.keyboard.press('Escape')
    await page.goto(entry)
    await expect(page.locator('.e-body')).toBeVisible()
    await axe(page)
    await page.keyboard.press('e')
    await page.getByRole('form', { name: 'Edit deploy-release' }).getByLabel('Slug').fill('ship-a-release')
    await expect(page.locator('.e-rename')).toBeVisible()
    await axe(page)
    await page.goto('/p/PHAROS/knowledge/external-system/hetzner')
    await expect(page.locator('.e-where')).toBeVisible()
    await axe(page)
    await page.goto('/knowledge?q=deploy')
    await expect(page.locator('.kp-row').first()).toBeVisible()
    await axe(page)
  })
}
