// SPDX-License-Identifier: AGPL-3.0-only
import { test, expect, type Page } from '@playwright/test'
import { fixtures, mockWork, watchErrors, type Call } from './work-fixtures'

// setSystemTime lets time flow (setFixedTime would freeze Vue's event timestamps).
test.beforeEach(async ({ page }) => { await page.clock.setSystemTime(new Date('2026-09-23T12:00:00Z')) })

const grid = (page: Page) => page.getByRole('grid', { name: 'Tickets' })
const rows = (page: Page) => grid(page).locator('tr.ticket-row:not(.ghost)')
const row = (page: Page, key: string) => grid(page).locator('tr.ticket-row').filter({ has: page.locator('.key', { hasText: new RegExp(`^${key}$`) }) })
const lastList = (calls: Call[]) => calls.filter(call => call.path === '/api/nodes' && call.query.get('within') && call.query.get('limit') === '200').at(-1)!

test('the list asks for open work in the project and shows every column', async ({ page }) => {
  const errors = watchErrors(page)
  const calls = await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await expect(page.getByRole('heading', { name: 'Pharos', level: 1 })).toBeVisible()
  await expect(rows(page)).toHaveCount(5)
  const query = lastList(calls).query
  expect(query.get('within')).toBe('p-pharos')
  expect(query.get('kind')).toBe('work,ticket,task,epic')
  expect(query.get('hide_closed')).toBe('true')
  expect(query.get('facets')).toBe('state,priority,assignee,kind')
  expect(query.get('sort')).toBe('-updated_at')
  await expect(rows(page).locator('.key')).toHaveText(['PHAROS-11', 'PHAROS-12', 'PHAROS-13', 'PHAROS-14', 'PHAROS-10'])
  await expect(rows(page).locator('.status-btn')).toHaveText(['In progress', 'Backlog', 'QA', 'New', 'Backlog'])
  await expect(rows(page).locator('.c-prio')).toHaveText(['High', 'Medium', 'Low', '—', 'High'])
  await expect(row(page, 'PHAROS-11').locator('.c-assignee')).toHaveText('MBMarkus Barta')
  await expect(row(page, 'PHAROS-14').locator('.c-assignee')).toHaveText('—')
  await expect(row(page, 'PHAROS-11').locator('.parent-chip')).toContainText('Guarded multi-cloud provisioning')
  await expect(row(page, 'PHAROS-13').locator('.parent-chip')).toHaveText('PHAROS-12')
  await expect(row(page, 'PHAROS-14').locator('.parent-chip')).toHaveCount(0)
  await expect(row(page, 'PHAROS-11').locator('time')).toHaveText('1h ago')
  // The count lives in the footer (footer-summary.spec.ts); the toolbar no longer repeats it.
  await expect(page.getByRole('toolbar').getByText('5 tickets')).toHaveCount(0)
  expect(await page.locator('thead th').first().evaluate(el => getComputedStyle(el).position)).toBe('sticky')
  expect(errors).toEqual([])
})

test('header clicks sort ascending, descending, then off; shift adds a second key', async ({ page }) => {
  const calls = await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await expect(rows(page)).toHaveCount(5)
  const priority = page.getByRole('columnheader', { name: 'Priority' })
  await priority.getByRole('button').click()
  await expect(page).toHaveURL(/sort=priority&view=list$/)
  await expect(priority).toHaveAttribute('aria-sort', 'ascending')
  await expect.poll(() => lastList(calls).query.get('sort')).toBe('priority,-updated_at')
  await expect(rows(page).first().locator('.key')).toHaveText('PHAROS-11')
  await priority.getByRole('button').click()
  await expect(priority).toHaveAttribute('aria-sort', 'descending')
  await expect.poll(() => lastList(calls).query.get('sort')).toBe('-priority,-updated_at')
  await priority.getByRole('button').click()
  await expect(priority).toHaveAttribute('aria-sort', 'none')
  await expect.poll(() => lastList(calls).query.get('sort')).toBe('-updated_at')
  await priority.getByRole('button').click()
  await page.getByRole('columnheader', { name: 'Key' }).getByRole('button').click({ modifiers: ['Shift'] })
  await expect.poll(() => lastList(calls).query.get('sort')).toBe('priority,key,-updated_at')
  await expect(page.getByRole('columnheader', { name: 'Key' }).locator('.sort-index')).toHaveText('2')
})

test('facet menus filter with counts, show chips, and closed statuses reveal closed work', async ({ page }) => {
  const calls = await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await expect(rows(page)).toHaveCount(5)
  await page.getByRole('toolbar').getByRole('button', { name: 'Status', exact: true }).click()
  const menu = page.getByRole('dialog', { name: 'Filter by Status' })
  await expect(menu.getByText('Blocked', { exact: true })).toBeVisible()
  await expect(menu.locator('.facet-option').filter({ hasText: 'Backlog' }).locator('.count')).toHaveText('2')
  await expect(menu.locator('.facet-option').filter({ hasText: 'In progress' }).locator('.count')).toHaveText('1')
  await menu.getByText('Backlog', { exact: true }).click()
  await expect(page).toHaveURL(/status=backlog/)
  await expect(rows(page)).toHaveCount(2)
  expect(lastList(calls).query.get('state')).toBe('backlog')
  // The status menu keeps counting the other statuses while Status is filtered.
  await expect(menu.locator('.facet-option').filter({ hasText: 'QA' }).locator('.count')).toHaveText('1')
  await page.keyboard.press('Escape')
  await expect(menu).toHaveCount(0)
  const applied = page.getByRole('toolbar').getByRole('button', { name: 'Edit Status filter: Backlog', exact: true })
  await expect(applied).toBeVisible()
  await expect(applied.locator('.facet-value')).toHaveText('· Backlog')
  await expect(applied.locator('.facet-count')).toHaveText('1')
  await expect(applied).toHaveAttribute('data-tip', 'Status: Backlog')
  await page.getByRole('toolbar').getByRole('button', { name: 'Priority', exact: true }).click()
  await page.getByRole('dialog', { name: 'Filter by Priority' }).getByText('High', { exact: true }).click()
  await expect(rows(page)).toHaveCount(1)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Remove Status filter' }).click()
  await expect(page).not.toHaveURL(/status=/)
  await expect(rows(page)).toHaveCount(2)
  await page.getByRole('button', { name: 'Remove Priority filter' }).click()
  await expect(rows(page)).toHaveCount(5)
  await page.getByRole('toolbar').getByRole('button', { name: 'Status', exact: true }).click()
  await page.getByRole('dialog', { name: 'Filter by Status' }).getByText('Done', { exact: true }).click()
  await expect(page).toHaveURL(/closed=1/)
  await expect(rows(page).locator('.key')).toHaveText(['PHAROS-15'])
  await expect(page.getByLabel('Hide closed', { exact: true })).not.toBeChecked()
})

test('hide closed is on by default and can be turned off', async ({ page }) => {
  const calls = await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await expect(rows(page)).toHaveCount(5)
  await page.getByLabel('Hide closed', { exact: true }).uncheck()
  await expect(rows(page)).toHaveCount(7)
  expect(lastList(calls).query.get('hide_closed')).toBeNull()
  await expect(row(page, 'PHAROS-16').locator('.status-btn')).toHaveText('Cancelled')
})

test('list search filters live, highlights matches, and / and Esc work', async ({ page }) => {
  const calls = await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await expect(rows(page)).toHaveCount(5)
  await page.keyboard.press('/')
  const search = page.getByLabel('Search tickets in this project')
  await expect(search).toBeFocused()
  await page.keyboard.type('hetzner')
  await expect(page).toHaveURL(/q=hetzner/)
  await expect(rows(page)).toHaveCount(2)
  expect(lastList(calls).query.get('q')).toBe('hetzner')
  await expect(grid(page).locator('mark')).toHaveText(['Hetzner', 'Hetzner'])
  await page.keyboard.press('Escape')
  await expect(search).toHaveValue('')
  await expect(rows(page)).toHaveCount(5)
})

test('grouping by status and by epic', async ({ page }) => {
  await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await expect(rows(page)).toHaveCount(5)
  await page.getByRole('button', { name: 'Display' }).click()
  await page.getByRole('dialog', { name: 'Display options' }).getByRole('radio', { name: 'Status' }).click()
  await expect(page).toHaveURL(/group=status/)
  await expect(grid(page).locator('.group-row .group-label')).toHaveText(['New', 'Backlog', 'In progress', 'QA'])
  await expect(grid(page).locator('.group-row .group-count')).toHaveText(['1', '2', '1', '1'])
  await page.getByRole('button', { name: 'Collapse Backlog' }).click()
  await expect(rows(page)).toHaveCount(3)
  await page.getByRole('button', { name: 'Grouped by status' }).click()
  await page.getByRole('dialog', { name: 'Display options' }).getByRole('radio', { name: 'Epic' }).click()
  await expect(grid(page).locator('.group-row .group-label')).toHaveText(['Guarded multi-cloud provisioning', 'No parent'])
  await expect(grid(page).locator('tbody').first().locator('.key')).toHaveText(['PHAROS-10', 'PHAROS-11', 'PHAROS-12', 'PHAROS-13'])
})

test('status changes are optimistic, confirmed by PATCH and can be undone', async ({ page }) => {
  const calls = await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await row(page, 'PHAROS-11').getByRole('button', { name: /Change status of PHAROS-11/ }).click()
  const menu = page.getByRole('menu', { name: 'Status of PHAROS-11' })
  await expect(menu.getByRole('menuitemradio', { name: 'In progress' })).toHaveAttribute('aria-checked', 'true')
  await expect(menu.getByRole('menuitemradio', { name: 'In progress' })).toBeFocused()
  await menu.getByRole('menuitemradio', { name: 'QA' }).click()
  await expect(row(page, 'PHAROS-11').locator('.status-btn')).toHaveText('QA')
  await expect(page.getByText('PHAROS-11 is now QA')).toBeVisible()
  await expect.poll(() => calls.find(call => call.method === 'PATCH')?.body).toEqual({ state: 'qa' })
  expect(calls.find(call => call.method === 'PATCH')!.headers['if-unmodified-since']).toBe(new Date(Date.parse('2026-09-23T12:00:00Z') - 3_600_000).toISOString())
  await page.getByRole('button', { name: 'Undo' }).click()
  await expect(row(page, 'PHAROS-11').locator('.status-btn')).toHaveText('In progress')
  await expect.poll(() => calls.filter(call => call.method === 'PATCH').at(-1)?.body).toEqual({ state: 'in-progress' })
})

test('blocked is a status between backlog and in progress', async ({ page }) => {
  const calls = await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await row(page, 'PHAROS-14').getByRole('button', { name: /Change status of PHAROS-14/ }).click()
  const menu = page.getByRole('menu', { name: 'Status of PHAROS-14' })
  await expect(menu.getByRole('menuitemradio').locator('.label')).toHaveText(['New', 'Backlog', 'Open', 'Blocked', 'In progress', 'QA', 'Done', 'Delivered', 'Accepted', 'Cancelled', 'Archived'])
  const icon = menu.getByRole('menuitemradio', { name: 'Blocked' }).locator('svg')
  await expect(icon).toHaveClass(/st-blocked/)
  await expect(icon.locator('circle')).toHaveAttribute('stroke', 'var(--st-blocked)')
  await expect(icon.locator('circle')).toHaveAttribute('stroke-dasharray', '2.1 1.9')
  await expect(icon.locator('path')).toHaveAttribute('d', 'M4.7 7h4.6')
  await menu.getByRole('menuitemradio', { name: 'Blocked' }).click()
  await expect(row(page, 'PHAROS-14').locator('.status-btn')).toHaveText('Blocked')
  await expect.poll(() => calls.find(call => call.method === 'PATCH')?.body).toEqual({ state: 'blocked' })
})

test('a status menu is keyboard driven with digits', async ({ page }) => {
  const calls = await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await row(page, 'PHAROS-14').getByRole('button', { name: /Change status of PHAROS-14/ }).click()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitemradio', { name: 'Backlog' })).toBeFocused()
  await expect(page.getByRole('menuitemradio', { name: 'QA', exact: true }).locator('.digit')).toHaveText('6')
  await page.keyboard.press('6')
  await expect(row(page, 'PHAROS-14').locator('.status-btn')).toHaveText('QA')
  await expect.poll(() => calls.find(call => call.method === 'PATCH')?.body).toEqual({ state: 'qa' })
})

test('a status changed elsewhere is not overwritten', async ({ page }) => {
  const calls = await mockWork(page, fixtures(), { conflictOn: 'n-2' })
  await page.goto('/p/PHAROS')
  await row(page, 'PHAROS-12').getByRole('button', { name: /Change status of PHAROS-12/ }).click()
  await page.getByRole('menuitemradio', { name: 'QA' }).click()
  await expect(page.getByText('PHAROS-12 was changed elsewhere')).toBeVisible()
  await expect(row(page, 'PHAROS-12').locator('.status-btn')).toHaveText('Backlog')
  await expect(row(page, 'PHAROS-12')).toContainText('(edited elsewhere)')
  const patches = calls.filter(call => call.method === 'PATCH')
  expect(patches).toHaveLength(1)
  expect(patches[0].headers['if-unmodified-since']).toBeTruthy()
  await expect(page.getByText('PHAROS-12 is now QA')).toHaveCount(0)
})

test('a rejected status change rolls back and explains why', async ({ page }) => {
  await mockWork(page, fixtures(), { failPatch: true })
  await page.goto('/p/PHAROS')
  await row(page, 'PHAROS-13').getByRole('button', { name: /Change status of PHAROS-13/ }).click()
  await page.getByRole('menuitemradio', { name: 'Done' }).click()
  await expect(page.getByText('PHAROS-13 keeps its status: State is not allowed here')).toBeVisible()
  await expect(row(page, 'PHAROS-13').locator('.status-btn')).toHaveText('QA')
})

test('keyboard opens the side panel; j and k follow; Esc and Back close it', async ({ page }) => {
  await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await expect(rows(page)).toHaveCount(5)
  await page.keyboard.press('j')
  await expect(row(page, 'PHAROS-11')).toHaveClass(/\bcursor\b/)
  await page.keyboard.press('j')
  await expect(row(page, 'PHAROS-12')).toHaveClass(/\bcursor\b/)
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL('/p/PHAROS/PHAROS-12')
  const panel = page.getByRole('complementary', { name: 'Ticket details' })
  await expect(panel.getByRole('heading', { name: 'Add an Oracle Cloud connector' })).toBeVisible()
  await expect(panel).toContainText('2 / 5')
  await page.keyboard.press('j')
  await expect(page).toHaveURL('/p/PHAROS/PHAROS-13')
  await expect(panel.getByRole('heading', { name: 'Run the disposable Hetzner end-to-end check' })).toBeVisible()
  await panel.getByRole('button', { name: 'Previous ticket' }).click()
  await expect(page).toHaveURL('/p/PHAROS/PHAROS-12')
  await page.keyboard.press('Escape')
  await expect(page).toHaveURL('/p/PHAROS/tickets')
  await expect(panel).toHaveCount(0)
  await page.keyboard.press('o')
  await expect(page).toHaveURL('/p/PHAROS/PHAROS-12')
  await page.goBack()
  await expect(page).toHaveURL('/p/PHAROS/tickets')
  await expect(panel).toHaveCount(0)
})

test('deep links open tickets outside the current list and render Markdown task lists', async ({ page }) => {
  const calls = await mockWork(page, fixtures())
  await page.goto('/p/PHAROS/PHAROS-15')
  const panel = page.getByRole('complementary', { name: 'Ticket details' })
  await expect(panel.getByRole('heading', { name: 'Beacon health probes' })).toBeVisible()
  await expect(panel.getByRole('button', { name: /Status: Done/ })).toBeVisible()
  expect(calls.some(call => call.path === '/api/nodes' && call.query.get('q') === 'PHAROS-15')).toBe(true)
  await page.goto('/p/PHAROS/PHAROS-11')
  await expect(panel.locator('.task-box')).toHaveCount(2)
  await expect(panel.locator('.task-box:checked')).toHaveCount(1)
  await expect(panel.locator('.task-list-item').first()).toHaveText('Token stored in the vault')
  expect(await panel.locator('.markdown-body code').first().evaluate(el => getComputedStyle(el).fontVariantLigatures)).toBe('none')
  await expect(row(page, 'PHAROS-11')).toHaveClass(/open/)
  await page.goto('/p/PHAROS/PHAROS-999')
  await expect(panel.getByRole('alert')).toContainText('PHAROS-999 is not part of Pharos')
})

test('? opens the shortcut sheet', async ({ page }) => {
  await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await expect(rows(page)).toHaveCount(5)
  await page.keyboard.press('Shift+?')
  const sheet = page.getByRole('dialog', { name: 'Keyboard shortcuts' })
  await expect(sheet).toBeVisible()
  // Command is drawn (an SVG with its name for screen readers), never the ⌘ text symbol.
  await expect(sheet.locator('.keycap').first()).toHaveText(/^(Command|Ctrl)$/)
  await expect(sheet).toContainText('Search tickets, projects and actions')
  await expect(sheet).toContainText('Search this list')
  await page.keyboard.press('Escape')
  await expect(sheet).not.toBeVisible()
})

test('long lists load 200 rows per page while scrolling', async ({ page }) => {
  const calls = await mockWork(page, fixtures({ bigProject: 450 }))
  await page.goto('/p/AEON')
  await expect(rows(page)).toHaveCount(200)
  await page.locator('main').evaluate(main => { main.scrollTop = main.scrollHeight })
  await expect(rows(page)).toHaveCount(400)
  const second = calls.find(call => call.query.get('cursor') === 'o:200')!
  expect(second.query.get('limit')).toBe('200')
  expect(second.query.get('facets')).toBe('state,priority,assignee,kind')
  await page.locator('main').evaluate(main => { main.scrollTop = main.scrollHeight })
  await expect(rows(page)).toHaveCount(451)
  await expect(page.locator('.list-foot.end')).toHaveText('451 tickets')
})

test('skeleton rows while loading, then an empty state that clears filters', async ({ page }) => {
  await mockWork(page, fixtures(), { delayList: 800 })
  await page.goto('/p/PHAROS?q=nothing-matches')
  // A filtered load expects few rows, so the skeleton stays short.
  await expect(page.locator('.skeleton-body tr')).toHaveCount(8)
  await expect(page.getByRole('heading', { name: 'No tickets match these filters' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await expect(rows(page)).toHaveCount(5)
})

test('an unfiltered load holds about the height of the first page', async ({ page }) => {
  await mockWork(page, fixtures(), { delayList: 800 })
  await page.goto('/p/PHAROS')
  // The summary counts 3 open and 2 in progress for PHAROS; the closed ones stay hidden.
  await expect(page.locator('.skeleton-body tr')).toHaveCount(5)
  await expect(rows(page)).toHaveCount(5)
})

test('load errors offer a retry', async ({ page }) => {
  await mockWork(page, fixtures(), { failList: true })
  await page.goto('/p/PHAROS')
  await expect(page.getByRole('heading', { name: 'Tickets could not be loaded' })).toBeVisible()
  await page.unroute('**/api/**')
  await mockWork(page, fixtures())
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(rows(page)).toHaveCount(5)
})

test('density switches between 36 and 30 pixel rows', async ({ page }) => {
  await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await expect(rows(page)).toHaveCount(5)
  expect((await rows(page).first().boundingBox())!.height).toBeCloseTo(36, 0)
  await page.getByRole('button', { name: 'Display' }).click()
  await page.getByRole('dialog', { name: 'Display options' }).getByRole('radiogroup', { name: 'Row height' }).getByRole('radio', { name: 'Compact' }).click()
  await expect(rows(page).first()).toHaveCSS('height', '30px')
})

test('every cell of a row shares one centre line', async ({ page }) => {
  await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await expect(rows(page)).toHaveCount(5)
  const centres = await row(page, 'PHAROS-11').evaluate(tr => ['.key', '.title-link', '.status-btn span', '.prio-label', '.person-name', 'time', '.kind-glyph', '.c-prio svg', '.c-status svg'].map(selector => {
    const box = tr.querySelector(selector)!.getBoundingClientRect()
    return box.top + box.height / 2
  }))
  for (const centre of centres) expect(Math.abs(centre - centres[0])).toBeLessThanOrEqual(1)
})

test('the Assignee column appears only when someone in the result is assigned', async ({ page }) => {
  await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  await expect(page.getByRole('columnheader', { name: 'Assignee' })).toBeVisible()
  await page.goto('/p/PHAROS?status=new')
  await expect(rows(page)).toHaveCount(1)
  await expect(page.getByRole('columnheader', { name: 'Assignee' })).toHaveCount(0)
  await expect(rows(page).first().locator('td')).toHaveCount(5)
})

test('project header shows the project summary counts, cancelled work out of scope', async ({ page }) => {
  await mockWork(page, fixtures())
  await page.goto('/p/PHAROS')
  const stats = page.locator('.head-stats')
  await expect(stats.getByRole('button', { name: 'Filter open tickets: 3', exact: true })).toBeVisible()
  // "Doing" on screen; the full "in progress" for screen readers and in the tooltip.
  await expect(stats.getByRole('button', { name: 'Filter doing tickets: 2', exact: true })).toBeVisible()
  await expect(stats).toHaveAttribute('aria-label', /2 in progress/)
  await expect(stats.getByRole('button', { name: 'Filter doing tickets: 2', exact: true })).toHaveAttribute('data-tip', 'Show only doing tickets; click again to clear')
  await expect(stats.getByRole('button', { name: 'Filter done tickets: 1', exact: true })).toBeVisible()
  await expect(stats).toContainText('17%')
  await expect(stats.locator('.progress-line')).toHaveAttribute('data-tip', '1 of 6 done · 1 cancelled')
})

test('wide screens dock the side panel beside the list; narrow ones overlay it', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await mockWork(page, fixtures())
  await page.goto('/p/PHAROS/PHAROS-12')
  const panel = page.getByRole('complementary', { name: 'Ticket details' })
  await expect(panel.getByRole('heading', { name: 'Add an Oracle Cloud connector' })).toBeVisible()
  const dock = (await panel.boundingBox())!
  const table = (await page.locator('.table-card').boundingBox())!
  expect(table.x + table.width).toBeLessThanOrEqual(dock.x)
  const status = (await page.getByRole('columnheader', { name: 'Status' }).boundingBox())!
  expect(status.x + status.width).toBeLessThanOrEqual(dock.x)
  await expect(page.getByRole('columnheader', { name: 'Updated' })).toBeVisible()
  await expect(row(page, 'PHAROS-12')).toBeInViewport()
  await page.setViewportSize({ width: 900, height: 768 })
  const tablet = (await page.locator('.table-card').boundingBox())!
  expect(tablet.x + tablet.width).toBeLessThanOrEqual((await panel.boundingBox())!.x)
  await page.setViewportSize({ width: 899, height: 768 })
  const overlaid = (await page.locator('.table-card').boundingBox())!
  expect(overlaid.x + overlaid.width).toBeGreaterThan((await panel.boundingBox())!.x)
})

test('the footer bar is a row of the shell: rows scroll above it, never under it', async ({ page }) => {
  await mockWork(page, fixtures({ bigProject: 30 }))
  await page.goto('/p/AEON')
  await expect(rows(page)).toHaveCount(31)
  const footer = page.locator('footer.app-footer')
  await expect(footer).toBeVisible()
  // Outside the scrolling page, at the bottom of the window.
  expect(await footer.evaluate(el => !el.closest('main'))).toBe(true)
  const viewport = page.viewportSize()!
  const foot = (await footer.boundingBox())!
  expect(Math.round(foot.y + foot.height)).toBe(viewport.height)
  expect(Math.round((await page.locator('main').boundingBox())!.y + (await page.locator('main').boundingBox())!.height)).toBeLessThanOrEqual(Math.round(foot.y) + 1)
  await page.locator('main').evaluate(el => { el.scrollTop = el.scrollHeight })
  const last = (await rows(page).last().boundingBox())!
  expect(last.y + last.height).toBeLessThanOrEqual(foot.y)
})

test('global search opens a ticket inside its project', async ({ page }) => {
  await mockWork(page, fixtures())
  await page.goto('/')
  await expect(page.getByRole('list', { name: 'Projects' })).toBeVisible()
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('combobox', { name: 'Search tickets, projects and actions' })).toBeFocused()
  await page.keyboard.type('oracle')
  await expect(page.getByRole('option').first()).toContainText('Add an Oracle Cloud connector')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL('/p/PHAROS/PHAROS-12')
  await expect(page.getByRole('complementary', { name: 'Ticket details' }).getByRole('heading', { name: 'Add an Oracle Cloud connector' })).toBeVisible()
})

test('unknown project keys explain themselves', async ({ page }) => {
  await mockWork(page, fixtures())
  await page.goto('/p/NOPE')
  await expect(page.getByRole('heading', { name: 'No project called NOPE' })).toBeVisible()
  await page.getByRole('link', { name: 'All projects' }).click()
  await expect(page).toHaveURL('/')
})

for (const colorScheme of ['light', 'dark'] as const) {
  test(`phone rows use two lines and filters move into a sheet in ${colorScheme}`, async ({ page }) => {
    const errors = watchErrors(page)
    await page.setViewportSize({ width: 390, height: 844 })
    await page.emulateMedia({ colorScheme })
    await mockWork(page, fixtures())
    await page.goto('/p/PHAROS')
    await expect(rows(page)).toHaveCount(5)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const first = rows(page).first()
    const key = await first.locator('.c-key').boundingBox(), title = await first.locator('.c-title').boundingBox()
    expect(title!.y).toBeGreaterThan(key!.y + key!.height - 1)
    await expect(page.getByRole('toolbar').getByRole('button', { name: 'Status', exact: true })).toBeHidden()
    await page.getByRole('button', { name: /^Filters/ }).click()
    const sheet = page.getByRole('dialog', { name: 'Filters' })
    await expect(sheet).toBeVisible()
    await sheet.locator('.facet-option').filter({ hasText: 'Backlog' }).click()
    await expect(page).toHaveURL(/status=backlog/)
    await sheet.getByRole('button', { name: 'Show 2 tickets' }).click()
    await expect(sheet).not.toBeVisible()
    await expect(rows(page)).toHaveCount(2)
    await rows(page).first().locator('.title-link').click()
    const panel = page.getByRole('complementary', { name: 'Ticket details' })
    await expect(panel).toBeVisible()
    const box = await panel.boundingBox()
    expect(box).toEqual({ x: 0, y: 0, width: 390, height: 844 })
    expect(errors).toEqual([])
  })
}
