// SPDX-License-Identifier: AGPL-3.0-only
// AEON-274: every quote of the ACME showcase bundle opens without an error page.
// The documents are the ones the server stores and serves byte for byte from
// GET /draft and GET /versions/{n}; they are generated by the Go test
// TestShowcaseQuotesAreUILoadable (internal/business/quoteshowcase):
//   AEON_SHOWCASE_FIXTURE_OUT=$PWD/web/tests/quotes/fixtures/showcase-acme.json go test -run TestShowcaseQuotesAreUILoadable ./internal/business/quoteshowcase/
import { readFileSync } from 'node:fs'
import { expect, test, type Page } from '@playwright/test'
import { crmData, HOFER, mockCRM } from './crm-fixtures'
import { mockQuotes, quoteWorld, type Row, type Version } from './quote-list-fixtures'
import type { QuoteDoc } from './quote-inspector-fixtures'
import { fixtures, me, mockWork, watchErrors } from './work-fixtures'
import { FONT } from './profile-fixtures'

interface ShowcaseQuote { key: string; offer_no: string; state: Row['state']; title: string; versions: number; documents: Record<string, QuoteDoc> }
const SHOWCASE: ShowcaseQuote[] = JSON.parse(readFileSync(new URL('./quotes/fixtures/showcase-acme.json', import.meta.url), 'utf8'))
const idOf = (i: number) => `acbe0000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`

async function setup(page: Page, tune: (key: string, doc: QuoteDoc) => void = () => {}) {
  await mockWork(page, fixtures())
  await mockCRM(page, crmData())
  const world = quoteWorld({ empty: true })
  SHOWCASE.forEach((quote, i) => {
    const qid = idOf(i)
    const draft = structuredClone(quote.documents.draft ?? quote.documents[`v${quote.versions}`]!)
    tune(quote.key, draft)
    const now = new Date().toISOString()
    world.rows.push({
      quote_node_id: qid, project_node_id: '', customer_org_node_id: HOFER, current_version: quote.versions, state: quote.state, revision: 2,
      offer_no: quote.offer_no, archived: false, project_ref: draft.project_ref, classic_status: quote.state === 'issued' ? 'sent' : quote.state,
      key: `QUO-${i + 1}`, title: quote.title, customer_name: String((draft.recipient as Record<string, unknown>).name ?? ''), currency: draft.currency,
      net_total_cents: draft.net_total_cents, offer_date: draft.offer_date, valid_until: draft.valid_until, created_at: now, updated_at: now,
    })
    world.drafts.set(qid, { document: draft, revision: 1, base: quote.versions })
    const versions: Version[] = []
    for (let n = 1; n <= quote.versions; n++) {
      const document = structuredClone(quote.documents[`v${n}`]!)
      tune(quote.key, document)
      versions.push({ quote_node_id: qid, version: n, currency: document.currency, title: document.title, content_sha256: `${n}`.repeat(64), created_by_principal_id: me.id, created_at: now, digest_mode: 'document-v1', pricing_mode: 'cent-half-up-v1', total: (document.net_total_cents / 100).toFixed(4), document, offer_no: quote.offer_no, validity_time_zone: 'Europe/Vienna' })
    }
    if (versions.length) world.versions.set(qid, versions)
  })
  await mockQuotes(page, world)
  await page.route('**/api/quote-profiles/assets/**', route => route.fulfill({ contentType: 'font/woff2', body: FONT }))
}

test('the fixture holds all five showcase quotes, the English one with its own profile', () => {
  expect(SHOWCASE.map(q => q.key)).toEqual(['acme-acceptance', 'acme-fitout', 'acme-platform', 'acme-retainer', 'steinwender-belegleser'])
  const retainer = SHOWCASE.find(q => q.key === 'acme-retainer')!
  expect(retainer.documents.draft!.profile!.definition.locale).toBe('en')
  expect(retainer.documents.draft!.profile!.definition.fonts).toEqual([])
})

for (const [i, quote] of SHOWCASE.entries()) {
  test(`showcase quote ${quote.key} opens beside the list without an error page`, async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    const errors = watchErrors(page)
    await setup(page)
    await page.goto(`/business/quotes?quote=${idOf(i)}`)
    const dock = page.locator('.quote-dock')
    await expect(dock.locator('.quote-document')).toHaveAttribute('data-quote-ready', 'true')
    await expect(dock.getByText(quote.title).first()).toBeVisible()
    await expect(page.getByText('This page stumbled')).toHaveCount(0)
    expect(errors).toEqual([])
  })
}

// The production draft of A260929-04 was stored before the fix with null lists
// in its profile snapshot. The page defaults them to empty instead of crashing.
test('a stored profile snapshot with null lists still opens (A260929-04 as stored before the fix)', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  const errors = watchErrors(page)
  await setup(page, (key, doc) => {
    if (key !== 'acme-retainer' || !doc.profile) return
    const definition = doc.profile.definition as unknown as Record<string, unknown>
    definition.fonts = null
    definition.labels = null
    definition.sections = null
    definition.cover = null
    definition.typography = null
  })
  const i = SHOWCASE.findIndex(q => q.key === 'acme-retainer')
  await page.goto(`/business/quotes?quote=${idOf(i)}`)
  const dock = page.locator('.quote-dock')
  await expect(dock.locator('.quote-document')).toHaveAttribute('data-quote-ready', 'true')
  await expect(dock.getByText('Analytical Support Retainer').first()).toBeVisible()
  await expect(page.getByText('This page stumbled')).toHaveCount(0)
  expect(errors).toEqual([])
})
