// SPDX-License-Identifier: AGPL-3.0-only
// Render Formula/aeon-agentd.rb for one inspr-calendar-v2 release.
// sha256 values come from that release's SHA256SUMS. The formula installs the
// signed, notarized darwin asset bytes with bin.install: no source build, no re-sign.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { pathToFileURL } from "node:url";
import { validCalendarVersion } from "./verify-release.mjs";

export const DARWIN_ASSETS = {
  arm64: "paimos-agentd-darwin-arm64",
  amd64: "paimos-agentd-darwin-amd64",
};

// sha256sum writes "<64 hex><two spaces><name>". shasum may use one space.
// A leading asterisk on the name is the binary-mode marker.
export function parseChecksums(text) {
  const map = new Map();
  for (const line of String(text).split(/\r?\n/)) {
    if (line === "") continue;
    const match = /^([0-9a-f]{64})[ \t]+\*?(\S+)$/.exec(line);
    if (!match) throw new Error("malformed SHA256SUMS line");
    if (map.has(match[2])) throw new Error(`duplicate checksum for ${match[2]}`);
    map.set(match[2], match[1]);
  }
  return map;
}

export function renderFormula(version, checksums) {
  if (!validCalendarVersion(version)) throw new Error(`invalid calendar version ${version}`);
  const sums = checksums instanceof Map ? checksums : parseChecksums(checksums);
  const arm = sums.get(DARWIN_ASSETS.arm64);
  const intel = sums.get(DARWIN_ASSETS.amd64);
  if (!/^[0-9a-f]{64}$/.test(arm || "") || !/^[0-9a-f]{64}$/.test(intel || "")) {
    throw new Error("SHA256SUMS is missing a darwin paimos-agentd asset");
  }
  const base = `https://github.com/inspr-at/paimos/releases/download/v${version}`;
  return `# SPDX-License-Identifier: AGPL-3.0-only
# Generated by scripts/homebrew-formula.mjs from the v${version} SHA256SUMS.
# Installs the signed, notarized darwin release bytes. No source build and no re-sign.
class AeonAgentd < Formula
  desc "PAIMOS AEON local harness supervisor"
  homepage "https://github.com/inspr-at/paimos"
  version "${version}"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "${base}/${DARWIN_ASSETS.arm64}"
      sha256 "${arm}"
    end
    on_intel do
      url "${base}/${DARWIN_ASSETS.amd64}"
      sha256 "${intel}"
    end
  end

  def install
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "paimos-agentd-darwin-#{arch}" => "aeon-agentd"
  end

  test do
    assert_match "${version}", shell_output("#{bin}/aeon-agentd --version")
  end
end
`;
}

function parseArgs(argv) {
  const args = { version: "", checksums: "", out: "" };
  for (let i = 0; i < argv.length; i++) {
    const key = argv[i];
    const value = argv[i + 1];
    if (key === "--version") args.version = value;
    else if (key === "--checksums") args.checksums = value;
    else if (key === "--out") args.out = value;
    else throw new Error(`unknown argument ${key}`);
    i++;
  }
  if (!args.version || !args.checksums) {
    throw new Error("usage: node scripts/homebrew-formula.mjs --version VERSION --checksums SHA256SUMS [--out FILE]");
  }
  return args;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    const args = parseArgs(process.argv.slice(2));
    const formula = renderFormula(args.version, readFileSync(args.checksums, "utf8"));
    if (args.out) {
      mkdirSync(dirname(args.out), { recursive: true });
      writeFileSync(args.out, formula);
    } else {
      process.stdout.write(formula);
    }
  } catch (err) {
    console.error(err.message);
    process.exitCode = 1;
  }
}
