#!/usr/bin/env python3
"""Regenerate the pinned MIT schema bundle; normal builds never fetch it."""
import argparse
import base64
import hashlib
import io
import json
from pathlib import Path
import shutil
import subprocess
import tarfile
import urllib.request

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "backend/agentd/claudeassets"
# Match the pinned SDK's Zod 4.0 JSON-schema converter; check with the real SDK.
VERSION = "4.0.17"
URL = f"https://registry.npmjs.org/zod/-/zod-{VERSION}.tgz"
INTEGRITY = "sha512-1PHjlYRevNxxdy2JZ8JcNAw7rX8V9P1AKkP+x/xZfxB0K5FYfuV+Ug6P/6NVSR2jHQ+FzDDoDHS04nYUsOIyLQ=="
ESBUILD = "0.25.12"

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--work-dir", type=Path, required=True,
                    help="new scratch directory; retained for inspection")
args = parser.parse_args()
work = args.work_dir.resolve()
work.mkdir(parents=True, exist_ok=False)
esbuild = ROOT / "frontend/node_modules/.bin/esbuild"
if subprocess.check_output([str(esbuild), "--version"], text=True).strip() != ESBUILD:
    raise RuntimeError("esbuild version mismatch")
with urllib.request.urlopen(URL, timeout=30) as response:
    archive = response.read(8 * 1024 * 1024 + 1)
if len(archive) > 8 * 1024 * 1024:
    raise RuntimeError("dependency archive is too large")
if "sha512-" + base64.b64encode(hashlib.sha512(archive).digest()).decode() != INTEGRITY:
    raise RuntimeError("dependency archive integrity mismatch")
modules = work / "node_modules"
modules.mkdir()
with tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz") as tar:
    tar.extractall(modules, filter="data")
(modules / "package").rename(modules / "zod")
source = ASSETS / "native-message-schema.src.mjs"
shutil.copyfile(source, work / "entry.mjs")
license_text = (modules / "zod/LICENSE").read_text()
banner = f"/*! Zod {VERSION}; generated by scripts/vendor-claude-message-schema.py.\n{license_text}*/"
output = ASSETS / "native-message-schema.mjs"
subprocess.run([str(esbuild), str(work / "entry.mjs"), "--bundle", "--format=esm",
                "--platform=node", "--target=node18", "--minify", "--legal-comments=none",
                f"--banner:js={banner}", f"--outfile={output}"], check=True)
manifest = {"dependency": "zod", "version": VERSION, "url": URL, "integrity": INTEGRITY,
            "license": "MIT", "esbuild": ESBUILD,
            "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
            "bundle_sha256": hashlib.sha256(output.read_bytes()).hexdigest()}
(ASSETS / "native-message-schema.json").write_text(json.dumps(manifest, indent=2) + "\n")
print(json.dumps(manifest, indent=2))
print(f"Scratch inputs retained at {work}; review the bundle and update its Go digest pin.")
