# SPDX-License-Identifier: AGPL-3.0-only
# Generated by scripts/homebrew-formula.mjs from the v260929113854.0.0 SHA256SUMS.
# Installs the signed, notarized darwin release bytes. No source build and no re-sign.
class AeonAgentd < Formula
  desc "PAIMOS AEON local harness supervisor"
  homepage "https://github.com/inspr-at/paimos"
  version "260929113854.0.0"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/inspr-at/paimos/releases/download/v260929113854.0.0/paimos-agentd-darwin-arm64"
      sha256 "a1efa562e714d3bd408b41f3fa3feae8e06a44f5f8d40027785e96dfaebaede6"
    end
    on_intel do
      url "https://github.com/inspr-at/paimos/releases/download/v260929113854.0.0/paimos-agentd-darwin-amd64"
      sha256 "b3b08483315b67df259572771c19e3ff3a8482b8a8af4239566b3899c668e20f"
    end
  end

  def install
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "paimos-agentd-darwin-#{arch}" => "aeon-agentd"
  end

  test do
    assert_match "260929113854.0.0", shell_output("#{bin}/aeon-agentd --version")
  end
end
